// Plan-prompt builders: the centerpiece functions that produce the
// markdown prompt sent to the architect at PLAN stage, plus the prior-
// rejection feedback header that prepends when re-planning a rejected
// item.
//
// Extracted from server/factory/loop-controller.js as part of Phase 1a.
// Behavior preserved; no signature changes.

const path = require('path');
const {
  inferAutoGeneratedPlanTechStack,
  extractManagedWorktreePlanPath,
  isInternalTempWorktreePlanPath,
  isManagedWorktreePlanPath,
} = require('../shared/plan-path');
const {
  collectArchitectScopeDetails,
} = require('../shared/scope-search');
const {
  getEffectiveProjectProvider,
  getProjectVerifyCommand,
  isRemoteVerificationDisabled,
} = require('../shared/project-config');
const {
  CODEGRAPH_PLANNER_PROMPT_SECTION,
  PLAN_GENERATION_REPOSITORY_BOUNDARY_SECTION,
} = require('../shared/prompt-sections');

const PATH_LIKE_TOKEN_RE = /[A-Za-z]:[^\s`'")\]}]+|\/[A-Za-z0-9_.@-][^\s`'")\]}]*(?:\/[^\s`'")\]}]+)+|(?:\.{1,2}[\\/])?[A-Za-z0-9_.@-]+(?:[\\/][A-Za-z0-9_.@#:+-]+)+/g;

function splitTrailingPromptPathPunctuation(value) {
  let core = String(value || '');
  let suffix = '';
  while (core.length > 0 && /[.,;:!?]+$/.test(core)) {
    suffix = core.slice(-1) + suffix;
    core = core.slice(0, -1);
  }
  return { core, suffix };
}

function cleanRepoRelativePromptPath(value) {
  const normalized = String(value || '').replace(/\\/g, '/').replace(/^\/+/, '').replace(/^\.\//, '');
  if (!normalized || normalized.startsWith('../')) return null;
  if (isInternalTempWorktreePlanPath(normalized) || isManagedWorktreePlanPath(normalized)) return null;
  return normalized;
}

function extractInternalTaskWorktreePromptPath(filePath) {
  const normalized = String(filePath || '').trim().replace(/\\/g, '/').replace(/^\.\//, '');
  const segments = normalized.split('/').filter(Boolean);
  for (let i = 0; i < segments.length - 2; i += 1) {
    if (segments[i] === '.tmp' && segments[i + 1] === 'worktrees') {
      return cleanRepoRelativePromptPath(segments.slice(i + 3).join('/'));
    }
  }
  return null;
}

function rewriteProjectAbsolutePromptPath(filePath, projectPath) {
  if (!projectPath) return null;
  const normalized = String(filePath || '').replace(/\\/g, '/');
  const root = path.resolve(projectPath).replace(/\\/g, '/');
  const prefix = `${root}/`;
  if (!normalized.toLowerCase().startsWith(prefix.toLowerCase())) {
    return null;
  }
  return cleanRepoRelativePromptPath(normalized.slice(prefix.length));
}

function rewritePromptPathToken(value, projectPath = null) {
  const { core, suffix } = splitTrailingPromptPathPunctuation(value);
  const normalized = core.replace(/\\/g, '/').replace(/^\.\//, '');
  if (!normalized) return value;

  if (/^(?:\.claude|\.codex|\.torque)\//i.test(normalized)
    || /\/(?:\.claude|\.codex|\.torque)\//i.test(normalized)) {
    return `repo-relative project file${suffix}`;
  }

  const internalRel = extractInternalTaskWorktreePromptPath(normalized);
  if (internalRel) return `${internalRel}${suffix}`;
  if (isInternalTempWorktreePlanPath(normalized)) {
    return `repo-relative project file${suffix}`;
  }

  const managedRel = extractManagedWorktreePlanPath(normalized);
  if (managedRel) return `${managedRel}${suffix}`;
  if (isManagedWorktreePlanPath(normalized)) {
    return `repo-relative project file${suffix}`;
  }

  const projectRel = rewriteProjectAbsolutePromptPath(normalized, projectPath);
  if (projectRel) return `${projectRel}${suffix}`;

  return value;
}

function sanitizePlanPromptText(value, projectPath = null) {
  if (typeof value !== 'string') return value;
  return value.replace(PATH_LIKE_TOKEN_RE, (match) => rewritePromptPathToken(match, projectPath));
}

function escapePromptRedactionRegExp(value) {
  return String(value || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function redactProjectVerifyCommandFromPromptText(value, projectVerifyCommand, projectPath = null) {
  if (typeof value !== 'string') return value;
  const commands = [
    projectVerifyCommand,
    sanitizePlanPromptText(projectVerifyCommand, projectPath),
  ]
    .map((entry) => (typeof entry === 'string' ? entry.trim() : ''))
    .filter(Boolean);

  let redacted = value;
  for (const command of [...new Set(commands)]) {
    redacted = redacted.replace(
      new RegExp(escapePromptRedactionRegExp(command), 'gi'),
      'the configured project verify command',
    );
  }
  return redacted;
}

function sanitizePlanPromptWorkItemForScope(workItem, projectPath = null, projectVerifyCommand = null) {
  if (!workItem || typeof workItem !== 'object') return workItem;
  return {
    ...workItem,
    title: sanitizePlanPromptText(workItem.title, projectPath),
    description: redactProjectVerifyCommandFromPromptText(
      sanitizePlanPromptText(workItem.description, projectPath),
      projectVerifyCommand,
      projectPath,
    ),
  };
}

function buildAutoGeneratedPlanPrompt(project, workItem, priorFeedback = null) {
  const projectPath = project?.path || null;
  const projectVerifyCommand = getProjectVerifyCommand(project);
  const sanitizedWorkItem = sanitizePlanPromptWorkItemForScope(workItem, projectPath, projectVerifyCommand);
  const projectBrief = typeof project?.brief === 'string' && project.brief.trim()
    ? redactProjectVerifyCommandFromPromptText(
        sanitizePlanPromptText(project.brief.trim(), projectPath),
        projectVerifyCommand,
        projectPath,
      )
    : 'No project brief provided.';
  const description = String(sanitizedWorkItem?.description || '').trim();
  const title = sanitizePlanPromptText(sanitizedWorkItem?.title || '', projectPath);
  const techStack = inferAutoGeneratedPlanTechStack(projectPath);
  const scopeDetails = collectArchitectScopeDetails(sanitizedWorkItem, projectPath);
  const {
    scopeFiles,
    candidateFiles,
    hardScopeFiles,
    relatedFiles,
    priorMissingTargetHints,
  } = scopeDetails;
  const effectiveProvider = getEffectiveProjectProvider(project);
  const remoteVerificationDisabled = isRemoteVerificationDisabled(project);
  const validationPolicyLines = remoteVerificationDisabled
    ? [
        '- Remote validation is disabled for this project. Do not write `torque-remote` commands.',
        projectVerifyCommand
          ? '- The orchestrator runs the configured project verify command locally after EXECUTE. Leave full-suite or heavyweight validation to that orchestrator verify step.'
          : '- Leave full-suite or heavyweight validation to the orchestrator verify step.',
        '- For task-level validation, use lightweight focused checks only, such as `git diff --check`, targeted linters, or a narrow unit-test command that is not a heavyweight full build/test suite.',
      ]
    : [
        '- Treat `.NET build/test` commands and repo build-wrapper scripts as heavyweight. If one of those commands must appear in a task body, prefix it with `torque-remote`.',
      ];
  const validationCommandExample = remoteVerificationDisabled
    ? '   path/to/spec.js`, `git diff --check`, `npx tsc --noEmit`, or `cargo test`.'
    : '   path/to/spec.js`, `torque-remote dotnet test tests/MyApp.Tests/MyApp.Tests.csproj`,\n   `npx tsc --noEmit`, or `cargo test`.';
  // Phase G: small local models (qwen3-coder:30b on the ollama lane)
  // can't drive the cg_* MCP tools effectively and timeout trying. Skip
  // the codegraph research section for ollama-pinned projects so the
  // prompt stays under ~2K chars and the architect has a real shot at
  // completing within the (also tightened) plan-generation timeout.
  const useOllamaShortPrompt = effectiveProvider === 'ollama';
  // Opt-in only, gated on its OWN env var — deliberately NOT
  // TORQUE_CODEGRAPH_ENABLED. That var controls the codegraph *plugin*
  // (default ON; `0` disables it), so reusing it here meant enabling the
  // plugin — or setting the var to `1` redundantly — silently flipped this
  // prompt section on too. Live plan-generation runs through provider CLIs
  // (claude-cli with `--strict-mcp-config` and no `--mcp-config`, codex,
  // ollama) that do NOT receive TORQUE's cg_* MCP tools. Advertising those
  // tools made the generator fabricate `<tool_call>`/`<tool_result>`
  // transcripts with invented file paths, which the plan-quality gate then
  // correctly rejected — every plan, indefinitely. Gate on a dedicated
  // TORQUE_CODEGRAPH_PLANNER_PROMPT var so operators opt in only for
  // environments that actually mount the cg_* tools into the worker process.
  const codegraphEnabled = process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT === '1'
    && !useOllamaShortPrompt
    && hardScopeFiles.length === 0;

  const prompt = [
    'You are generating an execution plan for a single factory work item.',
    '',
    'Return Markdown only. Do not wrap the response in code fences.',
    'Do not include commentary before or after the plan.',
    'Use this exact structure:',
    `# ${title || `Work Item ${workItem?.id}`} Plan`,
    `**Source:** auto-generated from work_item #${workItem?.id}`,
    `**Tech Stack:** ${techStack}`,
    '',
    '## Task 1: <task title>',
    '',
    '- [ ] **Step 1: <step title>**',
    '',
    '    Concrete implementation instructions, including relevant file paths.',
    '',
    '- [ ] **Step 2: Validate targeted change**',
    '',
    '    Run `<targeted validation command>` and state the expected passing result.',
    '',
    'Rules:',
    '- Use `## Task N:` headings exactly.',
    '- Use `- [ ] **Step N: ...**` checkbox lines exactly.',
    '- Use 1 to 5 tasks total.',
    '- Keep every task specific and executable.',
    '- Every task must perform a repository change: implementation, test coverage, documentation, or tracked evidence.',
    '- Every task body, not only the task heading, must include a backtick-wrapped concrete file path or grep/search target.',
    '- For edit/update/extend/fix tasks, name only files that already exist in the repository. If a needed file does not exist, either choose the real existing module or make the task an explicit create-file task.',
    '- Each create-file task must name a distinct output path. Do not reuse one new test/module path across multiple tasks, and do not say "Create" for a file that already exists; say "Edit" when adding cases to an existing suite.',
    '- Documentation tasks must name the exact documentation file to edit or create; do not say "README or similar" without a concrete `docs/...md` path.',
    '- Treat existing related files as evidence of completed work, not a todo list to recreate. Do not emit tasks that merely add or re-implement files already listed under "Existing repository files related to this work item".',
    '- If prior feedback says the work is already complete, already implemented, or would be a no-op, plan only the remaining gap: fix the failing validation/safeguard, add missing coverage, update tracked evidence/docs, or make a narrow corrective change that is not already present.',
    '- Do not create analysis-only, read-only, search-only, or validation-only tasks. Avoid task titles whose main action is identify, analyze, locate, inspect, examine, research, investigate, review, read, search, run, verify, or confirm. Put necessary reading and validation inside the implementation step for the file being changed.',
    '- If only one file needs a documentation, test, or implementation edit, emit one edit task for that file. Do not split the work into a separate inspect/read task followed by an edit task.',
    '- Do not include commit steps or `git commit` commands. Factory execution commits completed task changes after verification.',
    '- Use indented detail lines under steps. Do not use fenced code blocks.',
    '- Preserve the `**Source:** auto-generated from work_item #<id>` line.',
    '- Use repo-relative paths in implementation steps and validation commands. Do not cite absolute paths, managed worktree paths, internal task-isolation temp paths, hidden agent/config directories, or TORQUE runtime directories as task edit targets.',
    '- Do not tell the worker to create, switch to, or work inside another git worktree; factory execution already runs inside the isolated worktree for this batch.',
    '- The orchestrator runs the project verify command after task completion. Do not tell the worker to run the full build/test suite in task bodies.',
    ...validationPolicyLines,
    '- Targeted validation commands must point at relevant source/test files or existing repo scripts. Do not pass config or metadata files such as `.torque-remote.json`, `.env`, `package.json`, lockfiles, or test-runner config files as `vitest`, `pytest`, or `npm test --` targets.',
    '- Targeted validation commands must list each file path only once. Do not repeat the same test file multiple times in one command.',
    '- Match test file location to the code under test: server-side modules and database/workflow/runtime behavior belong under `server/tests/...` or a plugin-local `server/plugins/<plugin>/tests/...` file. Use `dashboard/src/views/*.test.jsx` only for React dashboard view/component tests.',
    '- For Vitest test files in this repository, do not include `require(\'vitest\')`, `import { ... } from \'vitest\'`, or dynamic `import(\'vitest\')` in plan-authored test code. Use the injected globals directly: `describe`, `it`, `test`, `expect`, `beforeEach`, `afterEach`, and `vi`.',
    '- If source docs, old plans, or examples show Vitest imports/requires, treat them as stale context and rewrite the planned test code to use Vitest globals.',
    '- Do not edit `.torque-remote.json`, remote execution settings, routing templates, or provider config unless this work item explicitly asks for remote execution, routing, or provider configuration changes.',
    '',
    'Every task body MUST include all five of these specificity signals,',
    'otherwise the plan-quality gate rejects it. Each signal is worth 20',
    'points; tasks need >= 80 points (4 of 5) to pass.',
    '1. Explicit file paths — cite the concrete files you will edit or',
    '   create, e.g. `example-project/agent/session.py` or `tests/test_foo.py`.',
    '2. Estimated scope — mention how many files/lines/tests/functions',
    '   are in scope, e.g. "~3 files", "two tests", "single helper".',
    '3. Success criteria — say what "done" looks like with words like',
    '   "acceptance criteria", "must", "should pass", "ensures that".',
    '4. Validation steps — include the exact command that proves the',
    '   task is done, e.g. `pytest tests/test_foo.py`, `npx vitest run',
    validationCommandExample,
    '5. Concrete language — avoid bare verbs like "improve", "handle",',
    '   "update", "modify", "clean up", "as needed" in task titles,',
    '   step titles, or task bodies. If you use them, qualify with a',
    '   nearby file path, function name, or backtick identifier.',
    '',
    PLAN_GENERATION_REPOSITORY_BOUNDARY_SECTION,
    ...(codegraphEnabled ? [CODEGRAPH_PLANNER_PROMPT_SECTION] : []),
    'Project context:',
    `- Project ID: ${project?.id || 'unknown'}`,
    `- Project name: ${project?.name || 'unknown'}`,
    `- Project path: ${project?.path || 'unknown'}`,
    `- Project brief: ${projectBrief}`,
    '',
    'Work item context:',
    `- Work item ID: ${workItem?.id || 'unknown'}`,
    `- Source: ${workItem?.source || 'unknown'}`,
    `- Title: ${title || 'Untitled work item'}`,
    ...(scopeFiles.length > 0 ? [
      '',
      'Files in scope (cite these in task bodies when they match the requested implementation area):',
      ...scopeFiles.map((f) => `- \`${f}\``),
      'These paths were verified under the project tree or came from trusted work-item scope. Prefer them over guessed paths from prose; do NOT invent unrelated paths.',
    ] : []),
    ...(candidateFiles.length > 0 ? [
      '',
      'Candidate paths mentioned by the work item but not currently present in the project tree:',
      ...candidateFiles.map((f) => `- \`${f}\``),
      'For additive implementation work, prefer creating these candidate files directly when they match the requested feature area.',
      'Only resolve to existing files below when they share the same feature area; do not substitute generated plan docs, findings docs, or language-mismatched tests for implementation targets.',
    ] : []),
    ...(priorMissingTargetHints.length > 0 ? [
      '',
      'Prior missing target resolution hints:',
      ...priorMissingTargetHints.map((hint) => `- \`${hint.missing}\` does not exist. Prefer existing nearby candidate(s): ${hint.candidates.map((f) => `\`${f}\``).join(', ')}.`),
      'Do not reuse prior missing paths in edit tasks. Choose one of the listed existing candidates or make the task an explicit create-file task.',
    ] : []),
    ...(relatedFiles.length > 0 ? [
      '',
      'Existing repository files related to this work item (use these to resolve "expected near" or "nearest existing" wording):',
      ...relatedFiles.map((f) => `- \`${f}\``),
    ] : []),
    ...(hardScopeFiles.length > 0 ? [
      '',
      'Hard file boundary:',
      '- This work item declares explicit `allowed_files`; treat that list as the maximum read/write scope for plan generation.',
      '- Do not read, search, summarize, or rely on files outside `allowed_files` while generating this plan.',
      '- If shell search is needed, pass only the allowed file paths as operands; do not run repo-wide `rg`, `git grep`, `find`, or directory scans.',
      '- Emit the smallest viable plan, preferably one implementation task, that stays within `allowed_files`.',
    ] : []),
    '',
    'Description:',
    description,
  ].join('\n');

  const sanitizedPriorFeedback = redactProjectVerifyCommandFromPromptText(
    sanitizePlanPromptText(priorFeedback, projectPath),
    projectVerifyCommand,
    projectPath,
  );
  if (typeof sanitizedPriorFeedback === 'string' && sanitizedPriorFeedback.trim().length > 0) {
    return `${sanitizedPriorFeedback.trim()}\n\n---\n\n${prompt}`;
  }
  return prompt;
}

function normalizePriorGateFeedback(value) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function buildPriorRejectionFeedbackPrompt(rejection, gateFeedback = null) {
  const rejectionObject = rejection && typeof rejection === 'object' ? rejection : {};
  const failingTasks = Array.isArray(rejectionObject.failing_tasks) ? rejectionObject.failing_tasks : [];
  const missingSignals = Array.isArray(rejectionObject.missing_specificity_signals)
    ? rejectionObject.missing_specificity_signals
    : [];
  const reasons = Array.isArray(rejectionObject.reasons) ? rejectionObject.reasons : [];
  const semanticFeedback = normalizePriorGateFeedback(rejectionObject.feedback_prompt)
    || normalizePriorGateFeedback(gateFeedback);
  // If we have nothing useful to feed back, signal "no feedback" rather than
  // an empty header that wastes prompt budget.
  if (
    failingTasks.length === 0
    && missingSignals.length === 0
    && reasons.length === 0
    && !semanticFeedback
  ) {
    return null;
  }

  const lines = [
    '## PRIOR PLAN REJECTED — your last attempt at this work item failed the quality gate.',
    '',
    'You MUST address the issues below in this new plan. Producing a plan',
    'with the same shape as before will be rejected again.',
    '',
  ];

  if (typeof rejectionObject.score === 'number' && typeof rejectionObject.threshold === 'number') {
    lines.push(`### Prior score: ${rejectionObject.score} / threshold ${rejectionObject.threshold}`);
    lines.push('');
  }

  if (failingTasks.length > 0) {
    lines.push('### Failing tasks from prior attempt:');
    for (const ft of failingTasks) {
      const num = typeof ft.task_index === 'number' ? `Task ${ft.task_index + 1}` : 'Task';
      const title = ft.task_title ? `: ${ft.task_title}` : '';
      lines.push(`- **${num}${title}** (score ${ft.score ?? '?'} / ${ft.threshold ?? '?'})`);
      const ftMissing = Array.isArray(ft.missing_specificity_signals) ? ft.missing_specificity_signals : [];
      if (ftMissing.length > 0) {
        lines.push(`  - Missing signals: ${ftMissing.join(', ')}`);
      }
      const ftReasons = Array.isArray(ft.reasons) ? ft.reasons : [];
      for (const r of ftReasons) lines.push(`  - ${r}`);
    }
    lines.push('');
  } else if (missingSignals.length > 0 || reasons.length > 0) {
    // Fallback: top-level signals when failing_tasks wasn't captured.
    if (missingSignals.length > 0) {
      lines.push(`### Missing signals: ${missingSignals.join(', ')}`);
    }
    if (reasons.length > 0) {
      lines.push('### Reasons:');
      for (const r of reasons) lines.push(`- ${r}`);
    }
    lines.push('');
  }

  if (semanticFeedback) {
    lines.push('### Prior gate feedback:');
    lines.push(semanticFeedback);
    lines.push('');
  }

  lines.push('### Required for this attempt:');
  lines.push('- Cite **explicit file paths** in every task body (`example-project/agent/session.py`, etc.)');
  lines.push('- State **estimated scope** ("~3 files", "two tests", "single helper")');
  lines.push('- Include **validation steps** (the exact command that proves the task is done)');
  lines.push('- Use distinct output paths for create-file tasks; if adding to an existing file, say **Edit** that file instead of **Create**');
  lines.push('- Do not repeat the same test/source path multiple times in one validation command');
  lines.push('- For repository Vitest tests, do **not** use `require(\'vitest\')`, `import { ... } from \'vitest\'`, or dynamic `import(\'vitest\')`; rely on injected globals like `describe`, `it`, `expect`, and `vi`.');
  lines.push('- Use **success criteria** language ("must", "should pass", "ensures that")');
  lines.push('- Avoid bare verbs like "improve", "handle", "as needed" without a backtick identifier nearby');
  lines.push('- Do **not** re-plan work that prior feedback says already exists; target only the remaining failing validation/safeguard, missing coverage, tracked evidence, or other concrete gap.');
  lines.push('');

  return lines.join('\n');
}

module.exports = {
  buildAutoGeneratedPlanPrompt,
  buildPriorRejectionFeedbackPrompt,
  sanitizePlanPromptText,
};
