// Task-spec builders: take a parsed plan-task plus its work item and
// produce the human-readable strings that fill the task body's
// specificity slots (scope detail, validation command, file list).
//
// Extracted from server/factory/loop-controller.js as part of Phase 1a.
// Behavior preserved; no signature changes.
//
// What stays in loop-controller for now: `augmentAutoGeneratedTaskSpecificity`,
// `buildTaskSpecificityAdditions`, and `buildImplementationTaskFromAnalysis`,
// because each depends on `scoreAutoGeneratedTaskDescription` (plan-quality
// scoring engine) or `summarizeWorkItemImplementationGoal` which haven't
// been lifted yet.

const {
  getWorkItemConstraintsObject,
} = require('../shared/workitem-accessors');
const {
  extractPlanDescriptionFilePaths,
  inferAutoGeneratedPlanValidationCommand,
} = require('../shared/plan-path');
const {
  collectArchitectScopeFiles,
} = require('../shared/scope-search');
const {
  buildWorkItemValidationDetail,
  buildWorkItemScopeDetail,
} = require('./workitem-spec');

function formatPlanDescriptionFileList(filePaths, limit = 4) {
  const files = [...new Set((filePaths || []).map((file) => String(file || '').trim()).filter(Boolean))];
  if (files.length === 0) return null;
  const shown = files.slice(0, limit).map((file) => `\`${file}\``).join(', ');
  return files.length > limit ? `${shown}, and ${files.length - limit} more` : shown;
}

function getTaskSpecificityFilePaths(task, workItem, planFilePaths = []) {
  const taskText = `${task?.title || ''}\n${task?.body || ''}`;
  if (/\b(?:doc|docs|documentation|readme)\b/i.test(taskText)) {
    const docPaths = collectArchitectScopeFiles(workItem)
      .filter((file) => /(?:^|[\\/])docs?[\\/]|(?:^|[\\/])README\.md$|\.md$/i.test(file));
    if (docPaths.length > 0) return docPaths;
  }
  const direct = extractPlanDescriptionFilePaths(`${task?.title || ''}\n${task?.body || ''}`);
  if (direct.length > 0) return direct;
  if (Array.isArray(planFilePaths) && planFilePaths.length > 0) return planFilePaths;
  return collectArchitectScopeFiles(workItem);
}

function buildTaskScopeDetail(task, workItem, planFilePaths = [], score = null) {
  // Workitem-level hard constraints (allowed_files + max_files) take
  // precedence: when the workitem says "up to 1 file, limited to X",
  // the lint-pass test for ollama-canary plans expects that exact phrasing
  // even when the task body also names the file directly. Falling through
  // to score.file_paths or task-extracted paths would emit "centered on"
  // instead of "limited to" and lose the constraint signal.
  const constraints = getWorkItemConstraintsObject(workItem);
  const hasHardConstraints = Number(constraints.max_files) > 0
    && Array.isArray(constraints.allowed_files)
    && constraints.allowed_files.length > 0;
  if (hasHardConstraints) {
    const constraintDetail = buildWorkItemScopeDetail(workItem);
    if (constraintDetail) return constraintDetail;
  }

  const directPaths = Array.isArray(score?.file_paths) ? score.file_paths : [];
  if (directPaths.length > 0) {
    return `${directPaths.length} file${directPaths.length === 1 ? '' : 's'}, centered on ${formatPlanDescriptionFileList(directPaths)}`;
  }

  const fallbackPaths = getTaskSpecificityFilePaths(task, workItem, planFilePaths);
  if (fallbackPaths.length > 0) {
    return `${fallbackPaths.length} file${fallbackPaths.length === 1 ? '' : 's'}, centered on ${formatPlanDescriptionFileList(fallbackPaths)}`;
  }

  return buildWorkItemScopeDetail(workItem) || '1 focused change';
}

function buildTaskValidationDetail(task, workItem, project, planFilePaths = []) {
  const explicit = buildWorkItemValidationDetail(workItem);
  if (explicit) return explicit;

  const paths = getTaskSpecificityFilePaths(task, workItem, planFilePaths);
  const testPath = paths.find((file) => /(?:^|[\\/])(?:__tests__|tests?)[\\/].*\.(?:test|spec)?\.[cm]?[jt]sx?$/i.test(file)
    || /\.(?:test|spec)\.[cm]?[jt]sx?$/i.test(file));
  if (testPath) {
    return `npx vitest run ${testPath}`;
  }

  const jsPath = paths.find((file) => /\.(?:cjs|mjs|js)$/i.test(file));
  if (jsPath) {
    return `node --check ${jsPath}`;
  }

  if (paths.some((file) => /\.(?:ts|tsx)$/i.test(file))) {
    return 'npx tsc --noEmit';
  }

  const pyPath = paths.find((file) => /\.(?:py)$/i.test(file));
  if (pyPath) {
    return `pytest ${pyPath}`;
  }

  return inferAutoGeneratedPlanValidationCommand(project?.path);
}

function buildImplementationTaskTitle(workItem) {
  let title = String(workItem?.title || '').trim()
    .replace(/^[^:]{0,80}:\s*/, '')
    .replace(/\b(?:continue|slice|task)\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
  title = title.replace(/^(?:add|create|define|expose|export|extract|fix|harden|implement|introduce|persist|refactor|repair|support|validate|wire)\s+/i, '');
  return `Implement ${title || `work item ${workItem?.id || ''}`.trim()}`;
}

module.exports = {
  formatPlanDescriptionFileList,
  getTaskSpecificityFilePaths,
  buildTaskScopeDetail,
  buildTaskValidationDetail,
  buildImplementationTaskTitle,
};
