// JSDoc typedefs for the data shapes flowing through plan-builders/.
//
// This file exports nothing at runtime — it exists so other modules can
// reference these typedefs via `@typedef {import('./types').WorkItem}`.
// Once a TypeScript migration ships, these definitions become the seed
// for the real interface declarations.

/**
 * @typedef {Object} ProjectRow
 *   The "project" argument threaded through every builder. Comes from the
 *   `factory_projects` table row or its `factory_projects_with_config`
 *   view. Builders only read from this object — they never mutate it.
 * @property {string|number} [id] — project id
 * @property {string} [name] — short human-readable project name
 * @property {string} [path] — absolute path to the project on disk
 * @property {string} [brief] — short freeform description shown in prompts
 * @property {Object} [config] — parsed project config (preferred)
 * @property {string} [config_json] — JSON-encoded config (fallback)
 */

/**
 * @typedef {Object} WorkItem
 *   The "work item" argument threaded through every builder. Comes from
 *   the `factory_work_items` table row. Builders read from many
 *   conventional fields; missing fields produce conservative defaults.
 * @property {string|number} [id]
 * @property {string} [title]
 * @property {string} [description]
 * @property {string} [source]
 * @property {Object} [origin] — parsed origin object (preferred)
 * @property {string} [origin_json] — JSON-encoded origin (fallback)
 * @property {Object} [constraints] — parsed constraints (preferred)
 * @property {string} [constraints_json] — JSON-encoded constraints (fallback)
 * @property {string} [reject_reason] — current rejection reason (if any)
 */

/**
 * @typedef {Object} PlanTask
 *   A parsed plan task fragment. Produced by the plan parser; consumed by
 *   task-spec builders that score and augment the body.
 * @property {number} [index] — 1-based task index inside the plan
 * @property {string} title
 * @property {string} body
 */

/**
 * @typedef {Object} TaskScore
 *   The scoring verdict returned by `scoreAutoGeneratedTaskDescription`
 *   in loop-controller. Plan-builders treat it as opaque — they read
 *   `passed`, `missing_signals`, and `file_paths` only.
 * @property {boolean} passed
 * @property {string[]} [missing_signals]
 * @property {string[]} [file_paths]
 */

/**
 * @typedef {Object} ArchitectScopeDetails
 *   Output of `collectArchitectScopeDetails` from `shared/scope-search`.
 *   Used by the plan prompt builder to fill in "Files in scope", "Candidate
 *   paths", "Existing repository files related", and "Hard file boundary"
 *   sections.
 * @property {string[]} scopeFiles
 * @property {string[]} candidateFiles
 * @property {string[]} hardScopeFiles
 * @property {string[]} relatedFiles
 */

/**
 * @typedef {Object} PlanQualityRejection
 *   The shape persisted on a work item's
 *   `origin.last_plan_description_quality_rejection`. Consumed by
 *   `prompt.js`'s `buildPriorRejectionFeedbackPrompt` to surface the
 *   prior gate verdict in the next architect attempt.
 * @property {number} [score]
 * @property {number} [threshold]
 * @property {Array<{
 *   task_index?: number,
 *   task_title?: string,
 *   score?: number,
 *   threshold?: number,
 *   missing_specificity_signals?: string[],
 *   reasons?: string[],
 * }>} [failing_tasks]
 * @property {string[]} [missing_specificity_signals]
 * @property {string[]} [reasons]
 * @property {string|null} [feedback_prompt]
 */

/**
 * @typedef {Object} GateVerdict
 *   The shape produced by the plan-quality gate (server/factory/plan-quality-gate.js).
 *   Consumed by `quality-reject.js`'s `buildPlanQualityGateRejectPayload`
 *   to translate gate hard-fails into the work-item rejection payload.
 * @property {Array<{ rule?: string, detail?: string, taskNumber?: number }>} [hardFails]
 * @property {string|null} [feedbackPrompt]
 */

module.exports = {};
