'use strict';

/**
 * Post-Task Validation Module
 *
 * Extracted from task-manager.js — contains all post-execution validation,
 * quality checks, syntax verification, build/test/style runners, and rollback.
 *
 * Uses dependency injection (init()) for db, git utilities, and sanitization.
 */

const path = require('path');
const fs = require('fs');
const { execFileSync, spawnSync } = require('child_process');
const logger = require('../logger').child({ component: 'post-task-validation' });
const serverConfig = require('../config');
const { TASK_TIMEOUTS } = require('../constants');
const buildVerification = require('./build-verification');

/**
 * Parse a command string into executable and args, respecting quoted segments.
 * Handles both single and double quotes. Falls back to simple split for unquoted strings.
 * @param {string} cmdString - e.g. 'npm run build' or 'npx tsc --project "path with spaces"'
 * @returns {{ executable: string, args: string[] }}
 */
function parseCommand(cmdString) {
  const tokens = [];
  let current = '';
  let inSingle = false;
  let inDouble = false;

  for (let i = 0; i < cmdString.length; i++) {
    const ch = cmdString[i];
    if (ch === "'" && !inDouble) {
      inSingle = !inSingle;
    } else if (ch === '"' && !inSingle) {
      inDouble = !inDouble;
    } else if (ch === ' ' && !inSingle && !inDouble) {
      if (current.length > 0) {
        tokens.push(current);
        current = '';
      }
    } else {
      current += ch;
    }
  }
  if (current.length > 0) tokens.push(current);

  return {
    executable: tokens[0] || '',
    args: tokens.slice(1)
  };
}

// Dependency injection
let db = null;
let _getModifiedFiles = null;  // from utils/git
let _parseGitStatusLine = null;  // from utils/git
let _sanitizeLLMOutput = null;

/**
 * Initialize dependencies for this module.
 * Must be called before any other function.
 * @param {Object} deps
 * @param {Object} deps.db - Database module (getProjectFromPath, getProjectConfig, saveBuildResult)
 * @param {Function} deps.getModifiedFiles - From utils/git
 * @param {Function} deps.parseGitStatusLine - From utils/git
 * @param {Function} deps.sanitizeLLMOutput - From utils/sanitize
 */
function init(deps) {
  db = deps.db;
  serverConfig.init({ db: deps.db });
  _getModifiedFiles = deps.getModifiedFiles;
  _parseGitStatusLine = deps.parseGitStatusLine;
  _sanitizeLLMOutput = deps.sanitizeLLMOutput;
  buildVerification.init({ db, parseCommand, extractBuildErrorFiles });
}

const EXACT_PLACEHOLDER_MARKERS = [
  '// Placeholder — to be generated by LLM',
  '// Placeholder - to be generated by LLM',
  '// Placeholder',
  '# Placeholder — to be generated by LLM',
  '# Placeholder - to be generated by LLM',
  '# Placeholder',
];

const PLACEHOLDER_SIGNAL_PATTERNS = [
  { regex: /^\s*(?:\/\/|#)\s*Placeholder(?:\s*[—-]\s*to be generated by LLM)?\s*$/im, kind: 'placeholder marker' },
  { regex: /^\s*(?:\/\/|#)\s*TODO:?\s*(implement|add|fix|finish|complete)\b/im, kind: 'TODO implementation marker' },
  { regex: /^\s*throw new NotImplementedException/im, kind: 'NotImplementedException stub' },
  { regex: /^\s*raise NotImplementedError/im, kind: 'NotImplementedError stub' },
  { regex: /^\s*pass\s*#/m, kind: 'pass stub marker' },
  { regex: /^\s*\.\.\.\s*$/m, kind: 'ellipsis stub marker' },
  { regex: /^\s*(?:\/\/|#)\s*\.{3}\s*(rest of|remaining|same as|unchanged|code remains|implementation)/im, kind: 'truncation stub marker' },
  { regex: /\[truncated(?: for brevity)?\]/i, kind: 'truncation marker' },
];

function parseGitStatusEntry(line) {
  if (!line || line.length < 4) return null;

  if (typeof _parseGitStatusLine === 'function') {
    const parsed = _parseGitStatusLine(line);
    if (parsed && parsed.filePath) {
      return parsed;
    }
  }

  const indexStatus = line[0];
  const workStatus = line[1];
  const filePath = line.slice(3).replace(/^"/, '').replace(/"$/, '').trim();
  if (!filePath) return null;

  return {
    indexStatus,
    workStatus,
    filePath,
    isNew: indexStatus === 'A' || (indexStatus === '?' && workStatus === '?'),
    isModified: indexStatus === 'M' || workStatus === 'M',
    isDeleted: indexStatus === 'D' || workStatus === 'D',
    isRenamed: indexStatus === 'R',
  };
}

function getGitStatusEntries(workingDir) {
  if (!workingDir || !fs.existsSync(workingDir)) return [];

  try {
    const gitOutput = execFileSync('git', ['status', '--porcelain'], {
      cwd: workingDir,
      encoding: 'utf8',
      timeout: TASK_TIMEOUTS.GIT_STATUS,
      maxBuffer: 1024 * 1024,
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true,
    }).trim();

    if (!gitOutput) return [];

    return gitOutput
      .split('\n')
      .map(line => parseGitStatusEntry(line))
      .filter(Boolean);
  } catch (err) {
    logger.debug("task handler error", { err: err.message });
    return [];
  }
}

function normalizeRelativePath(filePath) {
  return String(filePath || '').replace(/\\/g, '/');
}

function resolveRollbackFilePath(change, workingDir) {
  if (!change || !workingDir) return null;
  if (change.is_outside_workdir) return null;

  const worktreeRoot = path.resolve(workingDir);
  let candidate = '';

  if (typeof change.relative_path === 'string' && change.relative_path.trim()) {
    candidate = change.relative_path.trim();
  } else if (typeof change.file_path === 'string' && change.file_path.trim()) {
    const rawPath = change.file_path.trim();
    if (path.isAbsolute(rawPath)) {
      const relativePath = path.relative(worktreeRoot, path.resolve(rawPath));
      if (!relativePath || relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
        return null;
      }
      candidate = relativePath;
    } else {
      candidate = rawPath;
    }
  }

  const normalized = normalizeRelativePath(candidate).replace(/^\.\/+/, '').trim();
  if (!normalized || normalized === '.' || normalized.includes('\0')) return null;

  const resolved = path.resolve(worktreeRoot, normalized);
  const relativeToRoot = path.relative(worktreeRoot, resolved);
  if (relativeToRoot.startsWith('..') || path.isAbsolute(relativeToRoot)) {
    return null;
  }

  return normalizeRelativePath(relativeToRoot);
}

function revertScopedFiles(workingDir, files, label = 'ScopedRollback') {
  if (!workingDir || !fs.existsSync(workingDir)) {
    return { reverted: [], skipped: Array.isArray(files) ? [...files] : [] };
  }

  const uniqueFiles = [...new Set((Array.isArray(files) ? files : [])
    .map(file => normalizeRelativePath(file).replace(/^\.\/+/, '').trim())
    .filter(Boolean))];

  if (uniqueFiles.length === 0) {
    return { reverted: [], skipped: [] };
  }

  const reverted = [];
  const skipped = [];

  for (const file of uniqueFiles) {
    try {
      execFileSync('git', ['ls-files', '--error-unmatch', '--', file], {
        cwd: workingDir,
        encoding: 'utf8',
        stdio: 'pipe',
        windowsHide: true,
      });
    } catch (err) {
      logger.debug("task handler error", { err: err.message });
      skipped.push(file);
      continue;
    }

    try {
      execFileSync('git', ['checkout', '--', file], {
        cwd: workingDir,
        encoding: 'utf8',
        stdio: 'pipe',
        windowsHide: true,
      });
      reverted.push(file);
    } catch (err) {
      logger.info(`[${label}] Failed to revert ${file}: ${err.message}`);
      skipped.push(file);
    }
  }

  if (reverted.length > 0) {
    logger.info(`[${label}] Reverted ${reverted.length} tracked file(s): ${reverted.join(', ')}`);
  } else {
    logger.info(`[${label}] No tracked files were reverted`);
  }

  if (skipped.length > 0) {
    logger.info(`[${label}] Skipped ${skipped.length} file(s): ${skipped.join(', ')}`);
  }

  return { reverted, skipped };
}

function scopedRollback(taskId, workingDir = null, label = 'ScopedRollback') {
  if (!db || typeof db.getTaskFileChanges !== 'function') {
    logger.info(`[${label}] Task ${taskId}: task file change tracking is unavailable`);
    return { reverted: [], skipped: [] };
  }

  const task = typeof db.getTask === 'function' ? db.getTask(taskId) : null;
  const resolvedWorkingDir = workingDir || task?.working_directory || null;
  if (!resolvedWorkingDir || !fs.existsSync(resolvedWorkingDir)) {
    logger.info(`[${label}] Task ${taskId}: working directory unavailable for scoped rollback`);
    return { reverted: [], skipped: [] };
  }

  const fileChanges = db.getTaskFileChanges(taskId) || [];
  const rollbackFiles = [...new Set(fileChanges
    .map(change => resolveRollbackFilePath(change, resolvedWorkingDir))
    .filter(Boolean))];

  if (rollbackFiles.length === 0) {
    logger.info(`[${label}] Task ${taskId}: no recorded task files to revert`);
    return { reverted: [], skipped: [] };
  }

  const result = revertScopedFiles(resolvedWorkingDir, rollbackFiles, label);
  logger.info(
    `[${label}] Task ${taskId}: reverted ${result.reverted.length} file(s), skipped ${result.skipped.length}`
  );
  return result;
}

function expandArtifactCandidatePaths(fullPath, relativePath) {
  try {
    const stat = fs.statSync(fullPath);
    if (stat.isFile()) {
      return [{ fullPath, relativePath: normalizeRelativePath(relativePath) }];
    }

    if (!stat.isDirectory()) return [];

    const nestedFiles = [];
    for (const entry of fs.readdirSync(fullPath, { withFileTypes: true })) {
      const childFullPath = path.join(fullPath, entry.name);
      const childRelativePath = path.posix.join(normalizeRelativePath(relativePath), entry.name);
      if (entry.isDirectory()) {
        nestedFiles.push(...expandArtifactCandidatePaths(childFullPath, childRelativePath));
      } else if (entry.isFile()) {
        nestedFiles.push({ fullPath: childFullPath, relativePath: childRelativePath });
      }
    }
    return nestedFiles;
  } catch (err) {
    logger.debug("task handler error", { err: err.message });
    return [];
  }
}

function describePlaceholderOnlyContent(content) {
  if (typeof content !== 'string') return null;

  const trimmed = content.trim();
  if (!trimmed) {
    return 'File is empty after generation';
  }

  const exactMarker = EXACT_PLACEHOLDER_MARKERS.find(marker => trimmed === marker);
  if (exactMarker) {
    return `File still contains only placeholder marker ${JSON.stringify(exactMarker)}`;
  }

  return null;
}

function extractMatchingLine(text, pattern) {
  if (typeof text !== 'string' || !text) return null;

  for (const line of text.split(/\r?\n/)) {
    if (!line.trim()) continue;
    if (pattern.test(line)) {
      return line.trim().slice(0, 160);
    }
  }

  return null;
}

function findPlaceholderOutputMarkers(outputText) {
  if (typeof outputText !== 'string' || outputText.trim().length === 0) {
    return { valid: true, issues: [], markers: [] };
  }

  const sanitizedOutput = typeof _sanitizeLLMOutput === 'function'
    ? _sanitizeLLMOutput(outputText)
    : outputText;

  const markers = [];
  const seen = new Set();

  for (const signal of PLACEHOLDER_SIGNAL_PATTERNS) {
    const snippet = extractMatchingLine(sanitizedOutput, signal.regex);
    if (!snippet) continue;
    const key = `${signal.kind}:${snippet}`;
    if (seen.has(key)) continue;
    seen.add(key);
    markers.push({ kind: signal.kind, snippet });
  }

  return {
    valid: markers.length === 0,
    issues: markers.map(marker =>
      `Task output still contains ${marker.kind} (${JSON.stringify(marker.snippet)}) but no validated file changes were produced. Produce a real edit or fail the task explicitly.`
    ),
    markers,
  };
}

function findPlaceholderArtifacts(workingDir, modifiedFiles = []) {
  const artifacts = [];
  if (!workingDir || !fs.existsSync(workingDir)) {
    return { valid: true, issues: [], artifacts: [] };
  }

  const ignoredPaths = new Set(
    (Array.isArray(modifiedFiles) ? modifiedFiles : [])
      .map(filePath => normalizeRelativePath(filePath))
      .filter(Boolean)
  );

  // Skip build output directories — compiled/minified assets trigger false positives
  const BUILD_OUTPUT_PATTERNS = /(?:^|\/)(?:dist|build|out|\.next|\.nuxt|node_modules)\//;

  for (const entry of getGitStatusEntries(workingDir)) {
    if (!entry || entry.isDeleted || !entry.filePath) continue;
    if (BUILD_OUTPUT_PATTERNS.test(entry.filePath)) continue;

    const fullPath = path.join(workingDir, entry.filePath);
    const candidates = expandArtifactCandidatePaths(fullPath, entry.filePath);
    if (candidates.length === 0) continue;

    for (const candidate of candidates) {
      if (ignoredPaths.has(candidate.relativePath)) continue;

      let content;
      try {
        content = fs.readFileSync(candidate.fullPath, 'utf8');
      } catch (err) {
        logger.debug("task handler error", { err: err.message });
        continue;
      }

      const exactReason = describePlaceholderOnlyContent(content);
      if (exactReason) {
        artifacts.push({
          path: candidate.relativePath,
          reason: exactReason,
          gitStatus: `${entry.indexStatus}${entry.workStatus}`,
        });
        continue;
      }

      const qualityResult = checkFileQuality(candidate.fullPath, { isNewFile: true });
      const placeholderIssue = qualityResult.issues.find(issue => issue.includes('placeholder/stub'));
      if (!placeholderIssue) continue;

      artifacts.push({
        path: candidate.relativePath,
        reason: 'File contains placeholder/stub content and is still present in the working tree',
        gitStatus: `${entry.indexStatus}${entry.workStatus}`,
      });
    }
  }

  return {
    valid: artifacts.length === 0,
    issues: artifacts.map(artifact =>
      `${artifact.path}: ${artifact.reason}. Replace it with real code or remove the file from this task.`
    ),
    artifacts,
  };
}

/**
 * Remove junk/garbage files created by LLM during task execution.
 * Detects files with names that look like natural language (not real paths)
 * and removes them from the working directory and git staging area.
 * @param {string} workingDir - The working directory to scan
 * @param {string} taskId - The task ID for logging
 */
function cleanupJunkFiles(workingDir, taskId) {
  // Patterns that indicate a junk filename (not a real file path)
  const junkPatterns = [
    /^(Sure|Here|For |TODO|Note|1st|2nd|3rd|Let me|I will|I'll|I can|OK|Okay|The |This |Now )/i,
    /^\d+\.\s/,  // Fix F2: "1. ", "2. ", etc. — numbered list items used as filenames
    /\b(as follows|here is|example|you can use|I will modify|replace with|for benchmarking)\b/i,
    / {3,}/,  // Multiple spaces in filename
    /^[^/\\]+\.(cs|xaml|json|xml|md|csproj|sln)\s*\(/,  // "File.cs (description)" pattern
  ];

  try {
    // Get list of new/modified files from git using execFileSync (no shell injection)
    let gitOutput;
    try {
      gitOutput = execFileSync('git', ['status', '--porcelain'], {
        cwd: workingDir,
        encoding: 'utf8',
        timeout: TASK_TIMEOUTS.GIT_STATUS,
        windowsHide: true,
      }).trim();
    } catch (err) {
      logger.debug("task handler error", { err: err.message });
      return; // Not a git repo or git error
    }

    if (!gitOutput) return;

    const files = gitOutput.split('\n')
      .map(f => f.replace(/^[AMDR?! ]{1,3}\s*"?/, '').replace(/"$/, '').trim())
      .filter(f => f.length > 0);

    let cleaned = 0;
    for (const file of files) {
      const basename = path.basename(file);
      const isJunk = junkPatterns.some(p => p.test(basename)) ||
        basename.length > 80 ||  // Filenames longer than 80 chars are likely junk
        (basename.includes(' ') && !path.extname(basename));  // Spaces + no extension

      if (isJunk) {
        const fullPath = path.join(workingDir, file);
        try {
          if (fs.existsSync(fullPath)) {
            fs.unlinkSync(fullPath);
            cleaned++;
            logger.info(`[JunkCleanup] Removed junk file: ${file} (task ${taskId})`);
          }
          // Also try to unstage from git
          try {
            execFileSync('git', ['reset', 'HEAD', '--', file], { cwd: workingDir, timeout: TASK_TIMEOUTS.GIT_RESET, windowsHide: true });
          } catch (err) { logger.debug("task handler error", { err: err.message }); /* ignore */ }
        } catch (err) {
          logger.debug("task handler error", { err: err.message });
          // Ignore cleanup errors for individual files
        }
      }
    }

    if (cleaned > 0) {
      logger.info(`[JunkCleanup] Removed ${cleaned} junk files for task ${taskId}`);
    }
  } catch (e) {
    // Non-fatal — just log
    logger.info(`[JunkCleanup] Error scanning for junk files: ${e.message}`);
  }
}

/**
 * Get file changes from git for validation.
 * Returns array of { path, content, size, originalSize, originalContent }
 * @param {string} workingDir - The working directory
 * @param {number} [numCommits=1] - Number of commits to look back
 * @returns {Array<Object>} File change objects
 */
function getFileChangesForValidation(workingDir, numCommits = 1) {
  const fileChanges = [];

  if (!workingDir || !fs.existsSync(workingDir)) {
    return fileChanges;
  }

  try {
    // Get list of files changed in last N commits
    let changedFilesRaw = '';
    try {
      changedFilesRaw = execFileSync('git', ['diff', '--name-only', `HEAD~${numCommits}`, 'HEAD'],
        { cwd: workingDir, encoding: 'utf8', windowsHide: true });
    } catch (err) {
      logger.debug("task handler error", { err: err.message });
      // Fallback: get staged/unstaged changes
      try {
        changedFilesRaw = execFileSync('git', ['diff', '--name-only', 'HEAD'],
          { cwd: workingDir, encoding: 'utf8', windowsHide: true });
      } catch (err) {
        logger.debug("task handler error", { err: err.message });
        return fileChanges;
      }
    }

    const changedFiles = changedFilesRaw
      .split('\n')
      .filter(f => f.trim())
      .filter(f => f.endsWith('.cs') || f.endsWith('.xaml') || f.endsWith('.ts') || f.endsWith('.tsx') || f.endsWith('.js') || f.endsWith('.py'));

    for (const relPath of changedFiles) {
      const fullPath = path.join(workingDir, relPath);

      if (!fs.existsSync(fullPath)) continue;

      try {
        const content = fs.readFileSync(fullPath, 'utf8');
        const size = Buffer.byteLength(content, 'utf8');

        // Get original content from before the commit
        let originalContent = '';
        let originalSize = 0;
        try {
          originalContent = execFileSync('git', ['show', `HEAD~${numCommits}:${relPath}`],
            { cwd: workingDir, encoding: 'utf8', windowsHide: true });
          originalSize = Buffer.byteLength(originalContent, 'utf8');
        } catch (err) {
          logger.debug("task handler error", { err: err.message });
          // File may be new, original size is 0
        }

        fileChanges.push({
          path: relPath,
          content,
          size,
          originalSize: originalSize || size, // If new file, use current size
          originalContent
        });
      } catch (err) {
        logger.info(`[Validation] Error reading file ${relPath}: ${err.message}`);
      }
    }
  } catch (err) {
    logger.info(`[Validation] Error getting file changes: ${err.message}`);
  }

  return fileChanges;
}

/**
 * Check file quality for LLM-generated content.
 * Detects empty stubs, tiny files, mostly-comment files, placeholder content,
 * stub destruction patterns, and diff/patch content accidentally written as code.
 * @param {string} filePath - Path to the file to check
 * @param {Object} [options] - Options
 * @param {boolean} [options.isNewFile] - If true, skip size/line-count checks
 *   (new files are expected to be small; only placeholder patterns are flagged)
 * @returns {Object} { valid: boolean, issues: string[] }
 */
function checkFileQuality(filePath, options = {}) {
  const issues = [];

  try {
    if (!fs.existsSync(filePath)) {
      return { valid: true, issues: [] }; // File doesn't exist, not our problem
    }

    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n');
    const nonEmptyLines = lines.filter(l => l.trim().length > 0);
    const codeLines = nonEmptyLines.filter(l => {
      const trimmed = l.trim();
      // Skip comments and common stub patterns
      return !trimmed.startsWith('//') &&
             !trimmed.startsWith('/*') &&
             !trimmed.startsWith('*') &&
             !trimmed.startsWith('#') &&
             trimmed !== '{' &&
             trimmed !== '}' &&
             trimmed !== '';
    });

    // Size/line-count checks — skip for newly created files since they start small.
    // Placeholder/stub pattern detection below still applies to all files.
    if (!options.isNewFile) {
      // Check for empty/stub files
      if (content.trim().length < 50) {
        issues.push(`File is nearly empty (${content.trim().length} chars)`);
      }

      // P85: Check for tiny files (less than 2 meaningful lines).
      // Previous threshold of 5 caused false positives on legitimate single-function
      // utilities (R69 camelCase, R72 clamp — both 2-3 code lines). Real stubs are
      // also caught by placeholder pattern detection below (TODO, NotImplementedException, etc).
      if (codeLines.length < 2 && nonEmptyLines.length > 0) {
        issues.push(`File has only ${codeLines.length} lines of code (likely a stub)`);
      }

      // Check for files that are mostly comments (>80% comments)
      if (nonEmptyLines.length > 10) {
        const commentRatio = (nonEmptyLines.length - codeLines.length) / nonEmptyLines.length;
        if (commentRatio > 0.8) {
          issues.push(`File is ${Math.round(commentRatio * 100)}% comments`);
        }
      }
    }

    // Check for placeholder content - patterns that indicate INCOMPLETE/STUB implementations
    // NOTE: Simple TODO comments are legitimate documentation, not stubs
    // Only flag patterns that clearly indicate unfinished/stub code
    // Patterns use ^ anchor with multiline to match actual code lines, not string content
    const placeholderPatterns = [
      /^\s*(?:\/\/|#)\s*\.\.\.$/m,                 // Comment line with just ellipsis (// or #)
      ...PLACEHOLDER_SIGNAL_PATTERNS.map(signal => signal.regex),
      /{\s*(?:\/\/|#)\s*TODO\s*}/,                 // Empty block with only TODO marker (// or #)
      /=>\s*{\s*}/,                               // Empty arrow function body
    ];
    for (const pattern of placeholderPatterns) {
      if (pattern.test(content)) {
        issues.push('File contains placeholder/stub content');
        break;
      }
    }

    // P95/P100: Count stub comments that replace method bodies — 2+ is mass destruction
    // P100: Match both // (JS/TS/C#) and # (Python) comment syntax
    const stubCommentPattern = /^\s*(?:\/\/|#)\s*\.{3}\s*(rest|remaining|same|unchanged|code|implementation)/gim;
    const stubMatches = content.match(stubCommentPattern);
    if (stubMatches && stubMatches.length >= 2) {
      issues.push(`File has ${stubMatches.length} stub comments replacing method bodies (P95: mass code destruction)`);
    }

    // Check for diff/patch content accidentally written as code
    // Must have diff markers at START of lines (actual diff format)
    const hasDiffHeaders = /^---\s+\S/m.test(content) && /^\+\+\+\s+\S/m.test(content);
    const hasHunkMarkers = /^@@\s+-\d+.*\+\d+.*@@/m.test(content);
    if (hasDiffHeaders && hasHunkMarkers) {
      issues.push('File contains diff/patch content instead of code');
    }

  } catch (err) {
    logger.debug("task handler error", { err: err.message });
    // Can't read file - not a quality issue, might be binary
  }

  return { valid: issues.length === 0, issues };
}

/**
 * Detect duplicate file modifications — new files that may shadow existing ones.
 * Uses `find` to locate other files with the same basename and checks git tracking status.
 * @param {string} workingDir - The working directory
 * @param {string[]} modifiedFiles - List of files modified
 * @returns {Object} { valid: boolean, issues: string[] }
 */
function checkDuplicateFiles(workingDir, modifiedFiles) {
  const issues = [];

  if (!modifiedFiles || modifiedFiles.length === 0) {
    return { valid: true, issues: [] };
  }

  try {
    for (const modFile of modifiedFiles) {
      // Skip if file doesn't exist (might be deleted)
      const fullPath = path.isAbsolute(modFile) ? modFile : path.join(workingDir, modFile);
      if (!fs.existsSync(fullPath)) continue;

      const fileName = path.basename(modFile);

      // Find other files with the same name using git ls-files (cross-platform, no `find` dependency)
      try {
        const result = execFileSync('git', ['ls-files', '--', `**/${fileName}`], {
          cwd: workingDir,
          encoding: 'utf8',
          timeout: TASK_TIMEOUTS.PROCESS_QUERY,
          maxBuffer: 1024 * 1024,
          stdio: ['pipe', 'pipe', 'pipe'],
        });

        const matches = result.trim().split('\n')
          .filter(f => f && path.resolve(workingDir, f) !== path.resolve(fullPath));
        if (matches.length > 0) {
          // Check if this is a new file (not in git history)
          try {
            execFileSync('git', ['ls-files', '--error-unmatch', modFile], {
              cwd: workingDir,
              encoding: 'utf8',
              stdio: 'pipe'
            });
            // File exists in git - not a new duplicate
          } catch (err) {
            logger.debug("task handler error", { err: err.message });
            // File is new (untracked) - potential shadow
            issues.push(`New file '${fileName}' may shadow existing: ${matches[0]}`);
          }
        }
      } catch (err) {
        logger.debug("task handler error", { err: err.message });
        // Find failed - skip this check
      }
    }
  } catch (err) {
    logger.info(`[Safeguard] Duplicate check error: ${err.message}`);
  }

  return { valid: issues.length === 0, issues };
}

/**
 * Run quick syntax validation on modified files.
 * Supports C# (brace matching), JavaScript (node --check), TypeScript (tsc or fallback),
 * JSON (JSON.parse), and Python (py_compile).
 * @param {string} workingDir - The working directory
 * @param {string[]} modifiedFiles - List of files modified
 * @returns {Object} { valid: boolean, issues: string[] }
 */
function checkSyntax(workingDir, modifiedFiles) {
  const issues = [];

  if (!modifiedFiles || modifiedFiles.length === 0) {
    return { valid: true, issues: [] };
  }

  for (const modFile of modifiedFiles) {
    const fullPath = path.isAbsolute(modFile) ? modFile : path.join(workingDir, modFile);
    if (!fs.existsSync(fullPath)) continue;

    const ext = path.extname(fullPath).toLowerCase();

    try {
      if (ext === '.cs') {
        // C# - check for basic syntax issues
        const content = fs.readFileSync(fullPath, 'utf8');
        // Limitation: brace counting includes braces inside string literals,
        // verbatim strings, comments, and preprocessor regions. A file with
        // balanced braces in strings but asymmetric structural braces could
        // be a false-negative (or vice-versa). This is a heuristic check only.
        const openBraces = (content.match(/\{/g) || []).length;
        const closeBraces = (content.match(/\}/g) || []).length;
        if (openBraces !== closeBraces) {
          issues.push(`${path.basename(fullPath)}: Mismatched braces (${openBraces} open, ${closeBraces} close)`);
        }

        // Check for missing namespace/class
        if (!content.includes('namespace ') && !content.includes('class ') &&
            !content.includes('interface ') && !content.includes('enum ')) {
          issues.push(`${path.basename(fullPath)}: Missing namespace/class/interface declaration`);
        }
      } else if (ext === '.js') {
        // JavaScript - use node to check syntax
        try {
          execFileSync('node', ['--check', fullPath], {
            cwd: workingDir,
            encoding: 'utf8',
            timeout: TASK_TIMEOUTS.SYNTAX_CHECK,
            stdio: 'pipe'
          });
        } catch (syntaxErr) {
          issues.push(`${path.basename(fullPath)}: Syntax error - ${syntaxErr.message.substring(0, 100)}`);
        }
      } else if (ext === '.ts' || ext === '.tsx') {
        // TypeScript — try tsserver cached diagnostics first (instant), fall back to tsc
        let usedTsserver = false;
        if (db && serverConfig.isOptIn('tsserver_enabled')) {
          try {
            const tsserverClient = require('../utils/tsserver-client');
            const cached = tsserverClient.getCachedDiagnostics(fullPath);
            if (cached !== null) {
              usedTsserver = true;
              const errors = cached.filter(d => d.category === 'error' || !d.category);
              for (const d of errors) {
                const loc = d.start ? `L${d.start.line}:${d.start.offset}` : '';
                issues.push(`${path.basename(fullPath)}: TS${d.code || '?'} ${loc} ${d.text || d.message || ''}`);
              }
            }
          } catch (err) { logger.debug("task handler error", { err: err.message }); /* tsserver not available — fall through to tsc */ }
        }

        if (!usedTsserver) {
          // tsc fallback — use tsc if available, fallback to brace-matching (P63 fix)
          // If tsconfig.json exists, use --project so tsc respects lib/target settings.
          // Passing a file directly to tsc ignores tsconfig.json (ES3 default = false positives).
          const hasTsconfig = fs.existsSync(path.join(workingDir, 'tsconfig.json'));
          const tscArgs = hasTsconfig
            ? ['tsc', '--noEmit', '--project', path.join(workingDir, 'tsconfig.json')]
            : ['tsc', '--noEmit', '--allowJs', '--esModuleInterop', fullPath];
          try {
            execFileSync('npx', tscArgs, {
              cwd: workingDir,
              encoding: 'utf8',
              timeout: TASK_TIMEOUTS.TYPESCRIPT_CHECK,
              stdio: 'pipe',
              shell: process.platform === 'win32'
            });
            // If using --project mode, tsc checked ALL files — skip remaining TS files
            if (hasTsconfig) break;
          } catch (tsErr) {
            // npx tsc may not be available — fallback to basic checks
            // P69: ENOENT means npx/tsc binary not found — not a code error
            const errMsg = tsErr.message || '';
            const toolMissing = errMsg.includes('ENOENT') || errMsg.includes('not found') || tsErr.status === 127;
            if (toolMissing) {
              // tsc not available — do basic brace/bracket matching like C#
              const content = fs.readFileSync(fullPath, 'utf8');
              const openBraces = (content.match(/\{/g) || []).length;
              const closeBraces = (content.match(/\}/g) || []).length;
              if (openBraces !== closeBraces) {
                issues.push(`${path.basename(fullPath)}: Mismatched braces (${openBraces} open, ${closeBraces} close)`);
              }
            } else {
              // tsc found a real error — errors are in stdout, not stderr
              const tscOutput = tsErr.stdout || tsErr.stderr || '';
              // When using --project, filter errors to only modified files
              const modifiedBaseNames = hasTsconfig
                ? new Set(modifiedFiles.map(f => path.basename(path.isAbsolute(f) ? f : path.join(workingDir, f))))
                : null;
              // Parse individual TS errors: "file(line,col): error TSxxxx: message"
              const errorLines = tscOutput.split(/\r?\n/).filter(l => l.includes(': error TS'));
              if (errorLines.length > 0) {
                for (const errLine of errorLines) {
                  // Extract "error TSxxxx: message" from "path/file(line,col): error TSxxxx: message"
                  const m = errLine.match(/([^(/\\]+)\((\d+),(\d+)\):\s*(error TS\d+:\s*.+)/);
                  if (m) {
                    const errFileName = m[1];
                    // In --project mode, skip errors from files we didn't modify
                    if (modifiedBaseNames && !modifiedBaseNames.has(errFileName)) continue;
                    issues.push(`${errFileName}: L${m[2]}:${m[3]} ${m[4]}`);
                  } else {
                    issues.push(`${errLine.substring(0, 200)}`);
                  }
                }
              } else {
                // Fallback: use raw output truncated
                const fileName = path.basename(fullPath);
                issues.push(`${fileName}: TypeScript error - ${tscOutput.substring(0, 300)}`);
              }
              // If using --project, we already checked all files — break out of the per-file loop
              if (hasTsconfig) break;
            }
          }
        }
      } else if (ext === '.json') {
        // JSON - try to parse
        try {
          JSON.parse(fs.readFileSync(fullPath, 'utf8'));
        } catch (jsonErr) {
          issues.push(`${path.basename(fullPath)}: Invalid JSON - ${jsonErr.message}`);
        }
      } else if (ext === '.py') {
        // Python - use python to check syntax
        // P69: Try python3 first, fall back to python (Windows uses python)
        const pythonCmd = process.platform === 'win32' ? 'python' : 'python3';
        try {
          execFileSync(pythonCmd, ['-m', 'py_compile', fullPath], {
            cwd: workingDir,
            encoding: 'utf8',
            timeout: TASK_TIMEOUTS.SYNTAX_CHECK,
            stdio: 'pipe'
          });
        } catch (pyErr) {
          const pyErrMsg = pyErr.message || '';
          if (pyErrMsg.includes('ENOENT') || pyErrMsg.includes('not found') || pyErr.status === 127) {
            // Python not available — skip syntax check
          } else {
            issues.push(`${path.basename(fullPath)}: Python syntax error`);
          }
        }
      }
    } catch (err) {
      logger.debug("task handler error", { err: err.message });
      // Skip file on error
    }
  }

  return { valid: issues.length === 0, issues };
}

/**
 * Run all LLM output safeguards — file quality, duplicate detection, and syntax checks.
 * Aggregates results from checkFileQuality, checkDuplicateFiles, and checkSyntax.
 * Detects new vs modified files via git status for context-aware validation.
 * @param {string} taskId - The task ID
 * @param {string} workingDir - The working directory
 * @param {string[]} modifiedFiles - List of modified files
 * @returns {Object} { passed: boolean, issues: string[], details: Object }
 */
function runLLMSafeguards(taskId, workingDir, modifiedFiles, options = {}) {
  const normalizedModifiedFiles = Array.isArray(modifiedFiles) ? modifiedFiles : [];
  const allIssues = [];
  const details = {
    fileQuality: { checked: 0, issues: [] },
    placeholderArtifacts: { checked: false, issues: [], artifacts: [] },
    outputMarkers: { checked: false, issues: [], markers: [] },
    duplicates: { checked: false, issues: [] },
    syntax: { checked: 0, issues: [] }
  };

  logger.info(`[Safeguard] Running LLM output safeguards for task ${taskId}`);

  // Detect which files are newly created (git status 'A' or '??') vs modified ('M').
  // New files skip size/line-count checks since tasks that create files start small.
  const newFiles = new Set();
  try {
    const gitStatus = execFileSync('git', ['status', '--porcelain'], {
      cwd: workingDir, encoding: 'utf8', timeout: TASK_TIMEOUTS.GIT_STATUS, stdio: 'pipe', windowsHide: true
    });
    for (const line of gitStatus.split('\n')) {
      if (!line.trim()) continue;
      const status = line.slice(0, 2);
      const filePath = line.slice(3).trim();
      // 'A ' = staged new file, '??' = untracked new file
      if (status.startsWith('A') || status === '??') {
        newFiles.add(filePath);
      }
    }
  } catch (e) {
    logger.debug(`[Safeguard] Git status for new-file detection failed: ${e.message}`);
  }

  // 1. File quality checks
  if (normalizedModifiedFiles.length > 0) {
    for (const file of normalizedModifiedFiles) {
      const fullPath = path.isAbsolute(file) ? file : path.join(workingDir, file);
      const isNewFile = newFiles.has(file) || newFiles.has(file.replace(/\\/g, '/'));
      const result = checkFileQuality(fullPath, { isNewFile });
      details.fileQuality.checked++;
      if (!result.valid) {
        const fileIssues = result.issues.map(i => `${path.basename(file)}: ${i}`);
        details.fileQuality.issues.push(...fileIssues);
        allIssues.push(...fileIssues);
      }
    }
  }

  // 2. Placeholder artifact detection for files that never graduated past stub markers.
  const placeholderArtifactResult = findPlaceholderArtifacts(workingDir, normalizedModifiedFiles);
  details.placeholderArtifacts.checked = true;
  if (!placeholderArtifactResult.valid) {
    details.placeholderArtifacts.issues = placeholderArtifactResult.issues;
    details.placeholderArtifacts.artifacts = placeholderArtifactResult.artifacts;
    allIssues.push(...placeholderArtifactResult.issues);
  }

  // 3. Placeholder-only output detection. Gate on no validated file changes to avoid
  // false positives when a task discusses placeholder markers while still producing code.
  const shouldCheckOutputMarkers = options.checkOutputMarkers === true &&
    normalizedModifiedFiles.length === 0 &&
    typeof options.outputText === 'string' &&
    options.outputText.trim().length > 0;
  details.outputMarkers.checked = shouldCheckOutputMarkers;
  if (shouldCheckOutputMarkers) {
    const outputMarkerResult = findPlaceholderOutputMarkers(options.outputText);
    if (!outputMarkerResult.valid) {
      details.outputMarkers.issues = outputMarkerResult.issues;
      details.outputMarkers.markers = outputMarkerResult.markers;
      allIssues.push(...outputMarkerResult.issues);
    }
  }

  // 4. Duplicate file check
  const dupResult = checkDuplicateFiles(workingDir, normalizedModifiedFiles);
  details.duplicates.checked = true;
  if (!dupResult.valid) {
    details.duplicates.issues = dupResult.issues;
    allIssues.push(...dupResult.issues);
  }

  // 5. Syntax validation
  const syntaxResult = checkSyntax(workingDir, normalizedModifiedFiles);
  details.syntax.checked = normalizedModifiedFiles.length;
  if (!syntaxResult.valid) {
    details.syntax.issues = syntaxResult.issues;
    allIssues.push(...syntaxResult.issues);
  }

  if (allIssues.length > 0) {
    logger.info(`[Safeguard] Found ${allIssues.length} issue(s):`);
    allIssues.forEach(i => logger.info(`  - ${i}`));
  } else {
    logger.info(`[Safeguard] All checks passed for task ${taskId}`);
  }

  return {
    passed: allIssues.length === 0,
    issues: allIssues,
    details
  };
}

/**
 * Extract file paths from compiler/build error output.
 * Supports C# (dotnet), TypeScript (tsc), Rust (rustc), Go, Java (javac/maven), and generic patterns.
 * Returns deduplicated relative file paths found in error lines.
 * @param {string} output - Combined stdout+stderr from build command
 * @param {string} workingDir - Working directory (used to strip absolute prefixes)
 * @returns {string[]} Array of relative file paths referenced in errors
 */
function extractBuildErrorFiles(output, workingDir) {
  if (!output) return [];

  const filePaths = new Set();
  const lines = output.split('\n');

  // Normalize workingDir for stripping absolute paths
  const normWorkDir = workingDir.replace(/\\/g, '/').replace(/\/?$/, '/');

  for (const line of lines) {
    const lower = line.toLowerCase();
    if (!lower.includes('error') && !lower.includes('warning')) continue;

    let match;

    // C# / MSBuild: "path\to\File.cs(10,5): error CS0200: ..."
    match = line.match(/^\s*(.+?\.[a-zA-Z]{1,5})\(\d+,\d+\)\s*:\s*(?:error|warning)\s/i);
    if (match) { filePaths.add(match[1].trim()); continue; }

    // TypeScript (tsc): "src/file.ts(10,5): error TS2339: ..."
    // Also: "src/file.ts:10:5 - error TS2339: ..."
    match = line.match(/^\s*(.+?\.tsx?)[:(]\d+[,:]\d+/);
    if (match) { filePaths.add(match[1].trim()); continue; }

    // Rust (rustc): " --> src/main.rs:10:5"
    match = line.match(/\s*-->\s*(.+?\.[a-zA-Z]{1,5}):\d+:\d+/);
    if (match) { filePaths.add(match[1].trim()); continue; }

    // Go: "file.go:10:5: ..."
    match = line.match(/^\s*(.+?\.go):(\d+):(\d+):/);
    if (match) { filePaths.add(match[1].trim()); continue; }

    // Java (javac/maven): "[ERROR] /path/to/File.java:[10,5] error: ..."
    match = line.match(/^\s*(?:\[ERROR\]\s*)?(.+?\.java):\[?\d+[,:]?\d*\]?/i);
    if (match) { filePaths.add(match[1].trim()); continue; }
  }

  // Strip absolute working directory prefix to get relative paths
  const result = [];
  for (const fp of filePaths) {
    let rel = fp.replace(/\\/g, '/');
    const normRel = rel.toLowerCase();
    const normWorkDirLower = normWorkDir.toLowerCase();
    if (normRel.startsWith(normWorkDirLower)) {
      rel = rel.substring(normWorkDir.length);
    }
    if (/^[A-Za-z]:/.test(rel)) {
      const withoutDrive = rel.replace(/^[A-Za-z]:/, '');
      const wdWithoutDrive = normWorkDir.replace(/^[A-Za-z]:/, '');
      if (withoutDrive.toLowerCase().startsWith(wdWithoutDrive.toLowerCase())) {
        rel = withoutDrive.substring(wdWithoutDrive.length);
      }
    }
    result.push(rel);
  }

  return [...new Set(result)];
}

/**
 * Run build verification after task completion.
 * Auto-detects build commands (npm, cargo, go, maven, gradle, dotnet) or uses
 * project-specific configuration. Handles WSL/Windows cross-environment execution.
 * Saves build results to the database.
 * @param {string} taskId - The task ID
 * @param {Object} task - The task object
 * @param {string} workingDir - Working directory
 * @param {string[]} [taskModifiedFiles] - Files modified by this task (for scoped error checking)
 * @returns {Object} Build result with success, output, error, skipped, reason fields
 */
// Build verification extracted to ./build-verification.js
function runBuildVerification(taskId, task, workingDir, taskModifiedFiles) {
  return buildVerification.runBuildVerification(taskId, task, workingDir, taskModifiedFiles);
}

/**
 * Run test verification after task completion.
 * Auto-detects test commands (npm, cargo, go, maven, gradle, pytest, dotnet)
 * or uses project-specific configuration. Handles WSL/Windows cross-environment execution.
 * @param {string} taskId - The task ID
 * @param {Object} task - The task object
 * @param {string} workingDir - Working directory
 * @returns {Object} Test result with success, output, error, skipped fields
 */
function runTestVerification(taskId, task, workingDir) {
  const project = task.project || db.getProjectFromPath(workingDir);
  if (!project) {
    return { success: true, output: '', error: '', skipped: true, reason: 'no_project' };
  }

  const projectConfig = db.getProjectConfig(project);
  if (!projectConfig || !projectConfig.test_verification_enabled) {
    return { success: true, output: '', error: '', skipped: true, reason: 'disabled' };
  }

  // Determine test command - use project-specific or auto-detect
  let testCommand = projectConfig.test_command;
  if (!testCommand) {
    // Auto-detect based on project files
    if (fs.existsSync(path.join(workingDir, 'package.json'))) {
      testCommand = 'npm test';
    } else if (fs.existsSync(path.join(workingDir, 'Cargo.toml'))) {
      testCommand = 'cargo test';
    } else if (fs.existsSync(path.join(workingDir, 'go.mod'))) {
      testCommand = 'go test ./...';
    } else if (fs.existsSync(path.join(workingDir, 'pom.xml'))) {
      testCommand = 'mvn test -q';
    } else if (fs.existsSync(path.join(workingDir, 'build.gradle'))) {
      testCommand = 'gradle test -q';
    } else if (fs.existsSync(path.join(workingDir, 'pytest.ini')) || fs.existsSync(path.join(workingDir, 'pyproject.toml'))) {
      testCommand = 'pytest';
    } else {
      // Check for .NET projects
      let dirEntries = [];
      try { dirEntries = fs.readdirSync(workingDir); } catch { /* skip */ }
      const csprojFiles = dirEntries.filter(f => f.endsWith('.csproj') || f.endsWith('.sln'));
      if (csprojFiles.length > 0) {
        testCommand = 'dotnet test --no-build --verbosity quiet';
      }
    }
  }

  if (!testCommand) {
    return { success: true, output: '', error: '', skipped: true, reason: 'no_test_command' };
  }

  const timeout = (projectConfig.test_timeout || 300) * 1000; // Default 5 min for tests

  logger.info(`[Test Verification] Task ${taskId}: Running "${testCommand}" in ${workingDir}`);

  try {
    // Parse command into executable and args (supports quoted segments)
    const parsed = parseCommand(testCommand);
    let executable = parsed.executable;
    const args = parsed.args;

    // Handle WSL environment - use Windows executable paths for common tools
    const isWSL = process.platform === 'linux' && workingDir.startsWith('/mnt/');
    if (isWSL) {
      if (executable === 'dotnet') {
        executable = '/mnt/c/Program Files/dotnet/dotnet.exe';
      } else if (executable === 'npm') {
        const winNpm = '/mnt/c/Program Files/nodejs/npm.cmd';
        if (fs.existsSync(winNpm)) {
          executable = winNpm;
        }
      }
    }

    let spawnResult;

    if (isWSL && executable.endsWith('.exe')) {
      spawnResult = spawnSync(executable, args, {
        cwd: workingDir,
        encoding: 'utf8',
        timeout,
        maxBuffer: 10 * 1024 * 1024,
        shell: false,
        windowsHide: true
      });
    } else if (isWSL && (executable.endsWith('.cmd') || executable.endsWith('.bat'))) {
      const winPath = workingDir.replace(/^\/mnt\/([a-z])/, '$1:').replace(/\//g, '\\');
      spawnResult = spawnSync('cmd.exe', ['/c', executable, ...args], {
        cwd: workingDir,
        encoding: 'utf8',
        timeout,
        maxBuffer: 10 * 1024 * 1024,
        shell: false,
        windowsHide: true,
        env: { ...process.env, CD: winPath }
      });
    } else {
      spawnResult = spawnSync(executable, args, {
        cwd: workingDir,
        encoding: 'utf8',
        timeout,
        maxBuffer: 10 * 1024 * 1024,
        shell: false,
        windowsHide: true
      });
    }

    if (spawnResult.error) {
      throw spawnResult.error;
    }
    if (spawnResult.status !== 0) {
      const err = new Error('Tests failed');
      err.stdout = spawnResult.stdout;
      err.stderr = spawnResult.stderr;
      throw err;
    }

    const result = spawnResult.stdout;

    logger.info(`[Test Verification] Task ${taskId}: Tests PASSED`);
    return { success: true, output: result, error: '' };
  } catch (err) {
    const output = err.stdout || '';
    const error = err.stderr || err.message || 'Tests failed';

    logger.info(`[Test Verification] Task ${taskId}: Tests FAILED`);
    logger.info(`[Test Verification] Error: ${error.substring(0, 500)}`);

    return { success: false, output, error };
  }
}

/**
 * Run style check verification after task completion.
 * Auto-detects linting commands (dotnet format, npm run lint, ruff)
 * or uses project-specific configuration. Handles WSL/Windows cross-environment execution.
 * @param {string} taskId - The task ID
 * @param {Object} task - The task object
 * @param {string} workingDir - Working directory
 * @returns {Object} Style check result with success, output, error, skipped, durationSeconds fields
 */
function runStyleCheck(taskId, task, workingDir) {
  const project = task.project || db.getProjectFromPath(workingDir);
  if (!project) {
    return { success: true, output: '', error: '', skipped: true, reason: 'no_project' };
  }

  const projectConfig = db.getProjectConfig(project);
  if (!projectConfig || !projectConfig.style_check_enabled) {
    return { success: true, output: '', error: '', skipped: true, reason: 'disabled' };
  }

  // Determine style check command - use project-specific or auto-detect
  let styleCommand = projectConfig.style_check_command;
  if (!styleCommand) {
    // Auto-detect based on project files
    let styleDirEntries = [];
    try { styleDirEntries = fs.readdirSync(workingDir); } catch { /* skip */ }
    const csprojFiles = styleDirEntries.filter(f => f.endsWith('.csproj') || f.endsWith('.sln'));
    if (csprojFiles.length > 0) {
      styleCommand = 'dotnet format --verify-no-changes --verbosity quiet';
    } else if (fs.existsSync(path.join(workingDir, 'package.json'))) {
      styleCommand = 'npm run lint --silent';
    } else if (fs.existsSync(path.join(workingDir, 'pyproject.toml'))) {
      styleCommand = 'ruff check .';
    }
  }

  if (!styleCommand) {
    return { success: true, output: '', error: '', skipped: true, reason: 'no_style_command' };
  }

  const timeout = (projectConfig.style_check_timeout || 60) * 1000;
  const startTime = Date.now();

  logger.info(`[Style Check] Task ${taskId}: Running "${styleCommand}" in ${workingDir}`);

  try {
    // Parse command into executable and args (supports quoted segments)
    const parsed = parseCommand(styleCommand);
    let executable = parsed.executable;
    const args = parsed.args;

    // Handle WSL environment
    const isWSL = process.platform === 'linux' && workingDir.startsWith('/mnt/');
    if (isWSL && executable === 'dotnet') {
      executable = '/mnt/c/Program Files/dotnet/dotnet.exe';
    }

    let spawnResult;

    if (isWSL && executable.endsWith('.exe')) {
      spawnResult = spawnSync(executable, args, {
        cwd: workingDir,
        encoding: 'utf8',
        timeout,
        maxBuffer: 10 * 1024 * 1024,
        shell: false,
        windowsHide: true
      });
    } else {
      spawnResult = spawnSync(executable, args, {
        cwd: workingDir,
        encoding: 'utf8',
        timeout,
        maxBuffer: 10 * 1024 * 1024,
        shell: false,
        windowsHide: true
      });
    }

    const endTime = Date.now();
    const durationSeconds = (endTime - startTime) / 1000;

    if (spawnResult.error) {
      throw spawnResult.error;
    }
    if (spawnResult.status !== 0) {
      const err = new Error('Style check failed');
      err.stdout = spawnResult.stdout;
      err.stderr = spawnResult.stderr;
      throw err;
    }

    logger.info(`[Style Check] Task ${taskId}: Style check PASSED (${durationSeconds.toFixed(1)}s)`);
    return { success: true, output: spawnResult.stdout || '', error: '', durationSeconds };
  } catch (err) {
    const output = err.stdout || '';
    const error = err.stderr || err.message || 'Style check failed';

    logger.info(`[Style Check] Task ${taskId}: Style check FAILED`);
    logger.info(`[Style Check] Issues: ${error.substring(0, 500)}`);

    return { success: false, output, error, warnings: true };
  }
}

/**
 * Rollback task changes by reverting only files recorded for the task when the
 * workspace is dirty, or reverting the last auto-generated commit when the repo is clean.
 * @param {string} taskId - The task ID
 * @param {string} workingDir - Working directory
 * @returns {boolean} True if rollback was performed successfully
 */
function rollbackTaskChanges(taskId, workingDir) {
  if (!workingDir || !fs.existsSync(workingDir)) {
    return false;
  }

  try {
    // Check if there are uncommitted changes to rollback
    const status = execFileSync('git', ['status', '--porcelain'], {
      cwd: workingDir,
      encoding: 'utf8',
      windowsHide: true,
    });

    if (status.trim()) {
      logger.info(`[Rollback] Task ${taskId}: Restoring recorded task changes only`);
      const result = scopedRollback(taskId, workingDir, 'Rollback');
      return result.reverted.length > 0;
    }

    // Check if last commit was made by a TORQUE provider
    const lastCommitMessage = execFileSync('git', ['log', '-1', '--format=%s'], {
      cwd: workingDir,
      encoding: 'utf8',
      timeout: TASK_TIMEOUTS.GIT_STATUS,
      windowsHide: true,
    }).trim();

    const isTorqueCommit = lastCommitMessage.includes('[Torque');

    if (isTorqueCommit) {
      logger.info(`[Rollback] Task ${taskId}: Reverting last auto-generated commit`);
      execFileSync('git', ['revert', '--no-commit', 'HEAD'], { cwd: workingDir, encoding: 'utf8', timeout: TASK_TIMEOUTS.GIT_COMMIT, windowsHide: true });
      execFileSync('git', ['commit', '-m', `Revert: Build verification failed for task ${taskId}`], {
        cwd: workingDir,
        encoding: 'utf8',
        timeout: TASK_TIMEOUTS.GIT_COMMIT,
        windowsHide: true,
      });
      return true;
    }

    return false;
  } catch (err) {
    logger.info(`[Rollback] Task ${taskId}: Failed - ${err.message}`);
    return false;
  }
}

module.exports = {
  init,
  cleanupJunkFiles,
  getFileChangesForValidation,
  checkFileQuality,
  findPlaceholderArtifacts,
  checkDuplicateFiles,
  checkSyntax,
  runLLMSafeguards,
  extractBuildErrorFiles,
  runBuildVerification,
  runTestVerification,
  runStyleCheck,
  revertScopedFiles,
  scopedRollback,
  rollbackTaskChanges,
  parseCommand,
};
