'use strict';

const fs = require('fs');
const fsPromises = require('node:fs/promises');
const path = require('path');
const { spawnSync } = require('child_process');

const { handleSmartSubmitTask } = require('../handlers/integration/routing');
const { handleAwaitTask } = require('../handlers/workflow/await');

const STUDY_DIR = path.join('docs', 'architecture');
const STATE_FILE = path.join(STUDY_DIR, 'study-state.json');
const MODULE_INDEX_FILE = path.join(STUDY_DIR, 'module-index.json');
const SUMMARY_FILE = path.join(STUDY_DIR, 'SUMMARY.md');
const GENERATED_STUDY_FILES = new Set([
  'docs/architecture/module-index.json',
  'docs/architecture/study-state.json',
]);
const ALLOWED_EXTENSIONS = new Set(['.js', '.ts', '.json']);
const MAX_BATCH_SIZE = 5;

function createNoopLogger() {
  return {
    debug() {},
    info() {},
    warn() {},
    error() {},
  };
}

function createCodebaseStudy({ db: _db, taskCore, logger } = {}) {
  if (!taskCore || typeof taskCore.listTasks !== 'function') {
    throw new Error('createCodebaseStudy requires taskCore.listTasks(options)');
  }

  const studyLogger = logger || createNoopLogger();

  function resolveWorkingDirectory(workingDirectory) {
    if (typeof workingDirectory !== 'string' || !workingDirectory.trim()) {
      throw new Error('workingDirectory must be a non-empty string');
    }

    const resolved = path.resolve(workingDirectory.trim());
    if (!fs.existsSync(resolved)) {
      throw new Error(`Working directory not found: ${resolved}`);
    }

    return resolved;
  }

  function toRepoPath(filePath) {
    return String(filePath || '').trim().replace(/\\/g, '/');
  }

  function uniquePaths(values) {
    const seen = new Set();
    const output = [];
    for (const value of Array.isArray(values) ? values : []) {
      const normalized = toRepoPath(value);
      if (!normalized || seen.has(normalized)) {
        continue;
      }
      seen.add(normalized);
      output.push(normalized);
    }
    return output;
  }

  function isStudyCandidate(filePath) {
    const normalized = toRepoPath(filePath);
    if (!normalized) {
      return false;
    }

    if (GENERATED_STUDY_FILES.has(normalized)) {
      return false;
    }

    return ALLOWED_EXTENSIONS.has(path.extname(normalized).toLowerCase());
  }

  function filterStudyCandidates(values) {
    return uniquePaths(values).filter(isStudyCandidate);
  }

  function splitGitOutput(output) {
    return String(output || '')
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(Boolean);
  }

  function getPaths(workingDirectory) {
    return {
      studyDir: path.join(workingDirectory, STUDY_DIR),
      statePath: path.join(workingDirectory, STATE_FILE),
      moduleIndexPath: path.join(workingDirectory, MODULE_INDEX_FILE),
      summaryPath: path.join(workingDirectory, SUMMARY_FILE),
    };
  }

  function buildInitialState() {
    return {
      run_count: 0,
      last_sha: null,
      last_task_id: null,
      last_batch: [],
      last_run_at: null,
      last_completed_at: null,
      last_result: null,
      last_error: null,
      tracked_files: [],
      pending_files: [],
      file_counts: {
        tracked: 0,
        pending: 0,
        up_to_date: 0,
      },
    };
  }

  function normalizeState(rawState) {
    const initial = buildInitialState();
    const source = rawState && typeof rawState === 'object' && !Array.isArray(rawState)
      ? rawState
      : {};
    const trackedFiles = uniquePaths(source.tracked_files);
    const pendingFiles = uniquePaths(source.pending_files).filter(file => trackedFiles.includes(file));
    const fileCounts = {
      tracked: trackedFiles.length,
      pending: pendingFiles.length,
      up_to_date: Math.max(0, trackedFiles.length - pendingFiles.length),
    };

    return {
      ...initial,
      ...source,
      last_sha: typeof source.last_sha === 'string' && source.last_sha.trim() ? source.last_sha.trim() : null,
      last_task_id: typeof source.last_task_id === 'string' && source.last_task_id.trim() ? source.last_task_id.trim() : null,
      last_batch: uniquePaths(source.last_batch),
      tracked_files: trackedFiles,
      pending_files: pendingFiles,
      file_counts: fileCounts,
    };
  }

  async function ensureStudyDocs(workingDirectory) {
    const paths = getPaths(workingDirectory);
    await fsPromises.mkdir(paths.studyDir, { recursive: true });

    if (!fs.existsSync(paths.summaryPath)) {
      await fsPromises.writeFile(paths.summaryPath, 'auto-generated by study loop, no runs yet\n', 'utf8');
    }
    if (!fs.existsSync(paths.moduleIndexPath)) {
      await fsPromises.writeFile(paths.moduleIndexPath, '{"modules":[],"last_updated":null}\n', 'utf8');
    }
    if (!fs.existsSync(paths.statePath)) {
      await fsPromises.writeFile(paths.statePath, '{}\n', 'utf8');
    }

    return paths;
  }

  async function readStudyState(workingDirectory) {
    const paths = await ensureStudyDocs(workingDirectory);
    const raw = await fsPromises.readFile(paths.statePath, 'utf8');
    const parsed = raw.trim() ? JSON.parse(raw) : {};
    return { paths, state: normalizeState(parsed) };
  }

  async function writeStudyState(workingDirectory, state) {
    const paths = await ensureStudyDocs(workingDirectory);
    const normalized = normalizeState(state);
    await fsPromises.writeFile(paths.statePath, `${JSON.stringify(normalized, null, 2)}\n`, 'utf8');
    return { paths, state: normalized };
  }

  function runGitCommand(workingDirectory, args) {
    const result = spawnSync('git', args, {
      cwd: workingDirectory,
      encoding: 'utf8',
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    if (result.error) {
      throw result.error;
    }
    if (result.status !== 0) {
      const stderr = (result.stderr || '').trim();
      throw new Error(stderr || `git ${args.join(' ')} failed with exit code ${result.status}`);
    }

    return (result.stdout || '').trim();
  }

  function safeHeadSha(workingDirectory) {
    try {
      return runGitCommand(workingDirectory, ['rev-parse', 'HEAD']);
    } catch (error) {
      studyLogger.warn('[codebase-study] unable to resolve HEAD sha: ' + (error.message || error));
      return null;
    }
  }

  function loadDeltaFiles(workingDirectory, lastSha) {
    if (!lastSha) {
      return filterStudyCandidates(splitGitOutput(runGitCommand(workingDirectory, ['ls-files'])));
    }

    try {
      return filterStudyCandidates(splitGitOutput(runGitCommand(workingDirectory, ['diff', '--name-only', lastSha, 'HEAD'])));
    } catch (error) {
      studyLogger.warn('[codebase-study] diff failed, falling back to ls-files: ' + (error.message || error));
      return filterStudyCandidates(splitGitOutput(runGitCommand(workingDirectory, ['ls-files'])));
    }
  }

  function mergeUnique(baseValues, newValues) {
    return uniquePaths([...(baseValues || []), ...(newValues || [])]);
  }

  function buildCounts(trackedFiles, pendingFiles) {
    return {
      tracked: trackedFiles.length,
      pending: pendingFiles.length,
      up_to_date: Math.max(0, trackedFiles.length - pendingFiles.length),
    };
  }

  function extractText(result) {
    return Array.isArray(result?.content)
      ? result.content.map(part => (part && typeof part.text === 'string' ? part.text : '')).join('\n').trim()
      : '';
  }

  function normalizeTaskStatus(value) {
    if (!value || typeof value !== 'string') {
      return null;
    }
    return value.trim().toLowerCase();
  }

  function isTerminalTaskStatus(status) {
    switch (status) {
      case 'completed':
      case 'failed':
      case 'cancelled':
      case 'skipped':
        return true;
      default:
        return false;
    }
  }

  function buildStudyPrompt(batchFiles) {
    const formattedFiles = batchFiles.map(file => `- ${file}`).join('\n');
    return [
      'Update the TORQUE codebase study docs for this repository.',
      '',
      'Read exactly these source files:',
      formattedFiles,
      '',
      'Update only these files:',
      '- docs/architecture/module-index.json',
      '- docs/architecture/SUMMARY.md',
      '',
      'Requirements:',
      '- Preserve existing module-index entries for files outside this batch.',
      '- Upsert one module entry per studied file using this shape:',
      '  { "file": "...", "purpose": "...", "exports": ["..."], "deps": ["..."] }',
      '- Keep module-index.json valid JSON with top-level keys "modules" and "last_updated".',
      '- Deduplicate module entries by the "file" field.',
      '- Keep SUMMARY.md concise and cumulative for the whole project.',
      '- Do not edit docs/architecture/study-state.json.',
      '- If markdown needs a code block, use indented code blocks instead of fenced blocks.',
    ].join('\n');
  }

  async function submitStudyTask(workingDirectory, batchFiles) {
    const projectName = require('path').basename(workingDirectory);
    const result = await handleSmartSubmitTask({
      task: buildStudyPrompt(batchFiles),
      working_directory: workingDirectory,
      project: projectName,
      version_intent: 'internal',
      provider: 'codex',
      timeout_minutes: 30,
      tags: ['codebase-study', 'auto-generated'],
      files: [
        ...batchFiles,
        MODULE_INDEX_FILE,
        SUMMARY_FILE,
      ],
    });

    if (result?.isError) {
      throw new Error(extractText(result) || 'smart_submit_task failed');
    }
    if (!result?.task_id) {
      throw new Error('smart_submit_task did not return a task_id');
    }

    return result.task_id;
  }

  async function awaitStudyTask(taskId, workingDirectory, runNumber) {
    return handleAwaitTask({
      task_id: taskId,
      timeout_minutes: 30,
      working_directory: workingDirectory,
      auto_commit: true,
      commit_message: `docs: codebase study run #${runNumber}`,
    });
  }

  function buildStatusPayload(workingDirectory, state, currentSha) {
    return {
      working_directory: workingDirectory,
      last_sha: state.last_sha,
      current_sha: currentSha,
      run_count: state.run_count || 0,
      last_task_id: state.last_task_id || null,
      last_batch: uniquePaths(state.last_batch),
      last_run_at: state.last_run_at || null,
      last_completed_at: state.last_completed_at || null,
      last_result: state.last_result || null,
      last_error: state.last_error || null,
      tracked_count: state.file_counts?.tracked ?? state.tracked_files.length,
      pending_count: state.file_counts?.pending ?? state.pending_files.length,
      up_to_date_count: state.file_counts?.up_to_date ?? Math.max(0, state.tracked_files.length - state.pending_files.length),
      pending_files: uniquePaths(state.pending_files),
    };
  }

  async function runStudyCycle(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const runningTasks = taskCore.listTasks({ status: 'running', limit: 1000 });
    if (runningTasks.length > 0) {
      return {
        skipped: true,
        reason: 'queue_active',
        running_task_count: runningTasks.length,
      };
    }

    const { state } = await readStudyState(resolvedWorkingDirectory);
    const currentSha = safeHeadSha(resolvedWorkingDirectory);
    const deltaFiles = loadDeltaFiles(resolvedWorkingDirectory, state.last_sha);

    const trackedFiles = mergeUnique(
      state.tracked_files,
      state.last_sha ? deltaFiles : mergeUnique(state.pending_files, deltaFiles)
    );
    const pendingFiles = state.last_sha
      ? mergeUnique(state.pending_files, deltaFiles)
      : mergeUnique(state.pending_files, deltaFiles);

    if (pendingFiles.length === 0) {
      const nextState = normalizeState({
        ...state,
        last_sha: currentSha,
        last_run_at: new Date().toISOString(),
        last_result: 'up_to_date',
        last_error: null,
        tracked_files: trackedFiles,
        pending_files: [],
        file_counts: buildCounts(trackedFiles, []),
      });
      await writeStudyState(resolvedWorkingDirectory, nextState);
      return {
        skipped: true,
        reason: 'up_to_date',
        ...buildStatusPayload(resolvedWorkingDirectory, nextState, currentSha),
      };
    }

    const batchFiles = pendingFiles.slice(0, MAX_BATCH_SIZE);
    const runNumber = (state.run_count || 0) + 1;
    const taskId = await submitStudyTask(resolvedWorkingDirectory, batchFiles);
    const awaitResult = await awaitStudyTask(taskId, resolvedWorkingDirectory, runNumber);
    const task = typeof taskCore.getTask === 'function' ? taskCore.getTask(taskId) : null;
    const taskStatus = normalizeTaskStatus(task?.status) || (awaitResult?.isError ? 'failed' : 'completed');
    const terminal = isTerminalTaskStatus(taskStatus);
    const completed = taskStatus === 'completed';
    const running = !terminal;
    const remainingPending = (terminal && completed)
      ? pendingFiles.filter(file => !batchFiles.includes(file))
      : pendingFiles;

    const nowIso = new Date().toISOString();
    const lastError = running
      ? (state.last_error || null)
      : (completed ? null : (extractText(awaitResult) || `study task ended with status ${taskStatus}`));

    const nextState = normalizeState({
      ...state,
      run_count: runNumber,
      last_sha: running ? state.last_sha : currentSha,
      last_task_id: taskId,
      last_batch: batchFiles,
      last_run_at: nowIso,
      last_completed_at: completed ? nowIso : state.last_completed_at,
      last_result: taskStatus,
      last_error: lastError,
      tracked_files: trackedFiles,
      pending_files: remainingPending,
      file_counts: buildCounts(trackedFiles, remainingPending),
    });
    await writeStudyState(resolvedWorkingDirectory, nextState);

    return {
      skipped: false,
      task_id: taskId,
      task_status: taskStatus,
      batch_files: batchFiles,
      await_result: awaitResult,
      ...buildStatusPayload(resolvedWorkingDirectory, nextState, currentSha),
    };
  }

  async function getStudyStatus(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const { state } = await readStudyState(resolvedWorkingDirectory);
    return buildStatusPayload(resolvedWorkingDirectory, state, safeHeadSha(resolvedWorkingDirectory));
  }

  async function resetStudy(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const { paths, state } = await writeStudyState(resolvedWorkingDirectory, buildInitialState());
    return {
      reset: true,
      working_directory: resolvedWorkingDirectory,
      state_path: paths.statePath,
      ...buildStatusPayload(resolvedWorkingDirectory, state, safeHeadSha(resolvedWorkingDirectory)),
    };
  }

  return {
    runStudyCycle,
    getStudyStatus,
    resetStudy,
  };
}

module.exports = {
  createCodebaseStudy,
};
