'use strict';

const fs = require('fs');
const fsPromises = require('node:fs/promises');
const path = require('path');

const { STUDY_PROFILE_OVERRIDE_FILE, resolveStudyProfile, getStudyProfileOverridePath, readStudyProfileOverride, createStudyProfileOverrideTemplate, detectStudyProfileSignals } = require('./codebase-study-profiles');
const { STUDY_EVALUATION_FILE, STUDY_BENCHMARK_FILE, DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL, DEFAULT_PROPOSAL_MIN_SCORE, normalizeStudyThresholdLevel, evaluateStudyArtifacts, benchmarkStudyArtifacts, buildStudyBootstrapPlan } = require('./codebase-study-engine');
const symbolIndexer = require('../utils/symbol-indexer');
const { createScanner } = require('./codebase-study/scan');
const { createEvaluator } = require('./codebase-study/evaluate');
const { createProposer } = require('./codebase-study/proposal');
const { createParsers } = require('./codebase-study/parsers');
const { createProfileManager } = require('./codebase-study/profile');
const { createFlows } = require('./codebase-study/flows');
const { createHotspotsAnalyzer } = require('./codebase-study/hotspots');
const { createSummary } = require('./codebase-study/summary');
const { createSubsystems } = require('./codebase-study/subsystems');
const { createFlowDefinitions } = require('./codebase-study/flow-definitions');
const { createTestsIndex } = require('./codebase-study/tests-index');
const { createProfileSerializer } = require('./codebase-study/profile-serializer');
const { createExpertise } = require('./codebase-study/expertise');
const { createProposals } = require('./codebase-study/proposals');
const { createOrchestratorHelpers } = require('./codebase-study/orchestrator-helpers');
const { createArtifactFiles } = require('./codebase-study/artifact-files');

const STUDY_DIR = path.join('docs', 'architecture');
const STATE_FILE = path.join(STUDY_DIR, 'study-state.json');
const MODULE_INDEX_FILE = path.join(STUDY_DIR, 'module-index.json');
const KNOWLEDGE_PACK_FILE = path.join(STUDY_DIR, 'knowledge-pack.json');
const STUDY_DELTA_FILE = path.join(STUDY_DIR, 'study-delta.json');
const STUDY_BENCHMARK_FILE_LOCAL = path.join(STUDY_DIR, 'study-benchmark.json');
const SUMMARY_FILE = path.join(STUDY_DIR, 'SUMMARY.md');
const STUDY_OUTPUT_FILES = [MODULE_INDEX_FILE, KNOWLEDGE_PACK_FILE, STUDY_DELTA_FILE, STUDY_EVALUATION_FILE, STUDY_BENCHMARK_FILE_LOCAL, SUMMARY_FILE, STATE_FILE].map(filePath => filePath.replace(/\\/g, '/'));
const SUMMARY_PLACEHOLDER = 'auto-generated by study loop, no runs yet\n';
const GENERATED_STUDY_FILES = new Set(['docs/architecture/module-index.json', 'docs/architecture/study-state.json', 'docs/architecture/knowledge-pack.json', 'docs/architecture/study-delta.json', 'docs/architecture/study-evaluation.json', 'docs/architecture/study-benchmark.json', 'docs/architecture/SUMMARY.md']);
const ALLOWED_EXTENSIONS = new Set(['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs', '.json', '.py', '.cs']);
const JS_LIKE_EXTENSIONS = new Set(['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs']);
const SYMBOL_INDEX_EXTENSIONS = new Set([...JS_LIKE_EXTENSIONS, '.py', '.cs']);
const LOCAL_ONLY_STRATEGY = 'local-deterministic';
const DEFAULT_LOCAL_BATCH_SIZE = 100;
const DEFAULT_MANUAL_RUN_BATCH_COUNT = 5;
const MAX_RUN_BATCH_COUNT = 25;
const SUMMARY_SUBSYSTEM_LIMIT = 6;
const SUMMARY_FLOW_LIMIT = 5;
const HOTSPOT_LIMIT = 6;
const RELATIONSHIP_LIMIT = 8;
const NAVIGATION_HINT_LIMIT = 6;
const SUMMARY_INVARIANT_LIMIT = 5;
const SUMMARY_FAILURE_MODE_LIMIT = 5;
const SUMMARY_PLAYBOOK_LIMIT = 5;
const TRACE_LIMIT = 5;
const TEST_MATRIX_LIMIT = 6;
const SIGNIFICANCE_REASON_LIMIT = 4;
const KNOWLEDGE_PACK_VERSION = 3;
const STUDY_DELTA_VERSION = 1;
const ROOT_DOC_FILES = new Set(['README.md', 'CLAUDE.md', 'CONTRIBUTING.md']);
const LOW_SIGNAL_EXPORT_NAMES = new Set(['default', 'test', 'tests', 'value', 'values', 'data', 'result', 'results', 'foo', 'bar', 'baz']);
const LOW_SIGNAL_HOTSPOT_BASENAMES = new Set(['logger.js', 'constants.js']);
const TEST_FILE_PATTERN = /(?:^|\/)(?:tests?|__tests__)\/|(?:\.test|\.spec|\.e2e|\.integration)\.[^.]+$/i;
const TEST_SUFFIX_PATTERN = /(?:\.test|\.spec|\.e2e|\.integration)$/i;
const TOKEN_STOP_WORDS = new Set(['js', 'ts', 'jsx', 'tsx', 'index', 'main', 'test', 'tests', 'spec', 'e2e', 'integration', 'server', 'src', 'lib', 'app']);
const MAX_PROPOSAL_LIMIT = 5;
const GENERIC_FLOW_IDS = Object.freeze({ ENTRY_RUNTIME: 'generic-entry-runtime', CONFIG_CONTRACTS: 'generic-config-contracts', CHANGE_VALIDATION: 'generic-change-validation' });

function createNoopLogger() {
  return { debug() {}, info() {}, warn() {}, error() {} };
}

function createCodebaseStudy({ db: _db, taskCore, logger, batchSize } = {}) {
  if (!taskCore || typeof taskCore.listTasks !== 'function') {
    throw new Error('createCodebaseStudy requires taskCore.listTasks(options)');
  }

  const studyLogger = logger || createNoopLogger();
  const effectiveBatchSize = Number.isInteger(batchSize) && batchSize > 0
    ? batchSize
    : DEFAULT_LOCAL_BATCH_SIZE;
  const scanner = createScanner({ symbolIndexer, logger: studyLogger });
  const evaluator = createEvaluator({ db: _db, logger: studyLogger });
  const proposer = createProposer({ taskCore, logger: studyLogger, db: _db });
  const parsers = createParsers({ logger: studyLogger });
  const profileManager = createProfileManager({ db: _db, logger: studyLogger });
  const buildModuleEntryMap = parsers.buildModuleEntryMap;
  const buildModuleExportLookup = parsers.buildModuleExportLookup;
  const buildInterfaceImplementationMap = parsers.buildInterfaceImplementationMap;
  const buildServiceRegistrationLookup = parsers.buildServiceRegistrationLookup;
  const extractCSharpExplicitExports = parsers.extractCSharpExplicitExports;
  const extractCSharpImplementedInterfaces = parsers.extractCSharpImplementedInterfaces;
  const extractCSharpReferenceHints = parsers.extractCSharpReferenceHints;
  const extractServiceRegistrations = parsers.extractServiceRegistrations;
  const resolveCSharpDependencyCandidates = parsers.resolveCSharpDependencyCandidates;
  let flowDefinitions = null;
  let hotspotsAnalyzer = null;
  let testsIndex = null;
  const isLikelyEntrypoint = (...args) => flowDefinitions.isLikelyEntrypoint(...args);
  const isTestFile = (...args) => testsIndex.isTestFile(...args);
  const isStructuredContentFile = (...args) => hotspotsAnalyzer.isStructuredContentFile(...args);
  const isExecutableSurfaceFile = (...args) => hotspotsAnalyzer.isExecutableSurfaceFile(...args);
  const buildReverseDependencyMap = (...args) => hotspotsAnalyzer.buildReverseDependencyMap(...args);
  const getEntrypointCorePathBoost = (...args) => hotspotsAnalyzer.getEntrypointCorePathBoost(...args);
  const selectDiverseHotspots = (...args) => hotspotsAnalyzer.selectDiverseHotspots(...args);

  function resolveWorkingDirectory(workingDirectory) {
    if (typeof workingDirectory !== 'string' || !workingDirectory.trim()) {
      throw new Error('workingDirectory must be a non-empty string');
    }

    const resolved = path.resolve(workingDirectory.trim());
    if (!fs.existsSync(resolved)) {
      throw new Error(`Working directory not found: ${resolved}`);
    }

    return resolved;
  }

  function toRepoPath(filePath) {
    return String(filePath || '').trim().replace(/\\/g, '/');
  }

  function uniqueStrings(values) {
    const seen = new Set();
    const output = [];
    for (const value of Array.isArray(values) ? values : []) {
      const normalized = String(value || '').trim();
      if (!normalized || seen.has(normalized)) {
        continue;
      }
      seen.add(normalized);
      output.push(normalized);
    }
    return output;
  }

  function uniquePaths(values) {
    const seen = new Set();
    const output = [];
    for (const value of Array.isArray(values) ? values : []) {
      const normalized = toRepoPath(value);
      if (!normalized || seen.has(normalized)) {
        continue;
      }
      seen.add(normalized);
      output.push(normalized);
    }
    return output;
  }

  const orchestratorHelpers = createOrchestratorHelpers({
    GENERATED_STUDY_FILES,
    ALLOWED_EXTENSIONS,
    MAX_RUN_BATCH_COUNT,
    scanner,
    logger: studyLogger,
    buildModuleExportLookup,
    buildModuleEntryMap,
    buildInterfaceImplementationMap,
    buildServiceRegistrationLookup,
    extractCSharpExplicitExports,
    extractCSharpImplementedInterfaces,
    extractCSharpReferenceHints,
    extractServiceRegistrations,
    resolveCSharpDependencyCandidates,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
  });
  const normalizeNonNegativeInteger = orchestratorHelpers.normalizeNonNegativeInteger;
  const normalizePositiveInteger = orchestratorHelpers.normalizePositiveInteger;
  const buildCounts = orchestratorHelpers.buildCounts;
  const extractReadmeIntro = orchestratorHelpers.extractReadmeIntro;
  const writeTextFileIfChanged = orchestratorHelpers.writeTextFileIfChanged;
  const safeHeadSha = orchestratorHelpers.safeHeadSha;
  const loadTrackedFiles = orchestratorHelpers.loadTrackedFiles;
  const loadDeltaChanges = orchestratorHelpers.loadDeltaChanges;
  const mergeUnique = orchestratorHelpers.mergeUnique;
  const buildScanLookup = orchestratorHelpers.buildScanLookup;
  const enrichModuleEntries = orchestratorHelpers.enrichModuleEntries;
  const buildModuleEntry = orchestratorHelpers.buildModuleEntry;
  const formatInlineList = orchestratorHelpers.formatInlineList;
  const formatCodeList = orchestratorHelpers.formatCodeList;
  const artifactFiles = createArtifactFiles({
    ensureStudyDocs,
    normalizeModuleIndex,
    STUDY_DIR,
    STATE_FILE,
    MODULE_INDEX_FILE,
    KNOWLEDGE_PACK_FILE,
    STUDY_DELTA_FILE,
    STUDY_EVALUATION_FILE,
    STUDY_BENCHMARK_FILE_LOCAL,
    SUMMARY_FILE,
  });
  const getPaths = artifactFiles.getPaths;
  const readModuleIndex = artifactFiles.readModuleIndex;
  const writeModuleIndex = artifactFiles.writeModuleIndex;
  const writeKnowledgePack = artifactFiles.writeKnowledgePack;
  const writeStudyDelta = artifactFiles.writeStudyDelta;
  const writeStudyBenchmark = artifactFiles.writeStudyBenchmark;

  function buildInitialState() {
    return {
      run_count: 0,
      last_sha: null,
      last_task_id: null,
      last_batch: [],
      last_run_at: null,
      last_completed_at: null,
      last_result: null,
      last_error: null,
      tracked_files: [],
      pending_files: [],
      file_counts: {
        tracked: 0,
        pending: 0,
        up_to_date: 0,
      },
      index_strategy: LOCAL_ONLY_STRATEGY,
      summary_strategy: LOCAL_ONLY_STRATEGY,
      last_processed_count: 0,
      last_removed_count: 0,
      last_summary_updated_at: null,
      knowledge_pack_updated_at: null,
      last_delta_updated_at: null,
      module_entry_count: 0,
      subsystem_count: 0,
      flow_count: 0,
      hotspot_count: 0,
      invariant_count: 0,
      failure_mode_count: 0,
      trace_count: 0,
      playbook_count: 0,
      test_area_count: 0,
      delta_significance_level: 'none',
      delta_significance_score: 0,
      proposal_count: 0,
      submitted_proposal_count: 0,
      proposal_significance_level: DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
      proposal_min_score: DEFAULT_PROPOSAL_MIN_SCORE,
      evaluation_score: 0,
      evaluation_grade: null,
      evaluation_readiness: null,
      evaluation_findings_count: 0,
      evaluation_generated_at: null,
      benchmark_score: 0,
      benchmark_grade: null,
      benchmark_readiness: null,
      benchmark_findings_count: 0,
      benchmark_case_count: 0,
      benchmark_generated_at: null,
    };
  }

  function normalizeState(rawState) {
    const initial = buildInitialState();
    const source = rawState && typeof rawState === 'object' && !Array.isArray(rawState)
      ? rawState
      : {};
    const trackedFiles = uniquePaths(source.tracked_files);
    const pendingFiles = uniquePaths(source.pending_files).filter(file => trackedFiles.includes(file));
    const fileCounts = buildCounts(trackedFiles, pendingFiles);

    return {
      ...initial,
      ...source,
      last_sha: typeof source.last_sha === 'string' && source.last_sha.trim() ? source.last_sha.trim() : null,
      last_task_id: typeof source.last_task_id === 'string' && source.last_task_id.trim() ? source.last_task_id.trim() : null,
      last_batch: uniquePaths(source.last_batch),
      tracked_files: trackedFiles,
      pending_files: pendingFiles,
      file_counts: fileCounts,
      index_strategy: typeof source.index_strategy === 'string' && source.index_strategy.trim()
        ? source.index_strategy.trim()
        : LOCAL_ONLY_STRATEGY,
      summary_strategy: typeof source.summary_strategy === 'string' && source.summary_strategy.trim()
        ? source.summary_strategy.trim()
        : LOCAL_ONLY_STRATEGY,
      last_processed_count: normalizeNonNegativeInteger(source.last_processed_count),
      last_removed_count: normalizeNonNegativeInteger(source.last_removed_count),
      last_summary_updated_at: typeof source.last_summary_updated_at === 'string' && source.last_summary_updated_at.trim()
        ? source.last_summary_updated_at.trim()
        : null,
      knowledge_pack_updated_at: typeof source.knowledge_pack_updated_at === 'string' && source.knowledge_pack_updated_at.trim()
        ? source.knowledge_pack_updated_at.trim()
        : null,
      last_delta_updated_at: typeof source.last_delta_updated_at === 'string' && source.last_delta_updated_at.trim()
        ? source.last_delta_updated_at.trim()
        : null,
      module_entry_count: normalizeNonNegativeInteger(source.module_entry_count),
      subsystem_count: normalizeNonNegativeInteger(source.subsystem_count),
      flow_count: normalizeNonNegativeInteger(source.flow_count),
      hotspot_count: normalizeNonNegativeInteger(source.hotspot_count),
      invariant_count: normalizeNonNegativeInteger(source.invariant_count),
      failure_mode_count: normalizeNonNegativeInteger(source.failure_mode_count),
      trace_count: normalizeNonNegativeInteger(source.trace_count),
      playbook_count: normalizeNonNegativeInteger(source.playbook_count),
      test_area_count: normalizeNonNegativeInteger(source.test_area_count),
      delta_significance_level: typeof source.delta_significance_level === 'string' && source.delta_significance_level.trim()
        ? source.delta_significance_level.trim()
        : 'none',
      delta_significance_score: normalizeNonNegativeInteger(source.delta_significance_score),
      proposal_count: normalizeNonNegativeInteger(source.proposal_count),
      submitted_proposal_count: normalizeNonNegativeInteger(source.submitted_proposal_count),
      proposal_significance_level: normalizeStudyThresholdLevel(
        source.proposal_significance_level,
        DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL
      ),
      proposal_min_score: normalizeNonNegativeInteger(source.proposal_min_score, DEFAULT_PROPOSAL_MIN_SCORE),
      evaluation_score: normalizeNonNegativeInteger(source.evaluation_score),
      evaluation_grade: typeof source.evaluation_grade === 'string' && source.evaluation_grade.trim()
        ? source.evaluation_grade.trim()
        : null,
      evaluation_readiness: typeof source.evaluation_readiness === 'string' && source.evaluation_readiness.trim()
        ? source.evaluation_readiness.trim()
        : null,
      evaluation_findings_count: normalizeNonNegativeInteger(source.evaluation_findings_count),
      evaluation_generated_at: typeof source.evaluation_generated_at === 'string' && source.evaluation_generated_at.trim()
        ? source.evaluation_generated_at.trim()
        : null,
      benchmark_score: normalizeNonNegativeInteger(source.benchmark_score),
      benchmark_grade: typeof source.benchmark_grade === 'string' && source.benchmark_grade.trim()
        ? source.benchmark_grade.trim()
        : null,
      benchmark_readiness: typeof source.benchmark_readiness === 'string' && source.benchmark_readiness.trim()
        ? source.benchmark_readiness.trim()
        : null,
      benchmark_findings_count: normalizeNonNegativeInteger(source.benchmark_findings_count),
      benchmark_case_count: normalizeNonNegativeInteger(source.benchmark_case_count),
      benchmark_generated_at: typeof source.benchmark_generated_at === 'string' && source.benchmark_generated_at.trim()
        ? source.benchmark_generated_at.trim()
        : null,
    };
  }

  function normalizeModuleEntry(rawEntry) {
    const entry = rawEntry && typeof rawEntry === 'object' && !Array.isArray(rawEntry)
      ? rawEntry
      : {};
    const file = toRepoPath(entry.file);
    if (!file) {
      return null;
    }
    return {
      file,
      purpose: typeof entry.purpose === 'string' ? entry.purpose.trim() : '',
      exports: uniqueStrings(entry.exports),
      deps: uniqueStrings(entry.deps),
    };
  }

  function normalizeModuleIndex(rawIndex) {
    const source = rawIndex && typeof rawIndex === 'object' && !Array.isArray(rawIndex)
      ? rawIndex
      : {};
    const modules = [];
    const seen = new Set();
    for (const rawEntry of Array.isArray(source.modules) ? source.modules : []) {
      const entry = normalizeModuleEntry(rawEntry);
      if (!entry || seen.has(entry.file)) {
        continue;
      }
      seen.add(entry.file);
      modules.push(entry);
    }
    modules.sort((left, right) => left.file.localeCompare(right.file));
    return {
      modules,
      last_updated: typeof source.last_updated === 'string' && source.last_updated.trim()
        ? source.last_updated.trim()
        : null,
    };
  }

  async function readJsonIfPresent(filePath) {
    try {
      const raw = await fsPromises.readFile(filePath, 'utf8');
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }

  async function readTextIfPresent(filePath) {
    try {
      return await fsPromises.readFile(filePath, 'utf8');
    } catch {
      return '';
    }
  }

  async function loadRepoMetadata(workingDirectory) {
    const packageJson = await readJsonIfPresent(path.join(workingDirectory, 'package.json'));
    const readmeIntro = extractReadmeIntro(await readTextIfPresent(path.join(workingDirectory, 'README.md')));
    const rootEntries = await fsPromises.readdir(workingDirectory, { withFileTypes: true }).catch(() => []);
    const solutionFiles = rootEntries
      .filter((entry) => entry && typeof entry.name === 'string' && entry.isFile && entry.isFile() && entry.name.toLowerCase().endsWith('.sln'))
      .map((entry) => toRepoPath(entry.name));
    const repoName = typeof packageJson?.name === 'string' && packageJson.name.trim()
      ? packageJson.name.trim()
      : path.basename(workingDirectory);
    const description = typeof packageJson?.description === 'string' && packageJson.description.trim()
      ? packageJson.description.trim()
      : (readmeIntro || `Architecture study for ${repoName}.`);
    const packageMain = typeof packageJson?.main === 'string' && packageJson.main.trim()
      ? toRepoPath(packageJson.main)
      : null;
    const binFiles = packageJson?.bin && typeof packageJson.bin === 'object' && !Array.isArray(packageJson.bin)
      ? uniquePaths(Object.values(packageJson.bin))
      : [];

    return {
      name: repoName,
      description,
      package_main: packageMain,
      bin_files: binFiles,
      package_json: packageJson || null,
      solution_files: solutionFiles,
      dotnet_project: solutionFiles.length > 0 || fs.existsSync(path.join(workingDirectory, 'global.json')),
      python_project: fs.existsSync(path.join(workingDirectory, 'pyproject.toml'))
        || fs.existsSync(path.join(workingDirectory, 'requirements.txt'))
        || fs.existsSync(path.join(workingDirectory, 'setup.py')),
      has_powershell_build: fs.existsSync(path.join(workingDirectory, 'scripts', 'build.ps1')),
    };
  }

  async function ensureStudyDocs(workingDirectory) {
    const paths = getPaths(workingDirectory);
    await fsPromises.mkdir(paths.studyDir, { recursive: true });

    if (!fs.existsSync(paths.summaryPath)) {
      await fsPromises.writeFile(paths.summaryPath, SUMMARY_PLACEHOLDER, 'utf8');
    }
    if (!fs.existsSync(paths.moduleIndexPath)) {
      await fsPromises.writeFile(paths.moduleIndexPath, '{"modules":[],"last_updated":null}\n', 'utf8');
    }
    if (!fs.existsSync(paths.knowledgePackPath)) {
      await fsPromises.writeFile(paths.knowledgePackPath, '{"version":3,"generated_at":null,"study_profile":{},"repo":{},"coverage":{},"artifacts":{},"entrypoints":[],"subsystems":[],"subsystem_relationships":[],"flows":[],"hotspots":[],"navigation_hints":[],"expertise":{"onramp":{},"invariants":[],"failure_modes":[],"canonical_traces":[],"test_matrix":[],"change_playbooks":[],"impact_guidance":[]}}\n', 'utf8');
    }
    if (!fs.existsSync(paths.deltaPath)) {
      await fsPromises.writeFile(paths.deltaPath, '{"version":1,"generated_at":null,"repo":{},"run":{},"coverage_delta":{},"significance":{"level":"none","score":0,"reasons":[]},"changed_files":{"repo_delta":[],"processed":[],"removed":[]},"changed_subsystems":[],"affected_flows":[],"invariant_hits":[],"failure_mode_hits":[],"hotspot_changes":{"entered":[],"exited":[],"touched":[]},"proposals":{"policy":{"allowed":false,"reason":"submission_disabled","threshold_level":"moderate","threshold_score":0,"suppressed_count":0},"suggested":[],"submitted":[],"errors":[]}}\n', 'utf8');
    }
    if (!fs.existsSync(paths.evaluationPath)) {
      await fsPromises.writeFile(paths.evaluationPath, '{"version":1,"generated_at":null,"repo":{},"summary":{"score":0,"grade":null,"readiness":"map_only","findings_count":0,"strengths_count":0,"indexed_percent":0},"checks":{},"strengths":[],"findings":[],"probes":[],"artifacts":{}}\n', 'utf8');
    }
    if (!fs.existsSync(paths.benchmarkPath)) {
      await fsPromises.writeFile(paths.benchmarkPath, '{"version":1,"generated_at":null,"repo":{},"summary":{"score":0,"grade":null,"readiness":"map_only","total_cases":0,"passed_cases":0,"partial_cases":0,"failed_cases":0,"delta_significance_level":"none","evaluation_grade":null},"findings":[],"cases":[],"artifacts":{}}\n', 'utf8');
    }
    if (!fs.existsSync(paths.statePath)) {
      await fsPromises.writeFile(paths.statePath, '{}\n', 'utf8');
    }

    return paths;
  }

  async function readStudyState(workingDirectory) {
    const paths = await ensureStudyDocs(workingDirectory);
    const raw = await fsPromises.readFile(paths.statePath, 'utf8');
    const parsed = raw.trim() ? JSON.parse(raw) : {};
    return { paths, state: normalizeState(parsed) };
  }

  async function writeStudyState(workingDirectory, state) {
    const paths = await ensureStudyDocs(workingDirectory);
    const normalized = normalizeState(state);
    await fsPromises.writeFile(paths.statePath, `${JSON.stringify(normalized, null, 2)}\n`, 'utf8');
    return { paths, state: normalized };
  }

  const subsystems = createSubsystems({
    ROOT_DOC_FILES,
    LOW_SIGNAL_EXPORT_NAMES,
    RELATIONSHIP_LIMIT,
    isLikelyEntrypoint,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
    formatInlineList,
    formatCodeList,
  });
  const buildSubsystemRows = subsystems.buildSubsystemRows;
  const getSubsystemForFile = subsystems.getSubsystemForFile;
  const buildSubsystemLookup = subsystems.buildSubsystemLookup;
  const getSubsystemPriority = subsystems.getSubsystemPriority;
  const buildDetectionSummary = subsystems.buildDetectionSummary;
  const buildSubsystemRelationships = subsystems.buildSubsystemRelationships;

  flowDefinitions = createFlowDefinitions({
    GENERIC_FLOW_IDS,
    SYMBOL_INDEX_EXTENSIONS,
    getSubsystemForFile,
    buildModuleEntryMap,
    isTestFile,
    isStructuredContentFile,
    isExecutableSurfaceFile,
    buildReverseDependencyMap,
    getEntrypointCorePathBoost,
    selectDiverseHotspots,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
  });
  const buildFlowSummaries = flowDefinitions.buildFlowSummaries;
  const buildEntrypoints = flowDefinitions.buildEntrypoints;

  hotspotsAnalyzer = createHotspotsAnalyzer({
    HOTSPOT_LIMIT,
    LOW_SIGNAL_HOTSPOT_BASENAMES,
    SYMBOL_INDEX_EXTENSIONS,
    getSubsystemForFile,
    isLikelyEntrypoint,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
  });

  testsIndex = createTestsIndex({
    TEST_FILE_PATTERN,
    TEST_SUFFIX_PATTERN,
    TOKEN_STOP_WORDS,
    TEST_MATRIX_LIMIT,
    getSubsystemForFile,
    getSubsystemPriority,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
  });
  const buildTestInventory = testsIndex.buildTestInventory;
  const findTestsForFiles = testsIndex.findTestsForFiles;
  const buildValidationCommands = testsIndex.buildValidationCommands;

  const expertise = createExpertise({
    GENERIC_FLOW_IDS,
    SUMMARY_SUBSYSTEM_LIMIT,
    TRACE_LIMIT,
    NAVIGATION_HINT_LIMIT,
    findTestsForFiles,
    buildValidationCommands,
    uniqueStrings,
    uniquePaths,
  });
  const buildOperationalInvariants = expertise.buildOperationalInvariants;
  const buildFailureModes = expertise.buildFailureModes;
  const buildCanonicalTraces = expertise.buildCanonicalTraces;
  const buildChangePlaybooks = expertise.buildChangePlaybooks;
  const buildImpactGuidance = expertise.buildImpactGuidance;
  const buildExpertiseOnramp = expertise.buildExpertiseOnramp;
  const buildCapabilityList = expertise.buildCapabilityList;
  const buildNavigationHints = expertise.buildNavigationHints;

  const profileSerializer = createProfileSerializer({
    STUDY_PROFILE_OVERRIDE_FILE,
    buildDetectionSummary,
    resolveWorkingDirectory,
    loadRepoMetadata,
    resolveStudyProfile,
    detectStudyProfileSignals,
    getStudyProfileOverridePath,
    readStudyProfileOverride,
    createStudyProfileOverrideTemplate,
    uniqueStrings,
  });
  const serializeStudyProfile = profileSerializer.serializeStudyProfile;
  const maybeWriteStudyProfileOverrideScaffold = profileSerializer.maybeWriteStudyProfileOverrideScaffold;
  const describeStudyProfile = profileSerializer.describeStudyProfile;

  const summary = createSummary({
    SUMMARY_PLACEHOLDER,
    KNOWLEDGE_PACK_FILE,
    STUDY_DELTA_FILE,
    MODULE_INDEX_FILE,
    HOTSPOT_LIMIT,
    NAVIGATION_HINT_LIMIT,
    SUMMARY_SUBSYSTEM_LIMIT,
    SUMMARY_FLOW_LIMIT,
    SUMMARY_INVARIANT_LIMIT,
    SUMMARY_FAILURE_MODE_LIMIT,
    SUMMARY_PLAYBOOK_LIMIT,
    SIGNIFICANCE_REASON_LIMIT,
    LOCAL_ONLY_STRATEGY,
    DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
    DEFAULT_PROPOSAL_MIN_SCORE,
    uniquePaths,
    uniqueStrings,
    formatInlineList,
    formatCodeList,
  });
  const buildSummaryFromKnowledgePack = summary.buildSummaryFromKnowledgePack;
  const buildStatusPayload = summary.buildStatusPayload;
  const toPercent = summary.toPercent;

  const studyProposals = createProposals({
    STUDY_DELTA_FILE,
    KNOWLEDGE_PACK_FILE,
    STUDY_DELTA_VERSION,
    DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
    DEFAULT_PROPOSAL_MIN_SCORE,
    SIGNIFICANCE_REASON_LIMIT,
    MAX_PROPOSAL_LIMIT,
    getSubsystemForFile,
    getSubsystemPriority,
    findTestsForFiles,
    buildValidationCommands,
    toRepoPath,
    uniqueStrings,
    uniquePaths,
  });
  const buildStudyDelta = studyProposals.buildStudyDelta;

  const flows = createFlows({
    db: _db,
    logger: studyLogger,
    scanner,
    evaluator,
    proposer,
    profileManager,
    hotspotsAnalyzer,
    taskCore,
    effectiveBatchSize,
    helpers: {
      resolveWorkingDirectory,
      readStudyState,
      writeStudyState,
      safeHeadSha,
      loadTrackedFiles,
      loadDeltaChanges,
      mergeUnique,
      uniquePaths,
      updateStudyDocs,
      normalizeState,
      buildCounts,
      buildStatusPayload,
      buildInitialState,
      loadRepoMetadata,
      describeStudyProfile,
      maybeWriteStudyProfileOverrideScaffold,
      readJsonIfPresent,
      normalizeNonNegativeInteger,
      normalizePositiveInteger,
      normalizeStudyThresholdLevel,
      buildStudyBootstrapPlan,
      benchmarkStudy,
    },
    constants: {
      DEFAULT_LOCAL_BATCH_SIZE,
      DEFAULT_MANUAL_RUN_BATCH_COUNT,
      DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
      DEFAULT_PROPOSAL_MIN_SCORE,
      LOCAL_ONLY_STRATEGY,
      STUDY_OUTPUT_FILES,
      STUDY_BENCHMARK_FILE_LOCAL,
      STUDY_EVALUATION_FILE,
    },
  });

  async function buildKnowledgePack(workingDirectory, modules, context = {}) {
    const repoMetadata = await loadRepoMetadata(workingDirectory);
    const trackedFiles = uniquePaths(context.trackedFiles || modules.map(entry => entry.file));
    const pendingFiles = uniquePaths(context.pendingFiles || []);
    const availableFiles = new Set(trackedFiles);
    const profile = resolveStudyProfile({
      repoMetadata,
      trackedFiles,
      workingDirectory,
    });
    const repoSignals = detectStudyProfileSignals({
      repoMetadata,
      trackedFiles,
      profile,
    });
    const subsystemLookup = buildSubsystemLookup([...trackedFiles, ...modules.map(entry => entry.file)], profile);
    const reverseDeps = hotspotsAnalyzer.buildReverseDependencyMap(modules);
    const subsystems = buildSubsystemRows(modules, {
      trackedFiles,
      pendingFiles,
      reverseDeps,
      subsystemLookup,
      activeProfile: profile,
    });
    const relationships = buildSubsystemRelationships(modules, subsystemLookup, profile);
    const hotspots = hotspotsAnalyzer.analyzeHotspots({
      entries: modules,
      reverseDeps,
      subsystemLookup,
      activeProfile: profile,
      repoSignals,
    });
    const entrypoints = buildEntrypoints(repoMetadata, availableFiles, hotspots, modules, subsystemLookup, profile, repoSignals);
    const flows = buildFlowSummaries({
      repoMetadata,
      trackedFiles,
      modules,
      entrypoints,
      hotspots,
      subsystemLookup,
      activeProfile: profile,
    });
    const testInventory = buildTestInventory(modules, trackedFiles, subsystemLookup, flows, profile, workingDirectory);
    const invariants = buildOperationalInvariants(subsystems, flows, testInventory, profile);
    const failureModes = buildFailureModes(flows, hotspots, testInventory, profile);
    const canonicalTraces = buildCanonicalTraces(flows, testInventory, profile);
    const changePlaybooks = buildChangePlaybooks(subsystems, flows, testInventory, profile, workingDirectory, invariants);
    const impactGuidance = buildImpactGuidance(subsystems, flows, invariants, testInventory, profile, workingDirectory);
    const onramp = buildExpertiseOnramp(profile, entrypoints, flows, invariants, subsystems);
    const publicProfile = serializeStudyProfile({ ...profile, detection: repoSignals });
    const coverage = {
      tracked_files: trackedFiles.length,
      indexed_modules: modules.length,
      pending_files: pendingFiles.length,
      indexed_percent: toPercent(modules.length, trackedFiles.length),
    };

    return {
      version: KNOWLEDGE_PACK_VERSION,
      generated_at: context.generatedAt || new Date().toISOString(),
      study_profile: publicProfile,
      repo: {
        name: repoMetadata.name,
        description: repoMetadata.description,
        working_directory: workingDirectory,
        current_sha: context.currentSha || null,
        study_strategy: LOCAL_ONLY_STRATEGY,
        detection: buildDetectionSummary(repoSignals),
        capabilities: buildCapabilityList(subsystems, flows),
      },
      coverage,
      artifacts: {
        summary: SUMMARY_FILE.replace(/\\/g, '/'),
        module_index: MODULE_INDEX_FILE.replace(/\\/g, '/'),
        knowledge_pack: KNOWLEDGE_PACK_FILE.replace(/\\/g, '/'),
        study_evaluation: STUDY_EVALUATION_FILE.replace(/\\/g, '/'),
        study_benchmark: STUDY_BENCHMARK_FILE.replace(/\\/g, '/'),
      },
      entrypoints,
      subsystems,
      subsystem_relationships: relationships,
      flows,
      hotspots,
      navigation_hints: buildNavigationHints(flows, subsystems, entrypoints),
      expertise: {
        onramp,
        invariants,
        failure_modes: failureModes,
        canonical_traces: canonicalTraces,
        test_matrix: testInventory.coverage,
        change_playbooks: changePlaybooks,
        impact_guidance: impactGuidance,
      },
    };
  }

  async function updateStudyDocs(workingDirectory, batchFiles, removedFiles, context = {}) {
    const paths = await ensureStudyDocs(workingDirectory);
    const previousKnowledgePack = await readJsonIfPresent(paths.knowledgePackPath);
    const { moduleIndex } = await readModuleIndex(workingDirectory);
    const entryMap = new Map(moduleIndex.modules.map(entry => [entry.file, entry]));
    const trackedFiles = uniquePaths(context.trackedFiles || []);
    const scanTargets = uniquePaths([
      ...uniquePaths(batchFiles),
      ...trackedFiles.filter(file => !entryMap.has(file)),
    ]);
    const scanLookup = scanTargets.length > 0
      ? buildScanLookup(await scanner.scanRepo(workingDirectory, { files: scanTargets }))
      : buildScanLookup({ files: [], symbols: [], imports: [] });

    for (const removedFile of uniquePaths(removedFiles)) {
      entryMap.delete(removedFile);
    }

    const updatedEntries = [];
    for (const batchFile of uniquePaths(batchFiles)) {
      const entry = await buildModuleEntry(workingDirectory, batchFile, scanLookup);
      if (entry) {
        entryMap.set(entry.file, entry);
        updatedEntries.push(entry.file);
      }
    }

    // Self-heal stale module indexes when tracked study candidates expand without a git diff.
    for (const trackedFile of trackedFiles) {
      if (entryMap.has(trackedFile)) {
        continue;
      }
      const entry = await buildModuleEntry(workingDirectory, trackedFile, scanLookup);
      if (entry) {
        entryMap.set(entry.file, entry);
        updatedEntries.push(entry.file);
      }
    }

    const nextModules = await enrichModuleEntries(
      Array.from(entryMap.values()).sort((left, right) => left.file.localeCompare(right.file)),
      workingDirectory
    );
    const dateStamp = new Date().toISOString().slice(0, 10);
    await writeModuleIndex(workingDirectory, {
      modules: nextModules,
      last_updated: dateStamp,
    });

    const knowledgePack = await buildKnowledgePack(workingDirectory, nextModules, {
      trackedFiles,
      pendingFiles: context.pendingFiles || [],
      currentSha: context.currentSha || null,
      generatedAt: context.generatedAt || new Date().toISOString(),
    });
    const activeProfile = resolveStudyProfile({
      repoMetadata: {
        name: knowledgePack?.repo?.name,
        description: knowledgePack?.repo?.description,
      },
      trackedFiles: trackedFiles.length > 0 ? trackedFiles : nextModules.map(entry => entry.file),
      workingDirectory,
    });
    await writeKnowledgePack(workingDirectory, knowledgePack);
    const studyDelta = buildStudyDelta(previousKnowledgePack, knowledgePack, {
      workingDirectory,
      currentSha: context.currentSha || null,
      previousSha: context.previousSha || null,
      signalFiles: context.signalFiles || [],
      processedFiles: batchFiles,
      removedFiles,
      generatedAt: context.generatedAt || new Date().toISOString(),
      batchCount: context.batchCount || 0,
      manualRunNow: context.manualRunNow === true,
      forceRefresh: context.forceRefresh === true,
      scheduleId: context.scheduleId || null,
      scheduleName: context.scheduleName || null,
      scheduleRunId: context.scheduleRunId || null,
      currentTaskId: context.currentTaskId || null,
      activeProfile,
      subsystemLookup: buildSubsystemLookup([
        ...trackedFiles,
        ...nextModules.map(entry => entry.file),
        ...(context.signalFiles || []),
      ], activeProfile),
      isBaseline: !context.previousSha,
    });
    const evaluationResult = await evaluator.evaluateStudy(workingDirectory, {
      workingDirectory,
      state: {
        file_counts: {
          tracked: trackedFiles.length,
          pending: (context.pendingFiles || []).length,
        },
      },
      moduleIndex: {
        modules: nextModules,
      },
      knowledgePack,
      studyDelta,
      activeProfile,
      persistState: false,
    });
    const filteredProposals = proposer.filterProposals(
      evaluationResult.proposals?.suggested || [],
      {
        studyDelta,
        project: context.project,
        workingDirectory,
        submitProposals: context.submitProposals === true,
        proposalSignificanceLevel: context.proposalSignificanceLevel,
        proposalMinScore: context.proposalMinScore,
      }
    );
    const proposalResult = await proposer.submitProposals(workingDirectory, {
      workingDirectory,
      project: context.project,
      proposalLimit: context.proposalLimit,
      proposalSignificanceLevel: context.proposalSignificanceLevel,
      proposalMinScore: context.proposalMinScore,
      proposals: filteredProposals,
    });
    studyDelta.proposals = proposalResult;
    await writeStudyDelta(workingDirectory, studyDelta);
    const studyEvaluation = await readJsonIfPresent(paths.evaluationPath);
    const studyBenchmark = await readJsonIfPresent(paths.benchmarkPath);
    const summaryText = buildSummaryFromKnowledgePack(knowledgePack, studyDelta, studyEvaluation, studyBenchmark);
    const summaryUpdated = await writeTextFileIfChanged(paths.summaryPath, summaryText);

    return {
      module_entry_count: nextModules.length,
      module_entries_updated: updatedEntries.length,
      module_entries_removed: uniquePaths(removedFiles).length,
      subsystem_count: knowledgePack.subsystems.length,
      flow_count: knowledgePack.flows.length,
      hotspot_count: knowledgePack.hotspots.length,
      invariant_count: knowledgePack.expertise?.invariants?.length || 0,
      failure_mode_count: knowledgePack.expertise?.failure_modes?.length || 0,
      trace_count: knowledgePack.expertise?.canonical_traces?.length || 0,
      playbook_count: knowledgePack.expertise?.change_playbooks?.length || 0,
      test_area_count: knowledgePack.expertise?.test_matrix?.length || 0,
      delta_significance_level: studyDelta.significance.level,
      delta_significance_score: studyDelta.significance.score,
      proposal_count: proposalResult?.suggested?.length || 0,
      submitted_proposal_count: proposalResult?.submitted?.length || 0,
      proposal_significance_level: proposalResult?.policy?.threshold_level || normalizeStudyThresholdLevel(context.proposalSignificanceLevel),
      proposal_min_score: proposalResult?.policy?.threshold_score ?? normalizeNonNegativeInteger(context.proposalMinScore, DEFAULT_PROPOSAL_MIN_SCORE),
      evaluation_score: studyEvaluation.summary.score,
      evaluation_grade: studyEvaluation.summary.grade,
      evaluation_readiness: studyEvaluation.summary.readiness,
      evaluation_findings_count: studyEvaluation.summary.findings_count,
      evaluation_generated_at: studyEvaluation.generated_at,
      benchmark_score: studyBenchmark.summary.score,
      benchmark_grade: studyBenchmark.summary.grade,
      benchmark_readiness: studyBenchmark.summary.readiness,
      benchmark_findings_count: studyBenchmark.findings.length,
      benchmark_case_count: studyBenchmark.summary.total_cases,
      benchmark_generated_at: studyBenchmark.generated_at,
      study_delta: studyDelta,
      study_evaluation: studyEvaluation,
      study_benchmark: studyBenchmark,
      summary_updated: summaryUpdated,
    };
  }

  async function getStudyStatus(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const { state } = await readStudyState(resolvedWorkingDirectory);
    return buildStatusPayload(resolvedWorkingDirectory, state, safeHeadSha(resolvedWorkingDirectory));
  }

  async function evaluateStudy(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const { paths, state } = await readStudyState(resolvedWorkingDirectory);
    const { moduleIndex } = await readModuleIndex(resolvedWorkingDirectory);
    const knowledgePack = await readJsonIfPresent(paths.knowledgePackPath);
    const studyDelta = await readJsonIfPresent(paths.deltaPath);

    if (!knowledgePack?.generated_at) {
      throw new Error('Study artifacts are not ready yet. Run the codebase study before evaluating it.');
    }

    await evaluator.evaluateStudy(resolvedWorkingDirectory, {
      workingDirectory: resolvedWorkingDirectory,
      state,
      moduleIndex,
      knowledgePack,
      studyDelta,
      persistState: false,
    });
    const studyEvaluation = await readJsonIfPresent(paths.evaluationPath);
    const studyBenchmark = await readJsonIfPresent(paths.benchmarkPath);
    const nextState = normalizeState({
      ...state,
      evaluation_score: studyEvaluation.summary.score,
      evaluation_grade: studyEvaluation.summary.grade,
      evaluation_readiness: studyEvaluation.summary.readiness,
      evaluation_findings_count: studyEvaluation.summary.findings_count,
      evaluation_generated_at: studyEvaluation.generated_at,
      benchmark_score: studyBenchmark.summary.score,
      benchmark_grade: studyBenchmark.summary.grade,
      benchmark_readiness: studyBenchmark.summary.readiness,
      benchmark_findings_count: studyBenchmark.findings.length,
      benchmark_case_count: studyBenchmark.summary.total_cases,
      benchmark_generated_at: studyBenchmark.generated_at,
    });
    await writeStudyState(resolvedWorkingDirectory, nextState);

    return {
      ...buildStatusPayload(resolvedWorkingDirectory, nextState, safeHeadSha(resolvedWorkingDirectory)),
      study_evaluation: studyEvaluation,
      study_benchmark: studyBenchmark,
      files_modified: [
        STUDY_EVALUATION_FILE.replace(/\\/g, '/'),
        STUDY_BENCHMARK_FILE_LOCAL.replace(/\\/g, '/'),
      ],
    };
  }

  async function benchmarkStudy(workingDirectory) {
    const resolvedWorkingDirectory = resolveWorkingDirectory(workingDirectory);
    const { paths, state } = await readStudyState(resolvedWorkingDirectory);
    const { moduleIndex } = await readModuleIndex(resolvedWorkingDirectory);
    const knowledgePack = await readJsonIfPresent(paths.knowledgePackPath);
    const studyDelta = await readJsonIfPresent(paths.deltaPath);
    const studyEvaluation = await readJsonIfPresent(paths.evaluationPath);

    if (!knowledgePack?.generated_at) {
      throw new Error('Study artifacts are not ready yet. Run the codebase study before benchmarking it.');
    }

    const benchmarkSourceEvaluation = studyEvaluation?.summary
      ? studyEvaluation
      : evaluateStudyArtifacts({
          knowledgePack,
          studyDelta,
          state,
          moduleIndex,
          workingDirectory: resolvedWorkingDirectory,
        });
    const studyBenchmark = benchmarkStudyArtifacts({
      knowledgePack,
      studyDelta,
      studyEvaluation: benchmarkSourceEvaluation,
      moduleIndex,
      workingDirectory: resolvedWorkingDirectory,
    });
    await writeStudyBenchmark(resolvedWorkingDirectory, studyBenchmark);
    const nextState = normalizeState({
      ...state,
      benchmark_score: studyBenchmark.summary.score,
      benchmark_grade: studyBenchmark.summary.grade,
      benchmark_readiness: studyBenchmark.summary.readiness,
      benchmark_findings_count: studyBenchmark.findings.length,
      benchmark_case_count: studyBenchmark.summary.total_cases,
      benchmark_generated_at: studyBenchmark.generated_at,
    });
    await writeStudyState(resolvedWorkingDirectory, nextState);

    return {
      ...buildStatusPayload(resolvedWorkingDirectory, nextState, safeHeadSha(resolvedWorkingDirectory)),
      study_benchmark: studyBenchmark,
      files_modified: [STUDY_BENCHMARK_FILE_LOCAL.replace(/\\/g, '/')],
    };
  }

  return {
    runStudyCycle: flows.runStudyCycle,
    getStudyStatus,
    evaluateStudy,
    benchmarkStudy,
    getStudyProfileOverrideStatus: (workingDirectory) => profileManager.getOverrideStatus(workingDirectory),
    saveStudyProfileOverride: (workingDirectory, overrideValue, options = {}) => (
      profileManager.saveOverride(workingDirectory, overrideValue, options)
    ),
    previewBootstrapStudy: flows.previewBootstrapStudy,
    bootstrapStudy: flows.bootstrapStudy,
    resetStudy: flows.resetStudy,
    _testing: {
      buildInterfaceImplementationMap,
      buildModuleEntryMap,
      buildModuleExportLookup,
      buildServiceRegistrationLookup,
      extractCSharpReferenceHints,
      extractServiceRegistrations,
      resolveCSharpDependencyCandidates,
    },
  };
}

module.exports = {
  createCodebaseStudy,
};
