// Plan-path utilities shared between the loop controller and other
// callers that need to resolve where auto-generated factory plans live.
//
// Extracted from server/factory/loop-controller.js as Phase 1a-prep of the
// god-object refactor — no behavior change. Each helper is pure (path/fs
// stdlib only, no shared state, no DB).

const fs = require('fs');
const path = require('path');

function resolvePlansRepoRoot(projectPath, plansDir) {
  const candidates = [];

  if (projectPath) {
    candidates.push(path.resolve(projectPath));
  }

  if (plansDir) {
    let current = path.resolve(plansDir);
    while (current && !candidates.includes(current)) {
      candidates.push(current);
      const parent = path.dirname(current);
      if (parent === current) {
        break;
      }
      current = parent;
    }
  }

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, '.git'))) {
      return candidate;
    }
  }

  for (const candidate of candidates) {
    if (fs.existsSync(candidate) && fs.existsSync(path.join(candidate, 'server'))) {
      return candidate;
    }
  }

  return candidates.find((candidate) => fs.existsSync(candidate)) || path.resolve(plansDir || projectPath || process.cwd());
}

function slugifyAutoGeneratedPlanSegment(value) {
  const normalized = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!normalized) {
    return 'work-item';
  }

  return normalized.slice(0, 80).replace(/-+$/g, '') || 'work-item';
}

function inferAutoGeneratedPlanTechStack(projectPath) {
  const root = projectPath ? path.resolve(projectPath) : process.cwd();

  try {
    const entries = fs.readdirSync(root);
    if (entries.some((entry) => entry.endsWith('.csproj') || entry.endsWith('.sln'))
      || fs.existsSync(path.join(root, 'simtests', 'SimCore.DotNet.Tests.csproj'))
      || fs.existsSync(path.join(root, 'server', 'DeadlockRelay'))
      || fs.existsSync(path.join(root, 'client', 'UnityProject'))) {
      return 'C#/.NET, Unity';
    }
  } catch {
    // Continue with marker-based inference below.
  }

  if (fs.existsSync(path.join(root, 'package.json'))) {
    return 'Node.js';
  }
  if (fs.existsSync(path.join(root, 'pyproject.toml')) || fs.existsSync(path.join(root, 'requirements.txt'))) {
    return 'Python';
  }
  if (fs.existsSync(path.join(root, 'Cargo.toml'))) {
    return 'Rust';
  }

  return 'application code';
}

function buildAutoGeneratedPlanPath(project, workItem, projectPathOverride = null) {
  const projectPath = path.resolve(projectPathOverride || project?.path || process.cwd());
  const plansDirHint = path.join(
    projectPath,
    'docs',
    'superpowers',
    'plans'
  );
  const repoRoot = resolvePlansRepoRoot(projectPath, plansDirHint);
  const fileName = `${workItem.id}-${slugifyAutoGeneratedPlanSegment(workItem?.title)}.md`;
  return path.join(repoRoot, 'docs', 'superpowers', 'plans', 'auto-generated', fileName);
}

module.exports = {
  resolvePlansRepoRoot,
  slugifyAutoGeneratedPlanSegment,
  inferAutoGeneratedPlanTechStack,
  buildAutoGeneratedPlanPath,
};
