// Plan-path utilities shared between the loop controller and other
// callers that need to resolve where auto-generated factory plans live.
//
// Extracted from server/factory/loop-controller.js as Phase 1a-prep of the
// god-object refactor — no behavior change. Each helper is pure (path/fs
// stdlib only, no shared state, no DB).

const fs = require('fs');
const path = require('path');

function resolvePlansRepoRoot(projectPath, plansDir) {
  const candidates = [];

  if (projectPath) {
    candidates.push(path.resolve(projectPath));
  }

  if (plansDir) {
    let current = path.resolve(plansDir);
    while (current && !candidates.includes(current)) {
      candidates.push(current);
      const parent = path.dirname(current);
      if (parent === current) {
        break;
      }
      current = parent;
    }
  }

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, '.git'))) {
      return candidate;
    }
  }

  for (const candidate of candidates) {
    if (fs.existsSync(candidate) && fs.existsSync(path.join(candidate, 'server'))) {
      return candidate;
    }
  }

  return candidates.find((candidate) => fs.existsSync(candidate)) || path.resolve(plansDir || projectPath || process.cwd());
}

function slugifyAutoGeneratedPlanSegment(value) {
  const normalized = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!normalized) {
    return 'work-item';
  }

  return normalized.slice(0, 80).replace(/-+$/g, '') || 'work-item';
}

function inferAutoGeneratedPlanTechStack(projectPath) {
  const root = projectPath ? path.resolve(projectPath) : process.cwd();

  try {
    const entries = fs.readdirSync(root);
    if (entries.some((entry) => entry.endsWith('.csproj') || entry.endsWith('.sln'))
      || fs.existsSync(path.join(root, 'simtests', 'SimCore.DotNet.Tests.csproj'))
      || fs.existsSync(path.join(root, 'server', 'DeadlockRelay'))
      || fs.existsSync(path.join(root, 'client', 'UnityProject'))) {
      return 'C#/.NET, Unity';
    }
  } catch {
    // Continue with marker-based inference below.
  }

  if (fs.existsSync(path.join(root, 'package.json'))) {
    return 'Node.js';
  }
  if (fs.existsSync(path.join(root, 'pyproject.toml')) || fs.existsSync(path.join(root, 'requirements.txt'))) {
    return 'Python';
  }
  if (fs.existsSync(path.join(root, 'Cargo.toml'))) {
    return 'Rust';
  }

  return 'application code';
}

function buildAutoGeneratedPlanPath(project, workItem, projectPathOverride = null) {
  const projectPath = path.resolve(projectPathOverride || project?.path || process.cwd());
  const plansDirHint = path.join(
    projectPath,
    'docs',
    'superpowers',
    'plans'
  );
  const repoRoot = resolvePlansRepoRoot(projectPath, plansDirHint);
  const fileName = `${workItem.id}-${slugifyAutoGeneratedPlanSegment(workItem?.title)}.md`;
  return path.join(repoRoot, 'docs', 'superpowers', 'plans', 'auto-generated', fileName);
}

// --- Plan-path internals (Phase 1a-prep continuation) -----------------
// Path-extension classification, language-family inference, and the
// project-relative normalizer used by scope-search and verify helpers.

const PLAN_RELATED_FILE_EXT_RE = /\.(?:cjs|mjs|js|ts|tsx|jsx|json|ya?ml|md|ps1|py|cs|csproj|sln)$/i;
const PLAN_RELATED_SKIP_DIRS = new Set([
  '.git',
  '.worktrees',
  'node_modules',
  'coverage',
  'dist',
  'build',
  '.next',
  '.cache',
  'tmp',
  'temp',
]);
const PLAN_RELATED_GENERATED_ARTIFACT_RE = /^(?:docs\/superpowers\/plans\/auto-generated|docs\/findings)\//i;

function isInternalTempWorktreePlanPath(filePath) {
  const normalized = String(filePath || '').trim().replace(/\\/g, '/').replace(/^\.\//, '');
  if (!normalized) return false;
  return normalized.startsWith('.tmp/worktrees/')
    || normalized.includes('/.tmp/worktrees/');
}

function getPlanPathExtension(filePath) {
  return path.extname(String(filePath || '').replace(/\\/g, '/')).toLowerCase();
}

function getPlanPathLanguageFamily(filePath) {
  const ext = getPlanPathExtension(filePath);
  if (['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx'].includes(ext)) return 'javascript';
  if (['.cs', '.csproj', '.sln'].includes(ext)) return 'csharp';
  if (ext === '.py') return 'python';
  if (ext === '.go') return 'go';
  if (ext === '.rs') return 'rust';
  if (['.java', '.gradle'].includes(ext)) return 'java';
  return null;
}

function getRequestedPlanLanguageFamilies(workItem, seedFiles = []) {
  const text = `${workItem?.title || ''}\n${workItem?.description || ''}\n${(seedFiles || []).join('\n')}`.toLowerCase();
  const families = new Set();
  if (/(?:\btypescript\b|\bjavascript\b|\bnode\.?js\b|\breact\b|\.tsx?\b|\.jsx?\b)/i.test(text)) {
    families.add('javascript');
  }
  if (/(?:\bc#\b|\bcsharp\b|\.csproj\b|\.sln\b|\.cs\b|\bdotnet\b)/i.test(text)) {
    families.add('csharp');
  }
  if (/(?:\bpython\b|\.py\b|pytest)/i.test(text)) families.add('python');
  if (/(?:\bgolang\b|\bgo\b|\.go\b|go\s+test)/i.test(text)) families.add('go');
  if (/(?:\brust\b|\.rs\b|cargo\s+test)/i.test(text)) families.add('rust');
  if (/(?:\bjava\b|\.java\b|gradle|mvn\s+test)/i.test(text)) families.add('java');
  return families;
}

function isLanguageCompatibleRelatedFile(filePath, requestedFamilies) {
  if (!requestedFamilies || requestedFamilies.size === 0) return true;
  const family = getPlanPathLanguageFamily(filePath);
  return !family || requestedFamilies.has(family);
}

function normalizePlanProjectRelativePath(filePath, projectPath = null) {
  const raw = String(filePath || '').trim().replace(/^`|`$/g, '');
  if (!raw) return null;
  if (!projectPath) {
    const normalizedRaw = raw.replace(/\\/g, '/');
    return isInternalTempWorktreePlanPath(normalizedRaw) ? null : normalizedRaw;
  }
  // Filter out PascalCase module-style names mentioned in prose (e.g.
  // "FooBar.js", "MyService.ts") that aren't repo-relative paths. Drop
  // the /i flag — lowercase filenames like "fix-me.js" or "config.ts"
  // are real files relative to the project root and must NOT be filtered.
  if (!/[\\/]/.test(raw) && /^[A-Z][A-Za-z0-9_-]*\.(?:js|ts|py|cs)$/.test(raw)) {
    return null;
  }

  const root = path.resolve(projectPath);
  const absolute = path.isAbsolute(raw)
    ? path.resolve(raw)
    : path.resolve(root, raw);
  const rel = path.relative(root, absolute);
  if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) {
    return null;
  }
  const normalizedRel = rel.replace(/\\/g, '/');
  if (isInternalTempWorktreePlanPath(normalizedRel)) {
    return null;
  }
  return normalizedRel;
}

function projectFileExists(projectPath, filePath) {
  const rel = normalizePlanProjectRelativePath(filePath, projectPath);
  if (!rel || !projectPath) return false;
  return fs.existsSync(path.resolve(projectPath, rel));
}

function addNormalizedPlanPath(out, filePath, projectPath = null) {
  const normalized = normalizePlanProjectRelativePath(filePath, projectPath);
  if (normalized) out.add(normalized);
}

module.exports = {
  resolvePlansRepoRoot,
  slugifyAutoGeneratedPlanSegment,
  inferAutoGeneratedPlanTechStack,
  buildAutoGeneratedPlanPath,
  PLAN_RELATED_FILE_EXT_RE,
  PLAN_RELATED_SKIP_DIRS,
  PLAN_RELATED_GENERATED_ARTIFACT_RE,
  isInternalTempWorktreePlanPath,
  getPlanPathExtension,
  getPlanPathLanguageFamily,
  getRequestedPlanLanguageFamilies,
  isLanguageCompatibleRelatedFile,
  normalizePlanProjectRelativePath,
  projectFileExists,
  addNormalizedPlanPath,
};
