/**
 * Tool definitions for integrationHandlers
 * Auto-generated by extract-tool-defs.js
 */
// CONSOLIDATION CANDIDATE: 4 routing-rule tools could merge into single routing_rule_crud tool.
// Rationale: add_routing_rule, update_routing_rule, delete_routing_rule, and test_routing are tightly coupled around routing-rule management and action selection.

const tools = [
  {
    name: 'full_project_audit',
    description: 'Run a full-project code audit across all enabled free and local LLM providers. Automatically scans the project, groups source files by subsystem, distributes audit tasks sized to each provider\'s context budget, and submits them all in parallel. Returns task IDs for monitoring. Use this when asked to "scan the whole project" or "audit everything".',
    inputSchema: {
      type: 'object',
      properties: {
        path: {
          type: 'string',
          description: 'Absolute path to the project root directory'
        },
        working_directory: {
          type: 'string',
          description: 'Alias for path (uses project working directory)'
        },
        source_dirs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Source directories to scan relative to project root (default: ["server"])'
        },
        max_tasks_per_provider: {
          type: 'number',
          description: 'Maximum audit tasks per provider (default: 5)',
          default: 5
        },
        min_file_lines: {
          type: 'number',
          description: 'Minimum lines for a file to be included in audit (default: 50)',
          default: 50
        },
        ignore_dirs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Directory names to skip (default: node_modules, .git, dist, build, coverage, tests, docs)'
        }
      },
      required: ['path']
    }
  },
  {
    name: 'scan_project',
    description: 'Scan a project directory and return a structured analysis — file counts, missing tests, TODOs, file sizes, data inventory, and dependencies. Zero LLM cost: pure filesystem operations. Use this instead of exploring codebases with an LLM agent.',
    inputSchema: {
      type: 'object',
      properties: {
        path: {
          type: 'string',
          description: 'Absolute path to the project root directory'
        },
        checks: {
          type: 'array',
          items: {
            type: 'string',
            enum: ['summary', 'missing_tests', 'todos', 'file_sizes', 'data_inventory', 'dependencies']
          },
          description: 'Which checks to run. Defaults to all if omitted.'
        },
        source_dirs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Source directories to scan relative to project root (default: ["src"])'
        },
        test_pattern: {
          type: 'string',
          description: 'Glob-style test file suffix pattern (default: ".test.ts")'
        },
        ignore_dirs: {
          type: 'array',
          items: { type: 'string' },
          description: 'Directory names to ignore (default: ["node_modules", ".git", "dist", "build", "coverage"])'
        }
      },
      required: ['path']
    }
  },
  {
    name: 'task_changes',
    description: 'View all file changes made by a task using git diff',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID to view changes for'
        },
        format: {
          type: 'string',
          enum: ['summary', 'full', 'stat'],
          description: 'Output format: summary (files only), full (complete diff), stat (statistics)',
          default: 'summary'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'rollback_file',
    description: 'Selectively rollback specific files from a task',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID'
        },
        file_path: {
          type: 'string',
          description: 'Path to the file to rollback'
        }
      },
      required: ['task_id', 'file_path']
    }
  },
  {
    name: 'stash_changes',
    description: 'Stash uncommitted changes in a task working directory',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID (uses task working directory)'
        },
        working_directory: {
          type: 'string',
          description: 'Working directory (alternative to task_id)'
        },
        message: {
          type: 'string',
          description: 'Stash message'
        }
      },
      required: []
    }
  },
  {
    name: 'list_rollback_points',
    description: 'Show available rollback options for a task',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'success_rates',
    description: 'Get task success rates grouped by project, template, or time period',
    inputSchema: {
      type: 'object',
      properties: {
        group_by: {
          type: 'string',
          enum: ['project', 'template', 'period_start'],
          description: 'How to group results (default: project)'
        },
        project: {
          type: 'string',
          description: 'Filter by project'
        },
        template: {
          type: 'string',
          description: 'Filter by template'
        },
        period_type: {
          type: 'string',
          enum: ['day', 'week', 'month'],
          description: 'Period granularity'
        },
        from_date: {
          type: 'string',
          description: 'Start date (ISO format)'
        },
        to_date: {
          type: 'string',
          description: 'End date (ISO format)'
        }
      },
      required: []
    }
  },
  {
    name: 'compare_performance',
    description: 'Compare task performance between two time periods',
    inputSchema: {
      type: 'object',
      properties: {
        current_from: {
          type: 'string',
          description: 'Current period start (ISO format)'
        },
        current_to: {
          type: 'string',
          description: 'Current period end (ISO format)'
        },
        previous_from: {
          type: 'string',
          description: 'Previous period start (ISO format)'
        },
        previous_to: {
          type: 'string',
          description: 'Previous period end (ISO format)'
        },
        group_by: {
          type: 'string',
          enum: ['project', 'template'],
          description: 'How to group comparison (default: project)'
        }
      },
      required: ['current_from', 'current_to', 'previous_from', 'previous_to']
    }
  },
  {
    name: 'view_dependencies',
    description: 'Visualize task dependencies in Mermaid diagram format',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Show dependencies for specific task'
        },
        project: {
          type: 'string',
          description: 'Show all dependencies in project'
        },
        include_completed: {
          type: 'boolean',
          description: 'Include completed tasks in diagram',
          default: false
        }
      },
      required: []
    }
  },
  {
    name: 'configure_integration',
    description: 'Configure an external service integration (Slack, Discord, etc.)',
    inputSchema: {
      type: 'object',
      properties: {
        integration_type: {
          type: 'string',
          enum: ['slack', 'discord', 's3', 'prometheus'],
          description: 'Type of integration'
        },
        config: {
          type: 'object',
          description: 'Integration-specific configuration (webhook_url, api_key, etc.)'
        },
        enabled: {
          type: 'boolean',
          description: 'Whether integration is enabled',
          default: true
        }
      },
      required: ['integration_type', 'config']
    }
  },
  {
    name: 'export_report_csv',
    description: 'Export task data as CSV format',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          description: 'Filter by task status'
        },
        project: {
          type: 'string',
          description: 'Filter by project'
        },
        from_date: {
          type: 'string',
          description: 'Filter from date (ISO format)'
        },
        to_date: {
          type: 'string',
          description: 'Filter to date (ISO format)'
        },
        limit: {
          type: 'number',
          description: 'Maximum rows to export',
          default: 1000
        }
      }
    }
  },
  {
    name: 'export_report_json',
    description: 'Export task data as JSON format',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          description: 'Filter by task status'
        },
        project: {
          type: 'string',
          description: 'Filter by project'
        },
        from_date: {
          type: 'string',
          description: 'Filter from date (ISO format)'
        },
        to_date: {
          type: 'string',
          description: 'Filter to date (ISO format)'
        },
        limit: {
          type: 'number',
          description: 'Maximum rows to export',
          default: 1000
        }
      }
    }
  },
  {
    name: 'list_integrations',
    description: 'List all configured external service integrations',
    inputSchema: {
      type: 'object',
      properties: {
        include_disabled: {
          type: 'boolean',
          description: 'Include disabled integrations',
          default: false
        }
      }
    }
  },
  {
    name: 'integration_health',
    description: 'Check health status of configured integrations',
    inputSchema: {
      type: 'object',
      properties: {
        integration_type: {
          type: 'string',
          enum: ['slack', 'discord', 's3', 'prometheus', 'all'],
          description: 'Specific integration to check or "all"',
          default: 'all'
        },
        include_history: {
          type: 'boolean',
          description: 'Include health check history',
          default: false
        }
      }
    }
  },
  {
    name: 'test_integration',
    description: 'Send a test message to verify integration is working',
    inputSchema: {
      type: 'object',
      properties: {
        integration_type: {
          type: 'string',
          enum: ['slack', 'discord'],
          description: 'Integration to test'
        },
        message: {
          type: 'string',
          description: 'Custom test message (optional)',
          default: 'This is a test message from TORQUE'
        }
      },
      required: ['integration_type']
    }
  },
  {
    name: 'disable_integration',
    description: 'Temporarily disable an integration',
    inputSchema: {
      type: 'object',
      properties: {
        integration_type: {
          type: 'string',
          enum: ['slack', 'discord', 's3', 'prometheus'],
          description: 'Integration to disable'
        }
      },
      required: ['integration_type']
    }
  },
  {
    name: 'enable_integration',
    description: 'Re-enable a disabled integration',
    inputSchema: {
      type: 'object',
      properties: {
        integration_type: {
          type: 'string',
          enum: ['slack', 'discord', 's3', 'prometheus'],
          description: 'Integration to enable'
        }
      },
      required: ['integration_type']
    }
  },
  {
    name: 'list_report_exports',
    description: 'List previous report exports',
    inputSchema: {
      type: 'object',
      properties: {
        limit: {
          type: 'number',
          description: 'Maximum exports to return',
          default: 50
        }
      }
    }
  },
  {
    name: 'smart_submit_task',
    description: 'PREFERRED: Submit a task with automatic provider selection. Routes simple tasks (docs, tests, explanations) to local LLM (free, no rate limits) and complex tasks (security, architecture, multi-file) to cloud providers. Supports per-task tuning overrides.',
    inputSchema: {
      type: 'object',
      properties: {
        task: {
          type: 'string',
          description: 'Task description'
        },
        working_directory: {
          type: 'string',
          description: 'Working directory for task execution'
        },
        files: {
          type: 'array',
          items: { type: 'string' },
          description: 'List of files involved in the task (for extension-based routing)'
        },
        model: {
          type: 'string',
          description: 'Model to use. For ollama: e.g., qwen2.5-coder:7b. For codex: e.g., gpt-5.3-codex-spark (passed as -m flag).'
        },
        timeout_minutes: {
          type: 'number',
          description: 'Safety-ceiling task timeout in minutes (default: 480)',
          minimum: 1,
          maximum: 480
        },
        priority: {
          type: 'number',
          description: 'Task priority (higher = more important)'
        },
        override_provider: {
          type: 'string',
          description: 'Force a specific provider, bypassing smart routing'
        },
        context_depth: {
          type: 'number',
          description: 'Depth of import graph traversal for context stuffing (default: 1)',
          enum: [1, 2]
        },
        context_stuff: {
          type: 'boolean',
          description: 'Enable context stuffing — inject relevant project files into the task prompt (default: false)'
        },
        context_budget: {
          type: 'number',
          description: 'Max tokens budget for stuffed context (default: provider-specific)'
        },
        prefer_free: {
          type: 'boolean',
          description: 'Route to $0 providers only: local Ollama first, then cloud free tiers (Google AI, Groq, OpenRouter, Ollama Cloud, Cerebras). Skips paid providers entirely.'
        },
        tuning: {
          type: 'object',
          description: 'Per-task tuning overrides (highest priority, overrides model and global settings)',
          properties: {
            preset: {
              type: 'string',
              enum: ['code', 'precise', 'creative', 'balanced', 'fast'],
              description: 'Apply a tuned profile before explicit overrides. Explicit fields override preset.'
            },
            temperature: { type: 'number', description: 'Override temperature for this task' },
            num_ctx: { type: 'number', description: 'Override context window for this task' },
            top_p: { type: 'number', description: 'Override top_p for this task' },
            top_k: { type: 'number', description: 'Override top_k for this task' },
            repeat_penalty: { type: 'number', description: 'Override repeat_penalty for this task' },
            mirostat: { type: 'number', description: 'Override mirostat for this task (0, 1, 2)' },
            num_predict: { type: 'number', description: 'Override max tokens for this task' }
          }
        },
        routing_template: {
          type: 'string',
          description: "Name or ID of a routing template (e.g. 'Cost Saver', 'Quality First', 'Free Agentic'). Controls the provider+model fallback chain. Available: System Default, Quality First, Cost Saver, Cloud Sprint, Free Agentic, Free Speed, All Local."
        },
        version_intent: {
          type: 'string',
          enum: ['feature', 'fix', 'breaking', 'internal'],
          description: 'Version intent for this task. Required for versioned projects. Determines semver bump: feature=minor, fix=patch, breaking=major, internal=no bump.'
        }
      },
      required: ['task']
    }
  },
  {
    name: 'submit_chunked_review',
    description: 'Submit a large file for review by splitting it into manageable chunks. Uses function boundaries when possible, falls back to line-based chunking. Automatically aggregates results.',
    inputSchema: {
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description: 'Absolute path to the file to review'
        },
        review_type: {
          type: 'string',
          enum: ['code_review', 'security_audit', 'documentation', 'refactoring', 'bug_hunt'],
          description: 'Type of review to perform. Default: code_review'
        },
        custom_prompt: {
          type: 'string',
          description: 'Custom review instructions (overrides review_type)'
        },
        model: {
          type: 'string',
          description: 'Model to use (e.g., my-model:14b). Uses smart routing if not specified.'
        },
        token_limit: {
          type: 'number',
          description: 'Token limit per chunk. Default: 32000'
        },
        priority: {
          type: 'number',
          description: 'Task priority (higher = processed first). Default: 0'
        }
      },
      required: ['file_path']
    }
  },
  {
    name: 'get_file_chunks',
    description: 'Preview how a file would be chunked for review without submitting tasks. Useful for understanding chunking strategy.',
    inputSchema: {
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description: 'Absolute path to the file to analyze'
        },
        token_limit: {
          type: 'number',
          description: 'Token limit per chunk. Default: 32000'
        }
      },
      required: ['file_path']
    }
  },
  {
    name: 'test_routing',
    description: 'Test which provider would be selected for a task without submitting it. Useful for understanding routing decisions.',
    inputSchema: {
      type: 'object',
      properties: {
        task: {
          type: 'string',
          description: 'Task description to test'
        },
        files: {
          type: 'array',
          items: { type: 'string' },
          description: 'List of files to test extension-based routing'
        }
      },
      required: ['task']
    }
  },
  {
    name: 'add_routing_rule',
    description: 'Create a new routing rule for smart task routing.',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Unique rule name (e.g., "security-tasks")'
        },
        description: {
          type: 'string',
          description: 'Human-readable description'
        },
        rule_type: {
          type: 'string',
          enum: ['keyword', 'extension', 'regex'],
          description: 'Type of matching: keyword (substring), extension (file extension), regex'
        },
        pattern: {
          type: 'string',
          description: 'Pattern to match. Use | to separate multiple patterns (e.g., "security|auth|password" or ".py|.js")'
        },
        target_provider: {
          type: 'string',
          description: 'Provider to use when rule matches (e.g., "ollama", "claude-cli", "codex")'
        },
        priority: {
          type: 'number',
          description: 'Rule priority (lower = checked first). Default: 50'
        },
        enabled: {
          type: 'boolean',
          description: 'Whether rule is active. Default: true'
        }
      },
      required: ['name', 'pattern', 'target_provider']
    }
  },
  {
    name: 'update_routing_rule',
    description: 'Update an existing routing rule.',
    inputSchema: {
      type: 'object',
      properties: {
        rule: {
          type: 'string',
          description: 'Rule ID or name to update'
        },
        name: { type: 'string', description: 'New name' },
        description: { type: 'string', description: 'New description' },
        rule_type: { type: 'string', enum: ['keyword', 'extension', 'regex'] },
        pattern: { type: 'string', description: 'New pattern' },
        target_provider: { type: 'string', description: 'New target provider' },
        priority: { type: 'number', description: 'New priority' },
        enabled: { type: 'boolean', description: 'Enable/disable rule' }
      },
      required: ['rule']
    }
  },
  {
    name: 'delete_routing_rule',
    description: 'Delete a routing rule.',
    inputSchema: {
      type: 'object',
      properties: {
        rule: {
          type: 'string',
          description: 'Rule ID or name to delete'
        }
      },
      required: ['rule']
    }
  },
  {
    name: 'set_host_priority',
    description: 'Set the priority of an Ollama host. Lower numbers = higher priority. Desktop should be priority 1, Laptop priority 2.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID'
        },
        priority: {
          type: 'number',
          description: 'Priority (lower = higher priority)'
        }
      },
      required: ['host_id', 'priority']
    }
  },
  {
    name: 'configure_review_workflow',
    description: 'Configure the automated review workflow settings.',
    inputSchema: {
      type: 'object',
      properties: {
        review_interval_minutes: {
          type: 'number',
          description: 'How often Claude should check completed tasks (default: 5)'
        },
        auto_approve_simple: {
          type: 'boolean',
          description: 'Automatically approve simple tasks if build passes'
        },
        require_review_for_complex: {
          type: 'boolean',
          description: 'Always require manual review for complex tasks'
        }
      }
    }
  },
  {
    name: 'get_review_workflow_config',
    description: 'Get the current review workflow configuration.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'import_plan',
    description: 'Import tasks from a markdown plan document into a project. Uses AI to parse the plan, extract tasks, and detect dependencies. Use dry_run=true (default) to preview before creating.',
    inputSchema: {
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description: 'Path to the markdown plan file'
        },
        project_name: {
          type: 'string',
          description: 'Name for the project (defaults to filename)'
        },
        dry_run: {
          type: 'boolean',
          default: true,
          description: 'Preview tasks without creating them'
        },
        working_directory: {
          type: 'string',
          description: 'Working directory for task execution'
        }
      },
      required: ['file_path']
    }
  },
  {
    name: 'list_plan_projects',
    description: 'List all plan projects with their status and progress',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['active', 'paused', 'completed', 'failed'],
          description: 'Filter by project status'
        },
        limit: {
          type: 'number',
          default: 20,
          description: 'Maximum projects to return'
        }
      }
    }
  },
  {
    name: 'get_plan_project',
    description: 'Get plan project details including all tasks and their dependency graph',
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'string',
          description: 'Project ID'
        }
      },
      required: ['project_id']
    }
  },
  {
    name: 'pause_plan_project',
    description: 'Pause all queued and waiting tasks in a plan project',
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'string',
          description: 'Project ID'
        }
      },
      required: ['project_id']
    }
  },
  {
    name: 'resume_plan_project',
    description: 'Resume a paused plan project - requeues paused tasks respecting dependencies',
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'string',
          description: 'Project ID'
        }
      },
      required: ['project_id']
    }
  },
  {
    name: 'retry_plan_project',
    description: 'Retry all failed tasks in a plan project and unblock dependent tasks',
    inputSchema: {
      type: 'object',
      properties: {
        project_id: {
          type: 'string',
          description: 'Project ID'
        }
      },
      required: ['project_id']
    }
  },
  {
    name: 'backup_database',
    description: 'Create a backup of the TORQUE database',
    inputSchema: {
      type: 'object',
      properties: {
        dest_path: { type: 'string', description: 'Destination file path for the backup. Defaults to backups/ directory with timestamp.' }
      }
    }
  },
  {
    name: 'restore_database',
    description: 'Restore the TORQUE database from a backup file. DESTRUCTIVE: replaces current database.',
    inputSchema: {
      type: 'object',
      properties: {
        src_path: { type: 'string', description: 'Path to the backup file to restore from' },
        confirm: { type: 'boolean', description: 'Must be true to confirm the restore operation' }
      },
      required: ['src_path', 'confirm']
    }
  },
  {
    name: 'list_database_backups',
    description: 'List available database backups',
    inputSchema: {
      type: 'object',
      properties: {
        directory: { type: 'string', description: 'Directory to search for backups. Defaults to the standard backups/ directory.' }
      }
    }
  },
  {
    name: 'send_email_notification',
    description: 'Send an email notification. If SMTP is not configured, records as pending for later delivery.',
    inputSchema: {
      type: 'object',
      properties: {
        recipient: {
          type: 'string',
          description: 'Email address of the recipient'
        },
        subject: {
          type: 'string',
          description: 'Email subject line'
        },
        body: {
          type: 'string',
          description: 'Email body text'
        },
        task_id: {
          type: 'string',
          description: 'Optional task ID to associate with the notification'
        }
      },
      required: ['recipient', 'subject', 'body']
    }
  },
  {
    name: 'list_email_notifications',
    description: 'List email notifications with optional status and task_id filters',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['sent', 'failed', 'pending'],
          description: 'Filter by notification status'
        },
        task_id: {
          type: 'string',
          description: 'Filter by associated task ID'
        },
        limit: {
          type: 'number',
          description: 'Maximum notifications to return (default: 100)',
          default: 100
        }
      }
    }
  },
  {
    name: 'get_email_notification',
    description: 'Get details of a specific email notification by ID',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Email notification ID'
        }
      },
      required: ['id']
    }
  }
];

module.exports = tools;
