/**
 * Tool definitions for providerHandlers
 * Auto-generated by extract-tool-defs.js
 */
// NOTE: Individual host tools (add_ollama_host, remove_ollama_host, etc.) kept for backward compat (tier 3).
// Prefer unified manage_host tool (tier 2).

const tools = [
  {
    name: 'approve_provider_switch',
    description: 'Approve switching a task from its current provider (e.g., Codex) to an alternative provider (e.g., Claude CLI) after a quota error',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID to approve provider switch for'
        },
        new_provider: {
          type: 'string',
          description: 'Provider to switch to (default: claude-cli)',
          default: 'claude-cli'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'reject_provider_switch',
    description: 'Reject a pending provider switch and mark the task as failed',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID to reject provider switch for'
        },
        reason: {
          type: 'string',
          description: 'Reason for rejection'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'list_providers',
    description: 'List all configured task execution providers with their status and settings',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'configure_provider',
    description: 'Update provider configuration settings',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider ID (e.g., codex, claude-cli)'
        },
        enabled: {
          type: 'boolean',
          description: 'Enable or disable this provider'
        },
        cli_path: {
          type: 'string',
          description: 'Path to CLI executable'
        },
        quota_error_patterns: {
          type: 'array',
          items: { type: 'string' },
          description: 'Patterns that indicate quota/rate limit errors'
        },
        max_concurrent: {
          type: 'number',
          description: 'Maximum concurrent tasks for this provider'
        }
      },
      required: ['provider']
    }
  },
  {
    name: 'provider_stats',
    description: 'Get usage statistics for a provider',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider ID (e.g., codex, claude-cli)'
        },
        days: {
          type: 'number',
          description: 'Number of days to include in stats',
          default: 30
        }
      },
      required: ['provider']
    }
  },
  {
    name: 'set_default_provider',
    description: 'Set the default provider for new tasks',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider ID to set as default (e.g., codex, claude-cli)'
        }
      },
      required: ['provider']
    }
  },
  {
    name: 'configure_fallback_chain',
    description: 'Configure the provider fallback chain for a given provider. When a provider fails, tasks are retried using providers in this order.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'The provider to configure fallback chain for (e.g., codex, claude-cli, anthropic)'
        },
        chain: {
          type: 'string',
          description: 'Comma-separated list of fallback providers in order (e.g., "claude-cli,anthropic,ollama") or JSON array'
        }
      },
      required: ['provider', 'chain']
    }
  },
  {
    name: 'detect_provider_degradation',
    description: 'Detect providers experiencing performance degradation (high failure rates in the last 24 hours).',
    inputSchema: {
      type: 'object',
      properties: {
        threshold: {
          type: 'number',
          description: 'Failure rate threshold (0-1) to flag degradation (default: 0.3)'
        }
      }
    }
  },
  {
    name: 'start_dashboard',
    description: 'Start the web dashboard for task monitoring and management. Opens browser automatically.',
    inputSchema: {
      type: 'object',
      properties: {
        port: {
          type: 'number',
          description: 'Port number for dashboard server (default: 3456)'
        },
        open_browser: {
          type: 'boolean',
          description: 'Whether to open browser automatically (default: true)',
          default: true
        }
      }
    }
  },
  {
    name: 'stop_dashboard',
    description: 'Stop the web dashboard server',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'list_ollama_models',
    description: 'List all available models from the configured Ollama instance. Shows model names, sizes, and details.',
    inputSchema: {
      type: 'object',
      properties: {
        host: {
          type: 'string',
          description: 'Override Ollama host URL (defaults to configured ollama_host)'
        }
      }
    }
  },
  {
    name: 'check_ollama_health',
    description: 'Check if Ollama is reachable and healthy. Shows connection status and triggers automatic fallback to cloud providers if unavailable.',
    inputSchema: {
      type: 'object',
      properties: {
        force_check: {
          type: 'boolean',
          description: 'Force a fresh health check, ignoring cache (default: true)'
        }
      }
    }
  },
  {
    name: 'add_ollama_host',
    description: 'Register a new Ollama host for load balancing. Multiple hosts can share the task load. Default memory limit is 8GB to prevent OOM crashes.',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'Unique identifier for the host (e.g., "local-4060", "remote-3090"). Auto-generated from URL if not provided.'
        },
        name: {
          type: 'string',
          description: 'Human-readable display name'
        },
        url: {
          type: 'string',
          description: 'Ollama API URL (e.g., "http://192.168.1.100:11434")'
        },
        memory_limit_gb: {
          type: 'number',
          description: 'Maximum memory for models in GB. Default is 8GB. Set based on available RAM minus system overhead.'
        },
        gpu_metrics_port: {
          type: 'number',
          description: 'Port of the gpu-metrics-server.js companion script on the remote host (default 9394). Enables real-time GPU metrics on the dashboard.'
        }
      },
      required: ['name', 'url']
    }
  },
  {
    name: 'remove_ollama_host',
    description: 'Remove an Ollama host from the load balancing pool.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to remove'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'cleanup_null_id_hosts',
    description: 'Remove all Ollama hosts with null or empty IDs from the database. Use this to fix database corruption from hosts added without explicit IDs.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'list_ollama_hosts',
    description: 'List all Ollama hosts with their status, load, and available models.',
    inputSchema: {
      type: 'object',
      properties: {
        enabled_only: {
          type: 'boolean',
          description: 'Only show enabled hosts (default: false)'
        }
      }
    }
  },
  {
    name: 'enable_ollama_host',
    description: 'Enable a disabled Ollama host to participate in load balancing.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to enable'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'disable_ollama_host',
    description: 'Disable an Ollama host without removing it. Disabled hosts do not receive tasks.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to disable'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'recover_ollama_host',
    description: 'Manually recover a downed Ollama host. Resets failure count and triggers health check.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to recover'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'refresh_host_models',
    description: 'Force refresh the model list for an Ollama host or all hosts.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to refresh (omit for all hosts)'
        }
      }
    }
  },
  {
    name: 'set_host_memory_limit',
    description: 'Set memory limit for an Ollama host (OOM protection). Models larger than this limit will not be loaded on this host. Set to 0 or null to disable limit.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to configure'
        },
        memory_limit_mb: {
          type: 'number',
          description: 'Memory limit in MB (e.g., 18000 for 18GB). Set to 0 to disable limit.'
        }
      },
      required: ['host_id', 'memory_limit_mb']
    }
  },
  {
    name: 'set_host_max_concurrent',
    description: 'Set maximum concurrent tasks for an Ollama host. When this limit is reached, new tasks will wait or be routed to other hosts. Set to 0 to disable limit (unlimited).',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to configure'
        },
        max_concurrent: {
          type: 'number',
          description: 'Maximum concurrent tasks (e.g., 2). Set to 0 for unlimited.'
        }
      },
      required: ['host_id', 'max_concurrent']
    }
  },
  {
    name: 'get_host_capacity',
    description: 'Get current capacity status for all Ollama hosts. Shows running tasks, max limits, and available capacity.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'configure_memory_protection',
    description: 'Configure global memory protection settings to prevent OOM errors from loading models too large for hosts.',
    inputSchema: {
      type: 'object',
      properties: {
        default_memory_limit_mb: {
          type: 'number',
          description: 'Default memory limit in MB for hosts without explicit limits (0 = no default)'
        },
        strict_mode: {
          type: 'boolean',
          description: 'Enable strict mode: reject all models with unknown sizes'
        },
        reject_unknown_sizes: {
          type: 'boolean',
          description: 'Reject models that have unknown/unreported sizes'
        }
      }
    }
  },
  {
    name: 'get_memory_protection_status',
    description: 'View current memory protection settings and host memory configurations.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'get_discovery_status',
    description: 'Get the status of Ollama LAN discovery (mDNS). Shows if advertising and browsing are active, and lists discovered hosts.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'set_discovery_config',
    description: 'Configure Ollama LAN discovery settings. Enable/disable discovery, advertising, or browsing.',
    inputSchema: {
      type: 'object',
      properties: {
        discovery_enabled: {
          type: 'boolean',
          description: 'Enable or disable discovery entirely'
        },
        discovery_advertise: {
          type: 'boolean',
          description: 'Enable or disable advertising local Ollama'
        },
        discovery_browse: {
          type: 'boolean',
          description: 'Enable or disable browsing for other hosts'
        }
      }
    }
  },
  {
    name: 'scan_network_for_ollama',
    description: 'Scan the local network for Ollama instances. Finds any machine running Ollama on the specified port (default 11434) and auto-adds them to the host pool.',
    inputSchema: {
      type: 'object',
      properties: {
        port: {
          type: 'number',
          description: 'Port to scan for Ollama (default: 11434)'
        },
        auto_add: {
          type: 'boolean',
          description: 'Automatically add discovered hosts to the pool (default: true)'
        },
        subnet: {
          type: 'string',
          description: 'Specific subnet to scan (e.g., "192.168.1"). If not specified, scans all local subnets.'
        }
      }
    }
  },
  {
    name: 'configure_auto_scan',
    description: 'Configure automatic periodic network scanning. When enabled, TORQUE scans for Ollama hosts every N minutes and auto-detects network changes (e.g., switching from hotspot to home WiFi).',
    inputSchema: {
      type: 'object',
      properties: {
        enabled: {
          type: 'boolean',
          description: 'Enable or disable auto-scan. Omit to query current status.'
        },
        interval_minutes: {
          type: 'number',
          description: 'Scan interval in minutes (default: 5)'
        }
      }
    }
  },
  {
    name: 'get_llm_tuning',
    description: 'View current LLM tuning parameters for Ollama and Aider. Shows temperature, context size, and other generation settings.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'set_llm_tuning',
    description: 'Adjust LLM tuning parameters. Use preset for quick configuration, or individual params for fine-tuning.',
    inputSchema: {
      type: 'object',
      properties: {
        preset: {
          type: 'string',
          enum: ['code', 'precise', 'creative', 'balanced', 'fast'],
          description: 'Apply a preset: code (default), precise (deterministic), creative (varied), balanced (mirostat), fast (low context)'
        },
        temperature: {
          type: 'number',
          description: 'Generation temperature (0.1-1.0). Lower = more deterministic. Recommended: 0.2-0.4 for code, 0.7 for creative.'
        },
        num_ctx: {
          type: 'number',
          description: 'Context window size (1024-32768). Higher = more context but slower/more VRAM.'
        },
        top_p: {
          type: 'number',
          description: 'Nucleus sampling (0.1-1.0). Lower = more focused. Default: 0.9'
        },
        top_k: {
          type: 'number',
          description: 'Top-k sampling (1-100). Limits vocabulary considered. Default: 40'
        },
        repeat_penalty: {
          type: 'number',
          description: 'Repetition penalty (1.0-1.5). Higher = less repetition. Default: 1.1'
        },
        num_predict: {
          type: 'number',
          description: 'Max tokens to generate (-1 for unlimited). Default: -1'
        },
        mirostat: {
          type: 'number',
          enum: [0, 1, 2],
          description: 'Mirostat mode: 0=off, 1=v1, 2=v2 (recommended for consistent quality)'
        },
        mirostat_tau: {
          type: 'number',
          description: 'Mirostat target entropy (1.0-10.0). Higher = more diverse. Default: 5.0'
        },
        mirostat_eta: {
          type: 'number',
          description: 'Mirostat learning rate (0.01-1.0). Default: 0.1'
        },
        seed: {
          type: 'number',
          description: 'Random seed for reproducibility. -1 for random.'
        },
        aider_edit_format: {
          type: 'string',
          enum: ['whole', 'diff', 'udiff'],
          description: 'Aider edit format. whole=reliable, diff=efficient for large files'
        },
        aider_map_tokens: {
          type: 'number',
          description: 'Aider repo context tokens (512-4096). Higher = better repo understanding.'
        },
        aider_auto_commits: {
          type: 'boolean',
          description: 'Whether Aider should auto-commit changes'
        },
        aider_subtree_only: {
          type: 'boolean',
          description: 'Only scan current directory (faster for large repos). Default: true'
        },
        host: {
          type: 'string',
          description: 'Ollama host URL (e.g., http://localhost:11434 or http://172.26.176.1:11434 for WSL2)'
        },
        auto_start_enabled: {
          type: 'boolean',
          description: 'Enable auto-starting Ollama when health check fails. Default: false'
        },
        auto_start_timeout_ms: {
          type: 'number',
          description: 'Timeout in milliseconds to wait for Ollama to start. Default: 15000'
        },
        binary_path: {
          type: 'string',
          description: 'Path to Ollama binary (auto-detected if not set)'
        },
        auto_detect_wsl_host: {
          type: 'boolean',
          description: 'Auto-detect Windows host IP for WSL2 environments. Default: true'
        }
      }
    }
  },
  {
    name: 'apply_llm_preset',
    description: 'Quick-apply a tuning preset. Presets: code (low temp, high context), precise (very low temp), creative (high temp), balanced (mirostat), fast (low context)',
    inputSchema: {
      type: 'object',
      properties: {
        preset: {
          type: 'string',
          enum: ['code', 'precise', 'creative', 'balanced', 'fast'],
          description: 'Preset name to apply'
        }
      },
      required: ['preset']
    }
  },
  {
    name: 'list_llm_presets',
    description: 'List all available LLM tuning presets and their settings',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'get_model_settings',
    description: 'View tuning settings for a specific model or all models. Model-specific settings override global defaults.',
    inputSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          description: 'Model name (e.g., codellama, llama3). Omit to see all models.'
        }
      }
    }
  },
  {
    name: 'set_model_settings',
    description: 'Set tuning parameters for a specific model. These override global defaults when that model is used.',
    inputSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          description: 'Model name (e.g., codellama, llama3, mistral)'
        },
        temperature: {
          type: 'number',
          description: 'Model-specific temperature (0.1-1.0)'
        },
        num_ctx: {
          type: 'number',
          description: 'Model-specific context window'
        },
        top_p: {
          type: 'number',
          description: 'Model-specific top_p (0.1-1.0)'
        },
        top_k: {
          type: 'number',
          description: 'Model-specific top_k (1-100)'
        },
        repeat_penalty: {
          type: 'number',
          description: 'Model-specific repeat penalty (1.0-2.0)'
        },
        mirostat: {
          type: 'number',
          description: 'Model-specific mirostat mode (0, 1, or 2)'
        },
        description: {
          type: 'string',
          description: 'Description of what this model is best for'
        }
      },
      required: ['model']
    }
  },
  {
    name: 'get_model_prompts',
    description: 'View system prompts configured for each model. Models use these as their base instructions.',
    inputSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          description: 'Model name to view prompt for. Omit to see all.'
        }
      }
    }
  },
  {
    name: 'set_model_prompt',
    description: 'Set a custom system prompt for a specific model.',
    inputSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          description: 'Model name (e.g., codellama, llama3)'
        },
        prompt: {
          type: 'string',
          description: 'System prompt text for this model'
        }
      },
      required: ['model', 'prompt']
    }
  },
  {
    name: 'get_instruction_templates',
    description: 'View instruction templates that wrap task descriptions with standardized safeguard rules. Templates prevent LLMs from creating stubs, empty files, or breaking builds.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider to view template for (aider-ollama, claude-cli, codex). Omit to see all.'
        }
      }
    }
  },
  {
    name: 'set_instruction_template',
    description: 'Set a custom instruction template for a provider. Templates wrap task descriptions with standardized instructions and safeguards.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider (aider-ollama, claude-cli, codex)'
        },
        model: {
          type: 'string',
          description: 'Optional: model-specific template (e.g., phi3, codestral)'
        },
        template: {
          type: 'string',
          description: 'Template text. Use {TASK_DESCRIPTION} for the task, {FILES} for files, {PROJECT} for project name.'
        }
      },
      required: ['provider', 'template']
    }
  },
  {
    name: 'toggle_instruction_wrapping',
    description: 'Enable or disable instruction template wrapping for all tasks.',
    inputSchema: {
      type: 'object',
      properties: {
        enabled: {
          type: 'boolean',
          description: 'Whether to wrap task descriptions with instruction templates'
        }
      },
      required: ['enabled']
    }
  },
  {
    name: 'get_hardware_tuning',
    description: 'View hardware optimization settings (GPU layers, CPU threads, keep-alive).',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'set_hardware_tuning',
    description: 'Configure hardware optimization for Ollama.',
    inputSchema: {
      type: 'object',
      properties: {
        num_gpu: {
          type: 'number',
          description: 'GPU layers to offload (-1=auto, 0=CPU only, N=specific layers). For RTX 4060 8GB, try 35-40.'
        },
        num_thread: {
          type: 'number',
          description: 'CPU threads (0=auto-detect). Usually best left at 0.'
        },
        keep_alive: {
          type: 'string',
          description: 'How long to keep model loaded (e.g., "5m", "1h", "0" to unload immediately)'
        }
      }
    }
  },
  {
    name: 'get_auto_tuning',
    description: 'View auto-tuning rules. Auto-tuning analyzes task descriptions and automatically adjusts temperature/settings.',
    inputSchema: {
      type: 'object',
      properties: {}
    }
  },
  {
    name: 'set_auto_tuning',
    description: 'Enable/disable auto-tuning or modify rules.',
    inputSchema: {
      type: 'object',
      properties: {
        enabled: {
          type: 'boolean',
          description: 'Enable or disable auto-tuning'
        },
        rule: {
          type: 'string',
          description: 'Rule name to modify (code_generation, documentation, creative, precise, debugging)'
        },
        patterns: {
          type: 'array',
          items: { type: 'string' },
          description: 'Keywords that trigger this rule'
        },
        tuning: {
          type: 'object',
          description: 'Tuning overrides when rule matches',
          properties: {
            temperature: { type: 'number' },
            top_k: { type: 'number' },
            mirostat: { type: 'number' }
          }
        }
      }
    }
  },
  {
    name: 'run_benchmark',
    description: 'Run performance benchmark on Ollama host(s) to find optimal configuration. Tests throughput, GPU layer optimization, and context window sizes.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'TORQUE host ID to benchmark (e.g., "desktop-17"). Uses first healthy host if not specified.'
        },
        host_url: {
          type: 'string',
          description: 'Direct Ollama URL to benchmark (e.g., "http://192.168.1.100:11434"). Overrides host_id.'
        },
        model: {
          type: 'string',
          description: 'Specific model to benchmark. If not specified, benchmarks all models on the host.'
        },
        test_type: {
          type: 'string',
          enum: ['basic', 'gpu', 'context', 'full'],
          description: 'Type of benchmark: basic (model throughput), gpu (layer optimization), context (window sizes), full (all tests). Default: basic'
        },
        gpu_layers: {
          type: 'array',
          items: { type: 'number' },
          description: 'Custom GPU layer values to test (e.g., [-1, 50, 70, 99]). Only used with gpu/full test_type.'
        },
        context_sizes: {
          type: 'array',
          items: { type: 'number' },
          description: 'Custom context window sizes to test (e.g., [4096, 8192, 16384]). Only used with context/full test_type.'
        }
      }
    }
  },
  {
    name: 'get_host_settings',
    description: 'Get optimization settings for a specific Ollama host. Shows merged global defaults + host-specific overrides.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to get settings for (e.g., "desktop-17")'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'set_host_settings',
    description: 'Set optimization settings for a specific Ollama host. Use after running benchmarks to apply optimal configuration.',
    inputSchema: {
      type: 'object',
      properties: {
        host_id: {
          type: 'string',
          description: 'Host ID to configure (e.g., "desktop-17")'
        },
        num_gpu: {
          type: 'number',
          description: 'GPU layers to offload (-1=auto, 0=CPU, N=specific layers). RTX 3090/4090 24GB: try 70 for 32B models.'
        },
        num_ctx: {
          type: 'number',
          description: 'Context window size. Larger = more memory. 8192 is balanced, 16384+ needs more VRAM.'
        },
        num_thread: {
          type: 'number',
          description: 'CPU threads (0=auto). Usually best left at 0.'
        },
        keep_alive: {
          type: 'string',
          description: 'How long to keep model loaded (e.g., "5m", "30m", "1h")'
        },
        temperature: {
          type: 'number',
          description: 'Generation temperature (0.0-1.0)'
        },
        top_k: {
          type: 'number',
          description: 'Top-K sampling'
        },
        top_p: {
          type: 'number',
          description: 'Top-P (nucleus) sampling'
        },
        max_concurrent: {
          type: 'number',
          description: 'Max concurrent tasks on this host (0=unlimited, 1=single task at a time). Set to 1 for hosts with limited GPU to prevent contention.'
        },
        gpu_metrics_port: {
          type: 'number',
          description: 'Port of the gpu-metrics-server.js companion script on the remote host (default 9394). Enables real-time GPU metrics on the dashboard.'
        }
      },
      required: ['host_id']
    }
  },
  {
    name: 'get_format_success_rates',
    description: 'Show per-model hashline format success rates (hashline vs hashline-lite). Shows success/failure counts, rates, average durations, and auto-routing recommendations.',
    inputSchema: {
      type: 'object',
      properties: {
        model: {
          type: 'string',
          description: 'Filter to a specific model (e.g. "qwen3:8b"). Omit for all models.'
        }
      },
      required: []
    }
  },
  {
    name: 'get_provider_health_trends',
    description: 'Get provider health trends from persistent health history. Shows whether each provider is improving, stable, or degrading over time.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Specific provider name (optional — omit for all providers)'
        },
        days: {
          type: 'number',
          description: 'Number of days of history to analyze (default: 30)'
        }
      }
    }
  },
  {
    name: 'get_model_leaderboard',
    description: 'Get model performance leaderboard ranked by success rate. Shows which models perform best for specific task types and languages. Data comes from actual task outcomes (currently ollama providers only).',
    inputSchema: {
      type: 'object',
      properties: {
        task_type: { type: 'string', description: 'Filter by task type', enum: ['code_gen', 'testing', 'refactoring', 'reasoning', 'docs'] },
        language: { type: 'string', description: 'Filter by language (javascript, typescript, python, etc.)' },
        days: { type: 'number', description: 'Number of days of history (default: 30)' },
        limit: { type: 'number', description: 'Max models to return (default: 20)' }
      }
    }
  },
  {
    name: 'get_provider_percentiles',
    description: 'Get duration percentile metrics (P50/P75/P90/P95/P99) for a provider. Useful for SLA monitoring and performance analysis.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: {
          type: 'string',
          description: 'Provider ID (e.g., codex, ollama, deepinfra)'
        },
        days: {
          type: 'number',
          description: 'Number of days of history to analyze (default: 7)',
          default: 7
        }
      },
      required: ['provider']
    }
  },
  // ── Unified tuning management tool (Phase 3.2 consolidation) ──
  {
    name: 'manage_tuning',
    description: 'Unified LLM tuning management. Consolidates 16 individual tuning tools into one. Use action param to select operation.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['get_llm', 'set_llm', 'apply_preset', 'list_presets', 'get_model', 'set_model', 'get_prompts', 'set_prompt', 'get_templates', 'set_template', 'toggle_wrapping', 'get_hardware', 'set_hardware', 'get_auto', 'set_auto', 'benchmark'],
          description: 'Operation: get_llm/set_llm (global tuning), apply_preset/list_presets (quick configs), get_model/set_model (per-model), get_prompts/set_prompt (system prompts), get_templates/set_template (instruction wrapping), toggle_wrapping, get_hardware/set_hardware (GPU/CPU), get_auto/set_auto (auto-tuning rules), benchmark (perf testing)'
        },
        // LLM tuning params
        preset: { type: 'string', enum: ['code', 'precise', 'creative', 'balanced', 'fast'], description: 'Tuning preset name' },
        temperature: { type: 'number', description: 'Generation temperature (0.1-1.0)' },
        num_ctx: { type: 'number', description: 'Context window size' },
        top_p: { type: 'number', description: 'Nucleus sampling (0.1-1.0)' },
        top_k: { type: 'number', description: 'Top-k sampling (1-100)' },
        repeat_penalty: { type: 'number', description: 'Repetition penalty (1.0-1.5)' },
        num_predict: { type: 'number', description: 'Max tokens (-1=unlimited)' },
        mirostat: { type: 'number', enum: [0, 1, 2], description: 'Mirostat mode (0=off, 2=recommended)' },
        mirostat_tau: { type: 'number', description: 'Mirostat target entropy' },
        mirostat_eta: { type: 'number', description: 'Mirostat learning rate' },
        seed: { type: 'number', description: 'Random seed (-1=random)' },
        // Aider params
        aider_edit_format: { type: 'string', enum: ['whole', 'diff', 'udiff'], description: 'Aider edit format' },
        aider_map_tokens: { type: 'number', description: 'Aider repo context tokens' },
        aider_auto_commits: { type: 'boolean', description: 'Aider auto-commit' },
        aider_subtree_only: { type: 'boolean', description: 'Aider subtree-only scan' },
        // Ollama host params
        host: { type: 'string', description: 'Ollama host URL' },
        auto_start_enabled: { type: 'boolean', description: 'Auto-start Ollama' },
        auto_start_timeout_ms: { type: 'number', description: 'Auto-start timeout' },
        binary_path: { type: 'string', description: 'Ollama binary path' },
        auto_detect_wsl_host: { type: 'boolean', description: 'Auto-detect WSL host' },
        // Model params
        model: { type: 'string', description: 'Model name' },
        description: { type: 'string', description: 'Model description' },
        // Prompt params
        prompt: { type: 'string', description: 'System prompt text' },
        // Template params
        provider: { type: 'string', description: 'Provider name' },
        template: { type: 'string', description: 'Instruction template text' },
        // Toggle/auto params
        enabled: { type: 'boolean', description: 'Enable/disable' },
        rule: { type: 'string', description: 'Auto-tuning rule name' },
        patterns: { type: 'array', items: { type: 'string' }, description: 'Auto-tuning trigger patterns' },
        tuning: { type: 'object', description: 'Auto-tuning overrides', properties: { temperature: { type: 'number' }, top_k: { type: 'number' }, mirostat: { type: 'number' } } },
        // Hardware params
        num_gpu: { type: 'number', description: 'GPU layers (-1=auto)' },
        num_thread: { type: 'number', description: 'CPU threads (0=auto)' },
        keep_alive: { type: 'string', description: 'Model keep-alive duration' },
        // Benchmark params
        host_id: { type: 'string', description: 'Host ID to benchmark' },
        host_url: { type: 'string', description: 'Direct URL to benchmark' },
        test_type: { type: 'string', enum: ['basic', 'gpu', 'context', 'full'], description: 'Benchmark type' },
        gpu_layers: { type: 'array', items: { type: 'number' }, description: 'GPU layer values to test' },
        context_sizes: { type: 'array', items: { type: 'number' }, description: 'Context sizes to test' },
      },
      required: ['action']
    }
  },
  // ── Unified host management tool (Phase 3.2 consolidation) ──
  {
    name: 'manage_host',
    description: 'Unified Ollama host management. Replaces individual add/remove/enable/disable/recover/refresh/config tools. Use action parameter to select operation.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['list', 'add', 'remove', 'enable', 'disable', 'recover', 'refresh_models', 'set_memory_limit', 'set_max_concurrent', 'get_capacity', 'health', 'cleanup_null_ids'],
          description: 'Operation to perform. list=show all hosts, add=register new host, remove=delete host, enable/disable=toggle host, recover=reset downed host, refresh_models=fetch model list, set_memory_limit/set_max_concurrent=configure host, get_capacity=show capacity, health=check connectivity, cleanup_null_ids=fix DB corruption.'
        },
        host_id: {
          type: 'string',
          description: 'Host ID (required for remove/enable/disable/recover/set_memory_limit/set_max_concurrent; optional for refresh_models)'
        },
        name: {
          type: 'string',
          description: 'Human-readable display name (required for add)'
        },
        url: {
          type: 'string',
          description: 'Ollama API URL (required for add, e.g., "http://192.168.1.100:11434")'
        },
        id: {
          type: 'string',
          description: 'Custom host ID (optional for add, auto-generated from URL if not provided)'
        },
        memory_limit_gb: {
          type: 'number',
          description: 'Memory limit in GB for add (default 8GB)'
        },
        memory_limit_mb: {
          type: 'number',
          description: 'Memory limit in MB for set_memory_limit. Set to 0 to disable.'
        },
        max_concurrent: {
          type: 'number',
          description: 'Max concurrent tasks for set_max_concurrent. Set to 0 for unlimited.'
        },
        gpu_metrics_port: {
          type: 'number',
          description: 'GPU metrics port for add (default 9394)'
        },
        enabled_only: {
          type: 'boolean',
          description: 'Only show enabled hosts for list (default: false)'
        },
        force_fresh: {
          type: 'boolean',
          description: 'Force fresh health check for health action (default: true)'
        }
      },
      required: ['action']
    }
  }
];

module.exports = tools;
