/**
 * Tool definitions for taskHandlers
 * Auto-generated by extract-tool-defs.js
 */

module.exports = [
  {
    "name": "configure",
    "description": "Get or set server configuration",
    "inputSchema": {
      "type": "object",
      "properties": {
        "max_concurrent": {
          "type": "number",
          "description": "Maximum concurrent provider instances (1-20)",
          "minimum": 1
        },
        "default_timeout": {
          "type": "number",
          "description": "Default timeout in minutes for new tasks"
        }
      },
      "required": []
    }
  },
  {
    "name": "share_context",
    "description": "Share context information with a task (writes to a context file the task can reference)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to share context with"
        },
        "context_type": {
          "type": "string",
          "enum": [
            "conversation",
            "codebase",
            "requirements",
            "custom"
          ],
          "description": "Type of context being shared"
        },
        "content": {
          "type": "string",
          "description": "The context content to share"
        }
      },
      "required": [
        "task_id",
        "content"
      ]
    }
  },
  {
    "name": "sync_files",
    "description": "Sync files between Claude workspace and task workspace",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID"
        },
        "direction": {
          "type": "string",
          "enum": [
            "push",
            "pull"
          ],
          "description": "push = send files to task, pull = get files from task"
        },
        "files": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of file paths to sync"
        }
      },
      "required": [
        "task_id",
        "direction",
        "files"
      ]
    }
  },
  {
    "name": "save_template",
    "description": "Save a reusable task template for common operations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Template name (e.g., \"unit-tests\", \"refactor\")"
        },
        "description": {
          "type": "string",
          "description": "What this template is for"
        },
        "task_template": {
          "type": "string",
          "description": "Task template with {placeholders} for variable parts"
        },
        "default_timeout": {
          "type": "number",
          "description": "Default timeout for tasks using this template"
        },
        "default_priority": {
          "type": "number",
          "description": "Default priority for tasks using this template"
        }
      },
      "required": [
        "name",
        "task_template"
      ]
    }
  },
  {
    "name": "list_templates",
    "description": "List all saved task templates",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "use_template",
    "description": "Create a task from a saved template",
    "inputSchema": {
      "type": "object",
      "properties": {
        "template_name": {
          "type": "string",
          "description": "Name of the template to use"
        },
        "variables": {
          "type": "object",
          "description": "Variables to substitute in the template (key-value pairs)"
        },
        "working_directory": {
          "type": "string",
          "description": "Working directory for the task"
        },
        "priority": {
          "type": "number",
          "description": "Override default priority"
        }
      },
      "required": [
        "template_name"
      ]
    }
  },
  {
    "name": "get_analytics",
    "description": "Get analytics and statistics about TORQUE task history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "include_events": {
          "type": "boolean",
          "description": "Include recent event log",
          "default": false
        }
      },
      "required": []
    }
  },
  {
    "name": "create_pipeline",
    "description": "Create a task pipeline - a sequence of tasks that run in order, with outputs passing to subsequent steps",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Pipeline name"
        },
        "description": {
          "type": "string",
          "description": "What this pipeline does"
        },
        "working_directory": {
          "type": "string",
          "description": "Working directory for pipeline tasks"
        },
        "steps": {
          "type": "array",
          "description": "Pipeline steps to add",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Step name"
              },
              "task_template": {
                "type": "string",
                "description": "Task description (can use ${prev_output} for previous step output)"
              },
              "condition": {
                "type": "string",
                "description": "Condition to run step: \"always\", \"on_success\", \"on_failure\"",
                "enum": ["always", "on_success", "on_failure"]
              },
              "timeout_minutes": {
                "type": "number",
                "description": "Timeout for this step",
                "minimum": 1,
                "maximum": 60
              }
            },
            "required": [
              "name",
              "task_template"
            ]
          }
        }
      },
      "required": [
        "name",
        "steps"
      ]
    }
  },
  {
    "name": "run_pipeline",
    "description": "Start executing a pipeline",
    "inputSchema": {
      "type": "object",
      "properties": {
        "pipeline_id": {
          "type": "string",
          "description": "Pipeline ID to run"
        },
        "variables": {
          "type": "object",
          "description": "Variables to pass to the pipeline steps"
        }
      },
      "required": [
        "pipeline_id"
      ]
    }
  },
  {
    "name": "get_pipeline_status",
    "description": "Get the status of a pipeline and its steps",
    "inputSchema": {
      "type": "object",
      "properties": {
        "pipeline_id": {
          "type": "string",
          "description": "Pipeline ID"
        }
      },
      "required": [
        "pipeline_id"
      ]
    }
  },
  {
    "name": "list_pipelines",
    "description": "List all pipelines",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "running",
            "completed",
            "failed"
          ],
          "description": "Filter by status"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number to return"
        }
      },
      "required": []
    }
  },
  {
    "name": "preview_diff",
    "description": "Preview the file changes made by a completed task before committing",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to preview changes for"
        },
        "working_directory": {
          "type": "string",
          "description": "Working directory (defaults to task working directory)"
        }
      },
      "required": [
        "task_id"
      ]
    }
  },
  {
    "name": "list_commits",
    "description": "List tasks that have been committed (rollback candidates)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "working_directory": {
          "type": "string",
          "description": "Filter by working directory"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number to return",
          "default": 10
        }
      },
      "required": []
    }
  },
  {
    "name": "list_tags",
    "description": "List all tags with usage counts and statistics",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "health_check",
    "description": "Run a health check on TORQUE infrastructure and record the results",
    "inputSchema": {
      "type": "object",
      "properties": {
        "check_type": {
          "type": "string",
          "enum": [
            "connectivity",
            "api",
            "performance",
            "full"
          ],
          "description": "Type of health check to run (default: connectivity)"
        }
      },
      "required": []
    }
  },
  {
    "name": "health_status",
    "description": "Get health monitoring status and history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "include_history": {
          "type": "boolean",
          "description": "Include recent health check history",
          "default": false
        },
        "limit": {
          "type": "number",
          "description": "Number of history entries to return",
          "default": 10
        }
      },
      "required": []
    }
  },
  {
    "name": "list_scheduled",
    "description": "List all scheduled tasks",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "active",
            "paused",
            "completed"
          ],
          "description": "Filter by status"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number to return",
          "default": 20
        }
      },
      "required": []
    }
  },
  {
    "name": "cancel_scheduled",
    "description": "Cancel/delete a scheduled task",
    "inputSchema": {
      "type": "object",
      "properties": {
        "schedule_id": {
          "type": "string",
          "description": "ID of the scheduled task to cancel"
        }
      },
      "required": [
        "schedule_id"
      ]
    }
  },
  {
    "name": "pause_scheduled",
    "description": "Pause or resume a scheduled task",
    "inputSchema": {
      "type": "object",
      "properties": {
        "schedule_id": {
          "type": "string",
          "description": "ID of the scheduled task"
        },
        "action": {
          "type": "string",
          "enum": [
            "pause",
            "resume"
          ],
          "description": "Action to take"
        }
      },
      "required": [
        "schedule_id",
        "action"
      ]
    }
  },
  {
    "name": "batch_retry",
    "description": "Retry all failed tasks matching filters",
    "inputSchema": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Retry failed tasks with any of these tags"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number to retry",
          "default": 10
        },
        "include_cancelled": {
          "type": "boolean",
          "description": "Also retry cancelled tasks",
          "default": false
        }
      },
      "required": []
    }
  },
  {
    "name": "batch_tag",
    "description": "Add tags to multiple tasks at once",
    "inputSchema": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Tags to add"
        },
        "filter_status": {
          "type": "string",
          "enum": [
            "pending",
            "queued",
            "running",
            "completed",
            "failed",
            "cancelled"
          ],
          "description": "Apply to tasks with this status"
        },
        "filter_tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Apply to tasks with any of these existing tags"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number of tasks to tag",
          "default": 50
        }
      },
      "required": [
        "tags"
      ]
    }
  },
  {
    "name": "search_outputs",
    "description": "Search across all task outputs for a pattern",
    "inputSchema": {
      "type": "object",
      "properties": {
        "pattern": {
          "type": "string",
          "description": "Text pattern to search for"
        },
        "status": {
          "type": "string",
          "enum": [
            "completed",
            "failed"
          ],
          "description": "Search only tasks with this status"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Search only tasks with these tags"
        },
        "since": {
          "type": "string",
          "description": "Search tasks created after this ISO timestamp"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number of results",
          "default": 20
        }
      },
      "required": [
        "pattern"
      ]
    }
  },
  {
    "name": "output_stats",
    "description": "Get statistics about task outputs",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "export_data",
    "description": "Export tasks, templates, pipelines, and scheduled tasks as JSON for backup or sharing",
    "inputSchema": {
      "type": "object",
      "properties": {
        "include": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tasks",
              "templates",
              "pipelines",
              "scheduled_tasks",
              "config"
            ]
          },
          "description": "Data types to include (default: all)"
        },
        "task_status": {
          "type": "string",
          "enum": [
            "pending",
            "queued",
            "running",
            "completed",
            "failed",
            "cancelled"
          ],
          "description": "Filter tasks by status"
        },
        "task_limit": {
          "type": "number",
          "description": "Maximum number of tasks to export",
          "default": 100
        },
        "output_file": {
          "type": "string",
          "description": "Optional file path to save export (otherwise returns JSON)"
        }
      },
      "required": []
    }
  },
  {
    "name": "import_data",
    "description": "Import tasks, templates, pipelines from a JSON export file or string",
    "inputSchema": {
      "type": "object",
      "properties": {
        "file_path": {
          "type": "string",
          "description": "Path to JSON file to import"
        },
        "json_data": {
          "type": "string",
          "description": "JSON string to import (alternative to file_path)"
        },
        "skip_existing": {
          "type": "boolean",
          "description": "Skip items that already exist (default: true)",
          "default": true
        }
      },
      "required": []
    }
  },
  {
    "name": "list_archived",
    "description": "List archived tasks",
    "inputSchema": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "number",
          "description": "Maximum number to return",
          "default": 20
        },
        "offset": {
          "type": "number",
          "description": "Number of items to skip",
          "default": 0
        }
      },
      "required": []
    }
  },
  {
    "name": "get_archive_stats",
    "description": "Get statistics about archived tasks",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "record_usage",
    "description": "Record token usage and cost for a task",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to record usage for"
        },
        "input_tokens": {
          "type": "number",
          "description": "Number of input tokens used"
        },
        "output_tokens": {
          "type": "number",
          "description": "Number of output tokens generated"
        },
        "model": {
          "type": "string",
          "description": "Model used (e.g., \"codex\", \"gpt-4\")",
          "default": "codex"
        }
      },
      "required": [
        "task_id",
        "input_tokens",
        "output_tokens"
      ]
    }
  },
  {
    "name": "cost_summary",
    "description": "Get token usage and cost summary with optional filtering. By default shows only costs from the current project.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "period": {
          "type": "string",
          "enum": [
            "hour",
            "day",
            "week",
            "month"
          ],
          "description": "Group costs by time period"
        },
        "limit": {
          "type": "number",
          "description": "Number of periods to return (for period grouping)",
          "default": 30
        },
        "since": {
          "type": "string",
          "description": "Filter usage since this ISO timestamp"
        },
        "model": {
          "type": "string",
          "description": "Filter by model"
        },
        "project": {
          "type": "string",
          "description": "Filter by project name (defaults to current project)"
        },
        "all_projects": {
          "type": "boolean",
          "description": "Show costs from all projects",
          "default": false
        }
      },
      "required": []
    }
  },
  {
    "name": "estimate_cost",
    "description": "Estimate token usage and cost for a task description before running",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_description": {
          "type": "string",
          "description": "Task description to estimate"
        },
        "model": {
          "type": "string",
          "description": "Model to use for estimation",
          "default": "codex"
        }
      },
      "required": [
        "task_description"
      ]
    }
  },
  {
    "name": "list_projects",
    "description": "List all projects that have tasks, with task counts and cost summaries",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "project_stats",
    "description": "Get detailed statistics for a specific project",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Project name to get stats for (defaults to current project)"
        }
      },
      "required": []
    }
  },
  {
    "name": "current_project",
    "description": "Get the current project name based on working directory",
    "inputSchema": {
      "type": "object",
      "properties": {
        "working_directory": {
          "type": "string",
          "description": "Working directory to detect project from (defaults to current directory)"
        }
      },
      "required": []
    }
  },
  {
    "name": "configure_project",
    "description": "Set project-specific configuration (concurrency limits, quotas, defaults)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Project name (defaults to current project)"
        },
        "max_concurrent": {
          "type": "number",
          "description": "Max concurrent tasks for this project (0 = use global limit)",
          "minimum": 0
        },
        "max_daily_cost": {
          "type": "number",
          "description": "Max daily cost in USD (0 = unlimited)"
        },
        "max_daily_tokens": {
          "type": "number",
          "description": "Max daily tokens (0 = unlimited)"
        },
        "default_timeout": {
          "type": "number",
          "description": "Default timeout in minutes for new tasks"
        },
        "default_priority": {
          "type": "number",
          "description": "Default priority for new tasks"
        },
        "auto_approve": {
          "type": "boolean",
          "description": "Default auto-approve setting for new tasks"
        },
        "enabled": {
          "type": "boolean",
          "description": "Enable/disable task submission for this project"
        },
        "build_verification_enabled": {
          "type": "boolean",
          "description": "Enable build verification after LLM task completion. When enabled, runs the build command after each task and marks the task as failed if the build fails."
        },
        "build_command": {
          "type": "string",
          "description": "Build command to run for verification (e.g., \"dotnet build\", \"npm run build\"). If not specified, auto-detects based on project files."
        },
        "build_timeout": {
          "type": "number",
          "description": "Build timeout in seconds (default: 120)"
        },
        "rollback_on_build_failure": {
          "type": "boolean",
          "description": "Automatically rollback changes if build fails (default: true)"
        },
        "test_verification_enabled": {
          "type": "boolean",
          "description": "Enable test verification after successful build. Runs the test command and reports failures."
        },
        "test_command": {
          "type": "string",
          "description": "Test command to run (e.g., \"dotnet test\", \"npm test\"). If not specified, auto-detects based on project files."
        },
        "test_timeout": {
          "type": "number",
          "description": "Test timeout in seconds (default: 300)"
        },
        "rollback_on_test_failure": {
          "type": "boolean",
          "description": "Rollback changes if tests fail (default: false - warns but keeps changes)"
        }
      },
      "required": []
    }
  },
  {
    "name": "get_project_config",
    "description": "Get configuration for a project including effective settings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Project name (defaults to current project)"
        }
      },
      "required": []
    }
  },
  {
    "name": "list_project_configs",
    "description": "List all project configurations",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "validate_import",
    "description": "Validate an import file without creating tasks (dry-run)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "file_path": {
          "type": "string",
          "description": "Path to the import file"
        },
        "content": {
          "type": "string",
          "description": "Inline JSON/YAML content"
        }
      },
      "required": []
    }
  },
  {
    "name": "create_group",
    "description": "Create a task group for organizing related tasks",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Group name"
        },
        "project": {
          "type": "string",
          "description": "Project this group belongs to"
        },
        "description": {
          "type": "string",
          "description": "Group description"
        },
        "default_priority": {
          "type": "number",
          "description": "Default priority for tasks in this group"
        },
        "default_timeout": {
          "type": "number",
          "description": "Default timeout for tasks in this group"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "name": "list_groups",
    "description": "List task groups with their statistics",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Filter by project"
        }
      },
      "required": []
    }
  },
  {
    "name": "group_action",
    "description": "Perform bulk actions on all tasks in a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Group ID"
        },
        "action": {
          "type": "string",
          "enum": [
            "start_all",
            "cancel_all",
            "retry_failed"
          ],
          "description": "Action to perform on group tasks"
        }
      },
      "required": [
        "group_id",
        "action"
      ]
    }
  },
  {
    "name": "forecast_costs",
    "description": "Predict future costs based on historical usage patterns",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Project to forecast (omit for all)"
        },
        "days_ahead": {
          "type": "number",
          "description": "Number of days to forecast",
          "default": 30
        },
        "based_on_days": {
          "type": "number",
          "description": "Historical days to base forecast on",
          "default": 30
        }
      },
      "required": []
    }
  },
  {
    "name": "delete_budget",
    "description": "Delete a cost budget by ID or name",
    "inputSchema": {
      "type": "object",
      "properties": {
        "budget_id": {
          "type": "string",
          "description": "Budget ID or name to delete"
        }
      },
      "required": [
        "budget_id"
      ]
    }
  },
  {
    "name": "set_default_limits",
    "description": "Set default limits for new projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "max_concurrent": {
          "type": "number",
          "description": "Default max concurrent tasks for new projects",
          "minimum": 0
        },
        "max_daily_cost": {
          "type": "number",
          "description": "Default max daily cost for new projects"
        },
        "auto_create_config": {
          "type": "boolean",
          "description": "Automatically create project config on first task",
          "default": true
        }
      },
      "required": []
    }
  },
  {
    "name": "suggest_improvements",
    "description": "Analyze a failed task and get AI-generated suggestions for how to fix it. Uses error patterns and similar successful tasks.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to analyze (must be a failed task)"
        }
      },
      "required": [
        "task_id"
      ]
    }
  },
  {
    "name": "learn_defaults",
    "description": "Analyze task history to learn optimal default configurations. Builds patterns from successful tasks.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_limit": {
          "type": "number",
          "description": "Number of recent tasks to analyze",
          "default": 100
        }
      },
      "required": []
    }
  },
  {
    "name": "apply_smart_defaults",
    "description": "Get suggested configuration for a new task based on learned patterns from similar successful tasks.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_description": {
          "type": "string",
          "description": "The task description to get smart defaults for"
        },
        "project": {
          "type": "string",
          "description": "Project name for project-specific patterns"
        }
      },
      "required": [
        "task_description"
      ]
    }
  },
  {
    "name": "add_comment",
    "description": "Add a comment to a task for collaboration. Supports note, blocker, and resolution types.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to comment on"
        },
        "comment": {
          "type": "string",
          "description": "Comment text"
        },
        "comment_type": {
          "type": "string",
          "enum": [
            "note",
            "blocker",
            "resolution"
          ],
          "description": "Type of comment",
          "default": "note"
        },
        "author": {
          "type": "string",
          "description": "Author name",
          "default": "user"
        }
      },
      "required": [
        "task_id",
        "comment"
      ]
    }
  },
  {
    "name": "list_comments",
    "description": "Get all comments for a task.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID"
        },
        "comment_type": {
          "type": "string",
          "enum": [
            "note",
            "blocker",
            "resolution"
          ],
          "description": "Filter by comment type"
        }
      },
      "required": [
        "task_id"
      ]
    }
  },
  {
    "name": "dry_run_bulk",
    "description": "Preview affected tasks for a bulk operation without executing it",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation": {
          "type": "string",
          "enum": [
            "cancel",
            "retry",
            "tag",
            "archive"
          ],
          "description": "Type of bulk operation to preview"
        },
        "status": {
          "type": "string",
          "description": "Filter by status (or array for multiple)"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by tags"
        },
        "older_than_hours": {
          "type": "number",
          "description": "Filter tasks older than N hours"
        },
        "project": {
          "type": "string",
          "description": "Filter by project"
        }
      },
      "required": [
        "operation"
      ]
    }
  },
  {
    "name": "bulk_operation_status",
    "description": "Get status and results of a bulk operation by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation_id": {
          "type": "string",
          "description": "ID of the bulk operation"
        }
      },
      "required": [
        "operation_id"
      ]
    }
  },
  {
    "name": "list_bulk_operations",
    "description": "List recent bulk operations with optional filtering",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation_type": {
          "type": "string",
          "enum": [
            "cancel",
            "retry",
            "tag",
            "archive"
          ],
          "description": "Filter by operation type"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "running",
            "completed",
            "failed"
          ],
          "description": "Filter by operation status"
        },
        "limit": {
          "type": "number",
          "description": "Maximum number of operations to return",
          "default": 20
        }
      },
      "required": []
    }
  },
  {
    "name": "predict_duration",
    "description": "Estimate how long a task will take based on historical data and patterns",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_description": {
          "type": "string",
          "description": "The task description to analyze"
        },
        "template_name": {
          "type": "string",
          "description": "Template name if using a template"
        },
        "project": {
          "type": "string",
          "description": "Project context for prediction"
        }
      },
      "required": [
        "task_description"
      ]
    }
  },
  {
    "name": "duration_insights",
    "description": "Show prediction accuracy and factors affecting duration estimates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "Filter insights by project"
        },
        "limit": {
          "type": "number",
          "description": "Number of recent predictions to show",
          "default": 20
        }
      },
      "required": []
    }
  },
  {
    "name": "calibrate_predictions",
    "description": "Recalculate prediction models from historical task data",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "name": "set_task_review_status",
    "description": "Set the review status of a completed task. Use this to approve tasks, request corrections, or mark as pending review.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "task_id": {
          "type": "string",
          "description": "Task ID to review"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "approved",
            "needs_correction"
          ],
          "description": "Review status to set"
        },
        "notes": {
          "type": "string",
          "description": "Review notes or correction instructions"
        }
      },
      "required": [
        "task_id",
        "status"
      ]
    }
  },
  {
    "name": "list_pending_reviews",
    "description": "List completed tasks that are pending review. Use this to check work done by LLMs before approving.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "number",
          "default": 20,
          "description": "Maximum number of tasks to return"
        }
      }
    }
  },
  {
    "name": "list_tasks_needing_correction",
    "description": "List tasks that were marked as needing correction. These tasks need to be fixed and resubmitted.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_complexity_routing",
    "description": "Get the routing destination for a given complexity level based on current routing rules.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "complexity": {
          "type": "string",
          "enum": [
            "simple",
            "normal",
            "complex"
          ],
          "description": "Complexity level to check"
        }
      },
      "required": [
        "complexity"
      ]
    }
  }
];
