/**
 * Tool definitions for webhookHandlers
 * Auto-generated by extract-tool-defs.js
 */

const tools = [
  {
    name: 'add_webhook',
    description: 'Add a webhook to receive notifications when task events occur (completed, failed, etc.)',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Friendly name for the webhook'
        },
        url: {
          type: 'string',
          description: 'Webhook URL to POST to'
        },
        events: {
          type: 'array',
          items: { type: 'string' },
          description: 'Events to trigger on: completed, failed, started, cancelled, timeout, * (all)',
          default: ['completed', 'failed']
        },
        project: {
          type: 'string',
          description: 'Only trigger for this project (optional, null = all projects)'
        },
        type: {
          type: 'string',
          enum: ['http', 'slack', 'discord'],
          description: 'Webhook type (http=generic, slack=Slack format, discord=Discord format)',
          default: 'http'
        },
        headers: {
          type: 'object',
          description: 'Custom headers to include (for http type)'
        },
        secret: {
          type: 'string',
          description: 'Secret for HMAC signature (X-Webhook-Signature header)'
        }
      },
      required: ['name', 'url']
    }
  },
  {
    name: 'list_webhooks',
    description: 'List all configured webhooks',
    inputSchema: {
      type: 'object',
      properties: {
        project: {
          type: 'string',
          description: 'Filter by project (optional)'
        }
      },
      required: []
    }
  },
  {
    name: 'remove_webhook',
    description: 'Remove a webhook by ID',
    inputSchema: {
      type: 'object',
      properties: {
        webhook_id: {
          type: 'string',
          description: 'Webhook ID to remove'
        }
      },
      required: ['webhook_id']
    }
  },
  {
    name: 'test_webhook',
    description: 'Send a test notification to a webhook',
    inputSchema: {
      type: 'object',
      properties: {
        webhook_id: {
          type: 'string',
          description: 'Webhook ID to test'
        }
      },
      required: ['webhook_id']
    }
  },
  {
    name: 'webhook_logs',
    description: 'View delivery logs for a webhook',
    inputSchema: {
      type: 'object',
      properties: {
        webhook_id: {
          type: 'string',
          description: 'Webhook ID'
        },
        limit: {
          type: 'number',
          description: 'Number of logs to return (default: 20)',
          default: 20
        }
      },
      required: ['webhook_id']
    }
  },
  {
    name: 'webhook_stats',
    description: 'Get webhook delivery statistics',
    inputSchema: {
      type: 'object',
      properties: {},
      required: []
    }
  },
  {
    name: 'configure_retries',
    description: 'Configure retry policy for a task or set default retry settings',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID to configure (omit to set defaults)'
        },
        max_retries: {
          type: 'number',
          description: 'Maximum number of retry attempts (0-10)',
          default: 3
        },
        strategy: {
          type: 'string',
          enum: ['exponential', 'linear', 'fixed'],
          description: 'Retry delay strategy (default: exponential)'
        },
        base_delay_seconds: {
          type: 'number',
          description: 'Base delay between retries in seconds',
          default: 30
        }
      },
      required: []
    }
  },
  {
    name: 'add_budget_alert',
    description: 'Create a cost or token threshold alert',
    inputSchema: {
      type: 'object',
      properties: {
        alert_type: {
          type: 'string',
          enum: ['daily_cost', 'daily_tokens', 'monthly_cost'],
          description: 'Type of budget alert'
        },
        threshold_value: {
          type: 'number',
          description: 'Threshold value (e.g., 10.00 for $10 daily cost)'
        },
        threshold_percent: {
          type: 'number',
          description: 'Alert when usage reaches this percentage of threshold (default: 80)',
          default: 80
        },
        project: {
          type: 'string',
          description: 'Project to monitor (omit for all projects)'
        },
        webhook_id: {
          type: 'string',
          description: 'Webhook to notify when alert triggers'
        },
        cooldown_minutes: {
          type: 'number',
          description: 'Minimum minutes between alerts (default: 60)',
          default: 60
        }
      },
      required: ['alert_type', 'threshold_value']
    }
  },
  {
    name: 'list_budget_alerts',
    description: 'List all configured budget alerts',
    inputSchema: {
      type: 'object',
      properties: {
        project: {
          type: 'string',
          description: 'Filter by project'
        },
        alert_type: {
          type: 'string',
          enum: ['daily_cost', 'daily_tokens', 'monthly_cost'],
          description: 'Filter by alert type'
        }
      },
      required: []
    }
  },
  {
    name: 'remove_budget_alert',
    description: 'Delete a budget alert',
    inputSchema: {
      type: 'object',
      properties: {
        alert_id: {
          type: 'string',
          description: 'ID of the budget alert to remove'
        }
      },
      required: ['alert_id']
    }
  },
  {
    name: 'configure_auto_cleanup',
    description: 'Configure automatic task cleanup and archiving policies',
    inputSchema: {
      type: 'object',
      properties: {
        auto_archive_days: {
          type: 'number',
          description: 'Archive tasks older than N days (0 to disable)'
        },
        auto_archive_status: {
          type: 'array',
          items: { type: 'string', enum: ['completed', 'failed', 'cancelled'] },
          description: 'Statuses to auto-archive (default: completed, failed)'
        },
        cleanup_log_days: {
          type: 'number',
          description: 'Delete logs older than N days (0 to disable)'
        }
      },
      required: []
    }
  },
  {
    name: 'run_maintenance',
    description: 'Run maintenance tasks manually or configure maintenance schedule',
    inputSchema: {
      type: 'object',
      properties: {
        task_type: {
          type: 'string',
          enum: ['archive_old_tasks', 'cleanup_logs', 'aggregate_metrics', 'all'],
          description: 'Type of maintenance to run (default: all)'
        },
        schedule: {
          type: 'object',
          properties: {
            enabled: { type: 'boolean', description: 'Enable scheduled maintenance' },
            interval_minutes: { type: 'number', description: 'Run every N minutes' }
          },
          description: 'Configure scheduled maintenance (omit to run immediately)'
        }
      },
      required: []
    }
  },
  {
    name: 'notify_slack',
    description: 'Send a notification to a Slack channel',
    inputSchema: {
      type: 'object',
      properties: {
        channel: {
          type: 'string',
          description: 'Slack channel (e.g., #general)'
        },
        message: {
          type: 'string',
          description: 'Message text'
        },
        task_id: {
          type: 'string',
          description: 'Task ID to include details from (optional)'
        },
        blocks: {
          type: 'array',
          description: 'Slack Block Kit blocks (optional)'
        }
      },
      required: ['message']
    }
  },
  {
    name: 'notify_discord',
    description: 'Send a notification to a Discord channel',
    inputSchema: {
      type: 'object',
      properties: {
        message: {
          type: 'string',
          description: 'Message content'
        },
        task_id: {
          type: 'string',
          description: 'Task ID to include details from (optional)'
        },
        embed: {
          type: 'object',
          description: 'Discord embed object (optional)',
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            color: { type: 'number' }
          }
        }
      },
      required: ['message']
    }
  },
  {
    name: 'quick_setup_notifications',
    description: 'Quick one-step setup for Slack or Discord task notifications. Auto-detects platform from URL. Creates webhook + configures integration in one call.',
    inputSchema: {
      type: 'object',
      properties: {
        webhook_url: {
          type: 'string',
          description: 'Slack incoming webhook URL or Discord webhook URL'
        },
        type: {
          type: 'string',
          enum: ['slack', 'discord', 'http'],
          description: 'Webhook type (auto-detected from URL if not specified)'
        },
        events: {
          type: 'array',
          items: { type: 'string' },
          description: 'Events to notify on (default: completed, failed). Use * for all.'
        },
        name: {
          type: 'string',
          description: 'Webhook name (default: auto-generated)'
        },
        project: {
          type: 'string',
          description: 'Filter to specific project (default: all projects)'
        }
      },
      required: ['webhook_url']
    }
  },
  {
    name: 'get_retry_history',
    description: 'Get retry attempt history.',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Filter by original task ID (optional)'
        },
        limit: {
          type: 'number',
          description: 'Maximum results to return (default: 50)'
        }
      }
    }
  },
  {
    name: 'create_inbound_webhook',
    description: 'Create an inbound webhook that triggers task creation when external services POST to TORQUE. Returns the webhook secret and endpoint URL.',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Unique name for the inbound webhook (used in endpoint URL)'
        },
        source_type: {
          type: 'string',
          enum: ['generic', 'github', 'gitlab'],
          description: 'Source type for signature verification (default: generic)',
          default: 'generic'
        },
        task_description: {
          type: 'string',
          description: 'Task description template. Use {{payload.field}} for variable substitution from webhook payload.'
        },
        trigger_type: {
          type: 'string',
          enum: ['standard', 'free_tier_task'],
          description: 'How to route created tasks. standard: use smart_submit_task (default). free_tier_task: route to free-tier providers (groq, cerebras, google-ai, openrouter), skipping Codex entirely.',
          default: 'standard'
        },
        provider: {
          type: 'string',
          description: 'Provider to use for created tasks (optional)'
        },
        model: {
          type: 'string',
          description: 'Model to use for created tasks (optional)'
        },
        tags: {
          type: 'string',
          description: 'Comma-separated tags for created tasks (optional)'
        },
        working_directory: {
          type: 'string',
          description: 'Working directory for created tasks (optional)'
        }
      },
      required: ['name', 'task_description']
    }
  },
  {
    name: 'list_inbound_webhooks',
    description: 'List all configured inbound webhooks',
    inputSchema: {
      type: 'object',
      properties: {},
      required: []
    }
  },
  {
    name: 'delete_inbound_webhook',
    description: 'Delete an inbound webhook by name',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Name of the inbound webhook to delete'
        }
      },
      required: ['name']
    }
  },
  {
    name: 'manage_webhook',
    description: 'Unified webhook management. Actions: add/list/remove/test/logs/stats (outbound), create_inbound/list_inbound/delete_inbound, notify_slack/notify_discord, quick_setup.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['add', 'list', 'remove', 'test', 'logs', 'stats', 'quick_setup', 'notify_slack', 'notify_discord', 'create_inbound', 'list_inbound', 'delete_inbound'],
          description: 'Operation to perform'
        },
        // Outbound webhook params (add/remove/test/logs)
        name: { type: 'string', description: 'Webhook name' },
        url: { type: 'string', description: 'Webhook URL' },
        webhook_id: { type: 'string', description: 'Webhook ID (for remove/test/logs)' },
        events: { type: 'array', items: { type: 'string' }, description: 'Events to trigger on' },
        project: { type: 'string', description: 'Filter by project' },
        type: { type: 'string', enum: ['http', 'slack', 'discord'], description: 'Webhook type' },
        headers: { type: 'object', description: 'Custom headers' },
        secret: { type: 'string', description: 'HMAC signature secret' },
        limit: { type: 'number', description: 'Number of logs to return' },
        // Notification params
        webhook_url: { type: 'string', description: 'Slack/Discord webhook URL (for quick_setup)' },
        channel: { type: 'string', description: 'Slack channel' },
        message: { type: 'string', description: 'Message text' },
        task_id: { type: 'string', description: 'Task ID for details' },
        blocks: { type: 'array', description: 'Slack Block Kit blocks' },
        embed: { type: 'object', description: 'Discord embed object' },
        // Inbound webhook params
        source_type: { type: 'string', enum: ['generic', 'github', 'gitlab'], description: 'Source type for signature verification' },
        task_description: { type: 'string', description: 'Task description template' },
        trigger_type: { type: 'string', enum: ['standard', 'free_tier_task'], description: 'How to route created tasks' },
        provider: { type: 'string', description: 'Provider for created tasks' },
        model: { type: 'string', description: 'Model for created tasks' },
        tags: { type: 'string', description: 'Comma-separated tags' },
        working_directory: { type: 'string', description: 'Working directory for created tasks' },
      },
      required: ['action']
    }
  }
];

module.exports = tools;
