/**
 * Tool definitions for workflowHandlers
 * Auto-generated by extract-tool-defs.js
 */

const tools = [
  {
    name: 'duplicate_pipeline',
    description: 'Clone an entire pipeline with new parameters.',
    inputSchema: {
      type: 'object',
      properties: {
        pipeline_id: {
          type: 'number',
          description: 'ID of the pipeline to clone'
        },
        new_name: {
          type: 'string',
          description: 'Name for the cloned pipeline'
        },
        working_directory: {
          type: 'string',
          description: 'Override working directory for all steps'
        },
        auto_approve: {
          type: 'boolean',
          description: 'Override auto_approve for all steps'
        },
        timeout_minutes: {
          type: 'number',
          description: 'Override timeout for all steps'
        },
        description: {
          type: 'string',
          description: 'Additional description for the clone'
        }
      },
      required: ['pipeline_id', 'new_name']
    }
  },
  {
    name: 'export_report',
    description: 'Generate a comprehensive task report in JSON, CSV, or Markdown format.',
    inputSchema: {
      type: 'object',
      properties: {
        format: {
          type: 'string',
          enum: ['json', 'csv', 'markdown'],
          description: 'Export format',
          default: 'markdown'
        },
        project: {
          type: 'string',
          description: 'Filter by project'
        },
        status: {
          type: 'string',
          description: 'Filter by status (or comma-separated list)'
        },
        start_date: {
          type: 'string',
          description: 'Start date (ISO format)'
        },
        end_date: {
          type: 'string',
          description: 'End date (ISO format)'
        },
        tags: {
          type: 'array',
          items: { type: 'string' },
          description: 'Filter by tags'
        },
        include_output: {
          type: 'boolean',
          description: 'Include task output in report',
          default: false
        }
      },
      required: []
    }
  },
  {
    name: 'create_workflow',
    description: 'Create a new workflow (DAG of dependent tasks)',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Workflow name'
        },
        description: {
          type: 'string',
          description: 'Optional description'
        },
        priority: {
          type: 'number',
          description: 'Workflow priority used for persistence and ordering',
          default: 0
        },
        tasks: {
          type: 'array',
          description: 'Initial workflow DAG nodes to create with the workflow. Empty workflows are rejected.',
          items: {
            type: 'object',
            properties: {
              node_id: {
                type: 'string',
                description: 'Unique node identifier within the workflow DAG'
              },
              task_description: {
                type: 'string',
                description: 'Task description/prompt for this node'
              },
              task: {
                type: 'string',
                description: 'Optional full task prompt; overrides task_description when both are provided'
              },
              depends_on: {
                type: 'array',
                items: { type: 'string' },
                description: 'Array of node_ids this task depends on'
              },
              condition: {
                type: 'string',
                description: 'Condition expression applied to each dependency edge'
              },
              on_fail: {
                type: 'string',
                enum: ['cancel', 'skip', 'continue', 'run_alternate'],
                description: 'Action when a dependency fails',
                default: 'skip'
              },
              alternate_node_id: {
                type: 'string',
                description: 'Alternate node to run when on_fail is run_alternate'
              },
              timeout_minutes: {
                type: 'number',
                description: 'Task timeout in minutes'
              },
              auto_approve: {
                type: 'boolean',
                description: 'Auto-approve task execution for this node'
              },
              working_directory: {
                type: 'string',
                description: 'Optional working directory override for this node'
              },
              tags: {
                type: 'array',
                items: { type: 'string' },
                description: 'Optional tags for this node'
              },
              provider: {
                type: 'string',
                enum: ['codex', 'claude-cli', 'ollama', 'aider-ollama', 'hashline-ollama', 'hashline-openai'],
                description: 'Optional provider override for this node'
              },
              model: {
                type: 'string',
                description: 'Optional model override for this node'
              },
              context_from: {
                type: 'array',
                items: { type: 'string' },
                description: 'Array of node_ids whose outputs should be injected when this node unblocks'
              }
            },
            required: ['node_id']
          }
        },
        working_directory: {
          type: 'string',
          description: 'Default working directory for tasks in this workflow. Tasks inherit this if they do not specify their own.'
        }
      },
      required: ['name', 'tasks']
    }
  },
  {
    name: 'add_workflow_task',
    description: 'Add a task to a workflow with optional dependencies',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to add task to'
        },
        task_description: {
          type: 'string',
          description: 'Task description/prompt'
        },
        node_id: {
          type: 'string',
          description: 'Unique identifier for this task within the workflow'
        },
        depends_on: {
          type: 'array',
          items: { type: 'string' },
          description: 'Array of node_ids this task depends on'
        },
        condition: {
          type: 'string',
          description: 'Condition expression (e.g., "exit_code == 0")'
        },
        on_fail: {
          type: 'string',
          enum: ['cancel', 'skip', 'continue', 'run_alternate'],
          description: 'Action when dependency fails',
          default: 'skip'
        },
        alternate_node_id: {
          type: 'string',
          description: 'Node to run if on_fail is run_alternate'
        },
        timeout_minutes: {
          type: 'number',
          description: 'Task timeout in minutes',
          default: 30
        },
        auto_approve: {
          type: 'boolean',
          description: 'Auto-approve task execution',
          default: false
        },
        working_directory: {
          type: 'string',
          description: 'Working directory for task'
        },
        tags: {
          type: 'array',
          items: { type: 'string' },
          description: 'Tags for the task'
        },
        provider: {
          type: 'string',
          description: 'Execution provider for this task (overrides project default)',
          enum: ['codex', 'claude-cli', 'ollama', 'aider-ollama', 'hashline-ollama', 'hashline-openai']
        },
        model: {
          type: 'string',
          description: 'Model override for this task (e.g., qwen2.5-coder:7b for ollama)'
        },
        context_from: {
          type: 'array',
          items: { type: 'string' },
          description: 'Array of node_ids whose outputs should be auto-injected as "Prior step results:" context when this task is unblocked'
        }
      },
      required: ['workflow_id', 'task_description', 'node_id']
    }
  },
  {
    name: 'run_workflow',
    description: 'Start executing a workflow',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to start'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'export_workflow',
    description: 'Export a workflow as a portable JSON structure.',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to export'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'import_workflow',
    description: 'Import a workflow from a portable JSON structure.',
    inputSchema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          description: 'Portable workflow JSON payload'
        }
      },
      required: ['data']
    }
  },
  {
    name: 'workflow_status',
    description: 'Get detailed workflow progress and task states',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to check'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'cancel_workflow',
    description: 'Cancel a workflow and all its pending tasks',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to cancel'
        },
        reason: {
          type: 'string',
          description: 'Cancellation reason'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'pause_workflow',
    description: 'Pause a workflow (block new task starts)',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to pause'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'create_workflow_template',
    description: 'Create a reusable workflow template',
    inputSchema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Unique template name'
        },
        description: {
          type: 'string',
          description: 'Template description'
        },
        task_definitions: {
          type: 'array',
          description: 'Array of task blueprints with node_id, task_description, etc.',
          items: {
            type: 'object',
            properties: {
              node_id: { type: 'string' },
              task_description: { type: 'string' },
              timeout_minutes: { type: 'number' },
              auto_approve: { type: 'boolean' },
              tags: { type: 'array', items: { type: 'string' } }
            },
            required: ['node_id', 'task_description']
          }
        },
        dependency_graph: {
          type: 'object',
          description: 'Object mapping node_id to array of dependency definitions'
        },
        variables: {
          type: 'object',
          description: 'Variable schema with defaults'
        }
      },
      required: ['name', 'task_definitions', 'dependency_graph']
    }
  },
  {
    name: 'list_workflow_templates',
    description: 'List available workflow templates',
    inputSchema: {
      type: 'object',
      properties: {
        filter: {
          type: 'string',
          description: 'Filter templates by name'
        },
        limit: {
          type: 'number',
          description: 'Maximum templates to return',
          default: 20
        }
      },
      required: []
    }
  },
  {
    name: 'instantiate_template',
    description: 'Create a workflow from a template',
    inputSchema: {
      type: 'object',
      properties: {
        template_id: {
          type: 'string',
          description: 'Template ID or name'
        },
        name: {
          type: 'string',
          description: 'Name for the new workflow'
        },
        variables: {
          type: 'object',
          description: 'Variable values for template substitution'
        },
        auto_run: {
          type: 'boolean',
          description: 'Automatically start workflow after creation',
          default: false
        }
      },
      required: ['template_id']
    }
  },
  {
    name: 'delete_workflow_template',
    description: 'Delete a workflow template',
    inputSchema: {
      type: 'object',
      properties: {
        template_id: {
          type: 'string',
          description: 'Template ID to delete'
        }
      },
      required: ['template_id']
    }
  },
  {
    name: 'dependency_graph',
    description: 'Get visual representation of workflow DAG',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to visualize'
        },
        format: {
          type: 'string',
          enum: ['json', 'mermaid', 'ascii'],
          description: 'Output format',
          default: 'mermaid'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'critical_path',
    description: 'Find the longest execution path through workflow',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to analyze'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'what_if',
    description: 'Simulate what happens if a task fails or succeeds',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to simulate'
        },
        task_id: {
          type: 'string',
          description: 'Task ID to simulate failure/success for'
        },
        simulated_status: {
          type: 'string',
          enum: ['completed', 'failed'],
          description: 'Simulated task status'
        },
        simulated_exit_code: {
          type: 'number',
          description: 'Simulated exit code',
          default: 0
        }
      },
      required: ['workflow_id', 'task_id', 'simulated_status']
    }
  },
  {
    name: 'blocked_tasks',
    description: 'List tasks waiting on dependencies',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Filter by workflow ID'
        }
      },
      required: []
    }
  },
  {
    name: 'retry_workflow_from',
    description: 'Restart workflow from a specific failed task',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to retry'
        },
        from_task_id: {
          type: 'string',
          description: 'Task ID to restart from'
        }
      },
      required: ['workflow_id', 'from_task_id']
    }
  },
  {
    name: 'skip_task',
    description: 'Manually skip a blocked task',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'Task ID to skip'
        },
        reason: {
          type: 'string',
          description: 'Reason for skipping'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'list_workflows',
    description: 'Query workflows with filters',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['pending', 'running', 'completed', 'failed', 'cancelled', 'paused'],
          description: 'Filter by status'
        },
        template_id: {
          type: 'string',
          description: 'Filter by template'
        },
        since: {
          type: 'string',
          description: 'ISO date string - only workflows created after this'
        },
        limit: {
          type: 'number',
          description: 'Maximum workflows to return',
          default: 20
        }
      },
      required: []
    }
  },
  {
    name: 'workflow_history',
    description: 'Get execution timeline of a workflow',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to get history for'
        }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'create_conditional_template',
    description: 'Create a template with conditional logic (if/else) based on input variables',
    inputSchema: {
      type: 'object',
      properties: {
        template_id: {
          type: 'string',
          description: 'ID of the template to add condition to'
        },
        condition_type: {
          type: 'string',
          enum: ['if', 'switch', 'when'],
          description: 'Type of condition: if (boolean), switch (multi-case), when (pattern match)'
        },
        condition_expr: {
          type: 'string',
          description: 'Condition expression (e.g., "${env} == production", "${count} > 10")'
        },
        then_block: {
          type: 'string',
          description: 'Task template to use when condition is true'
        },
        else_block: {
          type: 'string',
          description: 'Task template to use when condition is false (optional)'
        }
      },
      required: ['template_id', 'condition_type', 'condition_expr']
    }
  },
  {
    name: 'template_loop',
    description: 'Iterate a template over an array of values, creating multiple tasks',
    inputSchema: {
      type: 'object',
      properties: {
        template_id: {
          type: 'string',
          description: 'Template ID to iterate'
        },
        items: {
          type: 'array',
          items: { type: 'string' },
          description: 'Array of values to iterate over'
        },
        variable_name: {
          type: 'string',
          description: 'Variable name to use in template (default: "item")',
          default: 'item'
        },
        parallel: {
          type: 'boolean',
          description: 'Run iterations in parallel (default: false)',
          default: false
        }
      },
      required: ['template_id', 'items']
    }
  },
  {
    name: 'fork_workflow',
    description: 'Branch a workflow into multiple parallel execution paths',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: {
          type: 'string',
          description: 'Workflow ID to fork'
        },
        branches: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Branch name' },
              tasks: {
                type: 'array',
                items: { type: 'string' },
                description: 'Task descriptions for this branch'
              }
            },
            required: ['name', 'tasks']
          },
          description: 'Branch definitions (at least 2)'
        },
        merge_strategy: {
          type: 'string',
          enum: ['all', 'any', 'first'],
          description: 'How to merge branches: all (wait for all), any (first success), first (race)',
          default: 'all'
        }
      },
      required: ['workflow_id', 'branches']
    }
  },
  {
    name: 'merge_workflows',
    description: 'Merge multiple workflow branches back into a single execution path',
    inputSchema: {
      type: 'object',
      properties: {
        fork_id: {
          type: 'string',
          description: 'Fork ID to merge'
        },
        combine_outputs: {
          type: 'boolean',
          description: 'Combine branch outputs (default: true)',
          default: true
        }
      },
      required: ['fork_id']
    }
  },
  {
    name: 'replay_task',
    description: 'Replay a completed task with optionally modified inputs',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: {
          type: 'string',
          description: 'ID of the original task to replay'
        },
        modified_inputs: {
          type: 'object',
          description: 'Modified input parameters (merged with original)'
        },
        new_working_directory: {
          type: 'string',
          description: 'New working directory (optional, defaults to original)'
        }
      },
      required: ['task_id']
    }
  },
  {
    name: 'diff_task_runs',
    description: 'Compare two task executions to identify differences',
    inputSchema: {
      type: 'object',
      properties: {
        task_id_a: {
          type: 'string',
          description: 'First task ID to compare'
        },
        task_id_b: {
          type: 'string',
          description: 'Second task ID to compare'
        },
        compare_fields: {
          type: 'array',
          items: { type: 'string' },
          description: 'Fields to compare (default: output, files, duration)',
          default: ['output', 'files_modified', 'duration', 'exit_code']
        }
      },
      required: ['task_id_a', 'task_id_b']
    }
  },
  {
    name: 'await_workflow',
    description: 'Yield-on-completion workflow monitor. Blocks until the NEXT task finishes (wakes instantly via push notifications — no polling delay), returns its output for review, then returns. Call repeatedly to review tasks one-by-one. On the final call (all tasks done), runs verify/commit and returns the full summary. State is server-side — no parameters needed between calls. GLOBAL: works with any project.',
    inputSchema: {
      type: 'object',
      properties: {
        workflow_id: { type: 'string', description: 'Workflow ID to wait for' },
        timeout_minutes: { type: 'number', description: 'Max wait time in minutes (default: 30, max: 60)' },
        poll_interval_ms: { type: 'number', description: 'Fallback poll interval in ms if push notifications unavailable (default: 5000). Usually not needed — tasks wake the loop instantly via event bus.' },
        verify_command: { type: 'string', description: 'Shell command to run after successful completion (e.g., "npx tsc --noEmit && npx vitest run"). Runs in working_directory.' },
        auto_commit: { type: 'boolean', description: 'Auto-commit all changes on success (after verify passes if set)' },
        commit_message: { type: 'string', description: 'Custom commit message (default: workflow name)' },
        auto_push: { type: 'boolean', description: 'Auto-push after commit (default: false; only runs when explicitly true)' },
        working_directory: { type: 'string', description: 'Working directory for verify/commit (defaults to workflow working_directory)' }
      },
      required: ['workflow_id']
    }
  },
  {
    name: 'await_task',
    description: 'Block until a standalone task completes or fails, then return its result. Wakes instantly via event-bus push notifications (no polling delay). Optionally runs verify_command and auto-commits on success. Use this instead of polling check_status in a loop. GLOBAL: works with any project.',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: { type: 'string', description: 'Task ID to wait for' },
        timeout_minutes: { type: 'number', description: 'Max wait time in minutes (default: 30, max: 60)' },
        poll_interval_ms: { type: 'number', description: 'Fallback poll interval in ms if push notifications unavailable (default: 5000). Usually not needed — tasks wake the loop instantly via event bus.' },
        verify_command: { type: 'string', description: 'Shell command to run after successful completion (e.g., "npx tsc --noEmit && npx vitest run"). Runs in working_directory.' },
        auto_commit: { type: 'boolean', description: 'Auto-commit all changes on success (after verify passes if set)' },
        commit_message: { type: 'string', description: 'Custom commit message (default: task description)' },
        auto_push: { type: 'boolean', description: 'Auto-push after commit (default: false; only runs when explicitly true)' },
        working_directory: { type: 'string', description: 'Working directory for verify/commit (defaults to task working_directory)' }
      },
      required: ['task_id']
    }
  },
  {
    name: 'create_feature_workflow',
    description: 'Create a standardized feature workflow DAG: types → data → events → system → tests + wire. Eliminates repetitive workflow construction. Optionally adds parallel test tasks and auto-runs. GLOBAL: works with any project following the types→data→system pattern.',
    inputSchema: {
      type: 'object',
      properties: {
        feature_name: { type: 'string', description: 'PascalCase feature name (e.g., "SponsorshipSystem"). Used to generate file paths and node IDs.' },
        working_directory: { type: 'string', description: 'Working directory for all tasks' },
        workflow_name: { type: 'string', description: 'Custom workflow name (default: "Feature: {name}")' },
        description: { type: 'string', description: 'Workflow description' },
        types_task: { type: 'string', description: 'Task description for creating type definitions (Step 1, no deps)' },
        events_task: { type: 'string', description: 'Task description for adding events (Step 2, parallel with types)' },
        data_task: { type: 'string', description: 'Task description for creating data/definitions file (Step 3, depends on types)' },
        system_task: { type: 'string', description: 'Task description for creating the main system class (Step 4, depends on data + events)' },
        tests_task: { type: 'string', description: 'Task description for creating tests (Step 5, depends on system)' },
        wire_task: { type: 'string', description: 'Task description for wiring into existing code (Step 6, depends on system, parallel with tests)' },
        parallel_tasks: {
          type: 'array',
          description: 'Extra tasks that run in parallel with the feature chain (e.g., data tests, UI tests)',
          items: {
            type: 'object',
            properties: {
              node_id: { type: 'string', description: 'Unique node ID for this task' },
              task: { type: 'string', description: 'Task description' },
              provider: { type: 'string', description: 'Execution provider for this parallel task' }
            },
            required: ['task']
          }
        },
        auto_run: { type: 'boolean', description: 'Immediately start the workflow after creation (default: false)' },
        step_providers: {
          type: 'object',
          description: 'Per-step provider overrides. Keys: types, events, data, system, tests, wire, parallel. Unset steps use project default (codex).',
          properties: {
            types: { type: 'string', description: 'Provider for types step' },
            events: { type: 'string', description: 'Provider for events step' },
            data: { type: 'string', description: 'Provider for data step' },
            system: { type: 'string', description: 'Provider for system step' },
            tests: { type: 'string', description: 'Provider for tests step' },
            wire: { type: 'string', description: 'Provider for wire step' },
            parallel: { type: 'string', description: 'Default provider for parallel tasks (individual tasks can override)' }
          }
        }
      },
      required: ['feature_name', 'working_directory']
    }
  }
];

module.exports = tools;
