'use strict';

const fs = require('fs');
const fsPromises = require('node:fs/promises');
const path = require('path');

const {
  STUDY_EVALUATION_FILE,
  DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
  DEFAULT_PROPOSAL_MIN_SCORE,
  normalizeStudyThresholdLevel,
} = require('../codebase-study-engine');

const STUDY_DIR = path.join('docs', 'architecture');
const STATE_FILE = path.join(STUDY_DIR, 'study-state.json');
const MODULE_INDEX_FILE = path.join(STUDY_DIR, 'module-index.json');
const KNOWLEDGE_PACK_FILE = path.join(STUDY_DIR, 'knowledge-pack.json');
const STUDY_DELTA_FILE = path.join(STUDY_DIR, 'study-delta.json');
const STUDY_BENCHMARK_FILE_LOCAL = path.join(STUDY_DIR, 'study-benchmark.json');
const SUMMARY_FILE = path.join(STUDY_DIR, 'SUMMARY.md');
const SUMMARY_PLACEHOLDER = 'auto-generated by study loop, no runs yet\n';
const LOCAL_ONLY_STRATEGY = 'local-deterministic';

function resolveWorkingDirectory(workingDirectory) {
  if (typeof workingDirectory !== 'string' || !workingDirectory.trim()) {
    throw new Error('workingDirectory must be a non-empty string');
  }

  const resolved = path.resolve(workingDirectory.trim());
  if (!fs.existsSync(resolved)) {
    throw new Error(`Working directory not found: ${resolved}`);
  }

  return resolved;
}

function toRepoPath(filePath) {
  return String(filePath || '').trim().replace(/\\/g, '/');
}

function uniqueStrings(values) {
  const seen = new Set();
  const output = [];
  for (const value of Array.isArray(values) ? values : []) {
    const normalized = String(value || '').trim();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    output.push(normalized);
  }
  return output;
}

function uniquePaths(values) {
  const seen = new Set();
  const output = [];
  for (const value of Array.isArray(values) ? values : []) {
    const normalized = toRepoPath(value);
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    output.push(normalized);
  }
  return output;
}

function normalizeNonNegativeInteger(value, fallback = 0) {
  return Number.isInteger(value) && value >= 0 ? value : fallback;
}

function buildCounts(trackedFiles, pendingFiles) {
  return {
    tracked: trackedFiles.length,
    pending: pendingFiles.length,
    up_to_date: Math.max(0, trackedFiles.length - pendingFiles.length),
  };
}

function extractReadmeIntro(content) {
  const lines = String(content || '').split(/\r?\n/);
  const collected = [];
  let started = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!started) {
      if (!trimmed || trimmed.startsWith('#')) continue;
      started = true;
      collected.push(trimmed);
      continue;
    }
    if (!trimmed) break;
    collected.push(trimmed);
  }
  return collected.join(' ');
}

function buildInitialState() {
  return {
    run_count: 0,
    last_sha: null,
    last_task_id: null,
    last_batch: [],
    last_run_at: null,
    last_completed_at: null,
    last_result: null,
    last_error: null,
    tracked_files: [],
    pending_files: [],
    file_counts: {
      tracked: 0,
      pending: 0,
      up_to_date: 0,
    },
    index_strategy: LOCAL_ONLY_STRATEGY,
    summary_strategy: LOCAL_ONLY_STRATEGY,
    last_processed_count: 0,
    last_removed_count: 0,
    last_summary_updated_at: null,
    knowledge_pack_updated_at: null,
    last_delta_updated_at: null,
    module_entry_count: 0,
    subsystem_count: 0,
    flow_count: 0,
    hotspot_count: 0,
    invariant_count: 0,
    failure_mode_count: 0,
    trace_count: 0,
    playbook_count: 0,
    test_area_count: 0,
    delta_significance_level: 'none',
    delta_significance_score: 0,
    proposal_count: 0,
    submitted_proposal_count: 0,
    proposal_significance_level: DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
    proposal_min_score: DEFAULT_PROPOSAL_MIN_SCORE,
    evaluation_score: 0,
    evaluation_grade: null,
    evaluation_readiness: null,
    evaluation_findings_count: 0,
    evaluation_generated_at: null,
    benchmark_score: 0,
    benchmark_grade: null,
    benchmark_readiness: null,
    benchmark_findings_count: 0,
    benchmark_case_count: 0,
    benchmark_generated_at: null,
  };
}

function normalizeState(rawState) {
  const initial = buildInitialState();
  const source = rawState && typeof rawState === 'object' && !Array.isArray(rawState)
    ? rawState
    : {};
  const trackedFiles = uniquePaths(source.tracked_files);
  const pendingFiles = uniquePaths(source.pending_files).filter(file => trackedFiles.includes(file));
  const fileCounts = buildCounts(trackedFiles, pendingFiles);

  return {
    ...initial,
    ...source,
    last_sha: typeof source.last_sha === 'string' && source.last_sha.trim() ? source.last_sha.trim() : null,
    last_task_id: typeof source.last_task_id === 'string' && source.last_task_id.trim() ? source.last_task_id.trim() : null,
    last_batch: uniquePaths(source.last_batch),
    tracked_files: trackedFiles,
    pending_files: pendingFiles,
    file_counts: fileCounts,
    index_strategy: typeof source.index_strategy === 'string' && source.index_strategy.trim()
      ? source.index_strategy.trim()
      : LOCAL_ONLY_STRATEGY,
    summary_strategy: typeof source.summary_strategy === 'string' && source.summary_strategy.trim()
      ? source.summary_strategy.trim()
      : LOCAL_ONLY_STRATEGY,
    last_processed_count: normalizeNonNegativeInteger(source.last_processed_count),
    last_removed_count: normalizeNonNegativeInteger(source.last_removed_count),
    last_summary_updated_at: typeof source.last_summary_updated_at === 'string' && source.last_summary_updated_at.trim()
      ? source.last_summary_updated_at.trim()
      : null,
    knowledge_pack_updated_at: typeof source.knowledge_pack_updated_at === 'string' && source.knowledge_pack_updated_at.trim()
      ? source.knowledge_pack_updated_at.trim()
      : null,
    last_delta_updated_at: typeof source.last_delta_updated_at === 'string' && source.last_delta_updated_at.trim()
      ? source.last_delta_updated_at.trim()
      : null,
    module_entry_count: normalizeNonNegativeInteger(source.module_entry_count),
    subsystem_count: normalizeNonNegativeInteger(source.subsystem_count),
    flow_count: normalizeNonNegativeInteger(source.flow_count),
    hotspot_count: normalizeNonNegativeInteger(source.hotspot_count),
    invariant_count: normalizeNonNegativeInteger(source.invariant_count),
    failure_mode_count: normalizeNonNegativeInteger(source.failure_mode_count),
    trace_count: normalizeNonNegativeInteger(source.trace_count),
    playbook_count: normalizeNonNegativeInteger(source.playbook_count),
    test_area_count: normalizeNonNegativeInteger(source.test_area_count),
    delta_significance_level: typeof source.delta_significance_level === 'string' && source.delta_significance_level.trim()
      ? source.delta_significance_level.trim()
      : 'none',
    delta_significance_score: normalizeNonNegativeInteger(source.delta_significance_score),
    proposal_count: normalizeNonNegativeInteger(source.proposal_count),
    submitted_proposal_count: normalizeNonNegativeInteger(source.submitted_proposal_count),
    proposal_significance_level: normalizeStudyThresholdLevel(
      source.proposal_significance_level,
      DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL
    ),
    proposal_min_score: normalizeNonNegativeInteger(source.proposal_min_score, DEFAULT_PROPOSAL_MIN_SCORE),
    evaluation_score: normalizeNonNegativeInteger(source.evaluation_score),
    evaluation_grade: typeof source.evaluation_grade === 'string' && source.evaluation_grade.trim()
      ? source.evaluation_grade.trim()
      : null,
    evaluation_readiness: typeof source.evaluation_readiness === 'string' && source.evaluation_readiness.trim()
      ? source.evaluation_readiness.trim()
      : null,
    evaluation_findings_count: normalizeNonNegativeInteger(source.evaluation_findings_count),
    evaluation_generated_at: typeof source.evaluation_generated_at === 'string' && source.evaluation_generated_at.trim()
      ? source.evaluation_generated_at.trim()
      : null,
    benchmark_score: normalizeNonNegativeInteger(source.benchmark_score),
    benchmark_grade: typeof source.benchmark_grade === 'string' && source.benchmark_grade.trim()
      ? source.benchmark_grade.trim()
      : null,
    benchmark_readiness: typeof source.benchmark_readiness === 'string' && source.benchmark_readiness.trim()
      ? source.benchmark_readiness.trim()
      : null,
    benchmark_findings_count: normalizeNonNegativeInteger(source.benchmark_findings_count),
    benchmark_case_count: normalizeNonNegativeInteger(source.benchmark_case_count),
    benchmark_generated_at: typeof source.benchmark_generated_at === 'string' && source.benchmark_generated_at.trim()
      ? source.benchmark_generated_at.trim()
      : null,
  };
}

function normalizeModuleEntry(rawEntry) {
  const entry = rawEntry && typeof rawEntry === 'object' && !Array.isArray(rawEntry)
    ? rawEntry
    : {};
  const file = toRepoPath(entry.file);
  if (!file) {
    return null;
  }
  return {
    file,
    purpose: typeof entry.purpose === 'string' ? entry.purpose.trim() : '',
    exports: uniqueStrings(entry.exports),
    deps: uniqueStrings(entry.deps),
  };
}

function normalizeModuleIndex(rawIndex) {
  const source = rawIndex && typeof rawIndex === 'object' && !Array.isArray(rawIndex)
    ? rawIndex
    : {};
  const modules = [];
  const seen = new Set();
  for (const rawEntry of Array.isArray(source.modules) ? source.modules : []) {
    const entry = normalizeModuleEntry(rawEntry);
    if (!entry || seen.has(entry.file)) {
      continue;
    }
    seen.add(entry.file);
    modules.push(entry);
  }
  modules.sort((left, right) => left.file.localeCompare(right.file));
  return {
    modules,
    last_updated: typeof source.last_updated === 'string' && source.last_updated.trim()
      ? source.last_updated.trim()
      : null,
  };
}

async function readJsonIfPresent(filePath) {
  try {
    const raw = await fsPromises.readFile(filePath, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

async function readTextIfPresent(filePath) {
  try {
    return await fsPromises.readFile(filePath, 'utf8');
  } catch {
    return '';
  }
}

async function loadRepoMetadata(workingDirectory) {
  const packageJson = await readJsonIfPresent(path.join(workingDirectory, 'package.json'));
  const readmeIntro = extractReadmeIntro(await readTextIfPresent(path.join(workingDirectory, 'README.md')));
  const rootEntries = await fsPromises.readdir(workingDirectory, { withFileTypes: true }).catch(() => []);
  const solutionFiles = rootEntries
    .filter((entry) => entry && typeof entry.name === 'string' && entry.isFile && entry.isFile() && entry.name.toLowerCase().endsWith('.sln'))
    .map((entry) => toRepoPath(entry.name));
  const repoName = typeof packageJson?.name === 'string' && packageJson.name.trim()
    ? packageJson.name.trim()
    : path.basename(workingDirectory);
  const description = typeof packageJson?.description === 'string' && packageJson.description.trim()
    ? packageJson.description.trim()
    : (readmeIntro || `Architecture study for ${repoName}.`);
  const packageMain = typeof packageJson?.main === 'string' && packageJson.main.trim()
    ? toRepoPath(packageJson.main)
    : null;
  const binFiles = packageJson?.bin && typeof packageJson.bin === 'object' && !Array.isArray(packageJson.bin)
    ? uniquePaths(Object.values(packageJson.bin))
    : [];

  return {
    name: repoName,
    description,
    package_main: packageMain,
    bin_files: binFiles,
    package_json: packageJson || null,
    solution_files: solutionFiles,
    dotnet_project: solutionFiles.length > 0 || fs.existsSync(path.join(workingDirectory, 'global.json')),
    python_project: fs.existsSync(path.join(workingDirectory, 'pyproject.toml'))
      || fs.existsSync(path.join(workingDirectory, 'requirements.txt'))
      || fs.existsSync(path.join(workingDirectory, 'setup.py')),
    has_powershell_build: fs.existsSync(path.join(workingDirectory, 'scripts', 'build.ps1')),
  };
}

function getPaths(workingDirectory) {
  return {
    studyDir: path.join(workingDirectory, STUDY_DIR),
    statePath: path.join(workingDirectory, STATE_FILE),
    moduleIndexPath: path.join(workingDirectory, MODULE_INDEX_FILE),
    knowledgePackPath: path.join(workingDirectory, KNOWLEDGE_PACK_FILE),
    deltaPath: path.join(workingDirectory, STUDY_DELTA_FILE),
    evaluationPath: path.join(workingDirectory, STUDY_EVALUATION_FILE),
    benchmarkPath: path.join(workingDirectory, STUDY_BENCHMARK_FILE_LOCAL),
    summaryPath: path.join(workingDirectory, SUMMARY_FILE),
  };
}

async function ensureStudyDocs(workingDirectory) {
  const paths = getPaths(workingDirectory);
  await fsPromises.mkdir(paths.studyDir, { recursive: true });

  if (!fs.existsSync(paths.summaryPath)) {
    await fsPromises.writeFile(paths.summaryPath, SUMMARY_PLACEHOLDER, 'utf8');
  }
  if (!fs.existsSync(paths.moduleIndexPath)) {
    await fsPromises.writeFile(paths.moduleIndexPath, '{"modules":[],"last_updated":null}\n', 'utf8');
  }
  if (!fs.existsSync(paths.knowledgePackPath)) {
    await fsPromises.writeFile(paths.knowledgePackPath, '{"version":3,"generated_at":null,"study_profile":{},"repo":{},"coverage":{},"artifacts":{},"entrypoints":[],"subsystems":[],"subsystem_relationships":[],"flows":[],"hotspots":[],"navigation_hints":[],"expertise":{"onramp":{},"invariants":[],"failure_modes":[],"canonical_traces":[],"test_matrix":[],"change_playbooks":[],"impact_guidance":[]}}\n', 'utf8');
  }
  if (!fs.existsSync(paths.deltaPath)) {
    await fsPromises.writeFile(paths.deltaPath, '{"version":1,"generated_at":null,"repo":{},"run":{},"coverage_delta":{},"significance":{"level":"none","score":0,"reasons":[]},"changed_files":{"repo_delta":[],"processed":[],"removed":[]},"changed_subsystems":[],"affected_flows":[],"invariant_hits":[],"failure_mode_hits":[],"hotspot_changes":{"entered":[],"exited":[],"touched":[]},"proposals":{"policy":{"allowed":false,"reason":"submission_disabled","threshold_level":"moderate","threshold_score":0,"suppressed_count":0},"suggested":[],"submitted":[],"errors":[]}}\n', 'utf8');
  }
  if (!fs.existsSync(paths.evaluationPath)) {
    await fsPromises.writeFile(paths.evaluationPath, '{"version":1,"generated_at":null,"repo":{},"summary":{"score":0,"grade":null,"readiness":"map_only","findings_count":0,"strengths_count":0,"indexed_percent":0},"checks":{},"strengths":[],"findings":[],"probes":[],"artifacts":{}}\n', 'utf8');
  }
  if (!fs.existsSync(paths.benchmarkPath)) {
    await fsPromises.writeFile(paths.benchmarkPath, '{"version":1,"generated_at":null,"repo":{},"summary":{"score":0,"grade":null,"readiness":"map_only","total_cases":0,"passed_cases":0,"partial_cases":0,"failed_cases":0,"delta_significance_level":"none","evaluation_grade":null},"findings":[],"cases":[],"artifacts":{}}\n', 'utf8');
  }
  if (!fs.existsSync(paths.statePath)) {
    await fsPromises.writeFile(paths.statePath, '{}\n', 'utf8');
  }

  return paths;
}

async function readStudyState(workingDirectory) {
  const paths = await ensureStudyDocs(workingDirectory);
  const raw = await fsPromises.readFile(paths.statePath, 'utf8');
  const parsed = raw.trim() ? JSON.parse(raw) : {};
  return { paths, state: normalizeState(parsed) };
}

async function writeStudyState(workingDirectory, state) {
  const paths = await ensureStudyDocs(workingDirectory);
  const normalized = normalizeState(state);
  await fsPromises.writeFile(paths.statePath, `${JSON.stringify(normalized, null, 2)}\n`, 'utf8');
  return { paths, state: normalized };
}

module.exports = {
  STUDY_DIR,
  STATE_FILE,
  MODULE_INDEX_FILE,
  KNOWLEDGE_PACK_FILE,
  STUDY_DELTA_FILE,
  STUDY_BENCHMARK_FILE_LOCAL,
  SUMMARY_FILE,
  SUMMARY_PLACEHOLDER,
  LOCAL_ONLY_STRATEGY,
  resolveWorkingDirectory,
  toRepoPath,
  uniqueStrings,
  uniquePaths,
  buildInitialState,
  normalizeState,
  normalizeModuleEntry,
  normalizeModuleIndex,
  readJsonIfPresent,
  readTextIfPresent,
  loadRepoMetadata,
  ensureStudyDocs,
  readStudyState,
  writeStudyState,
};
