'use strict';

function defaultToRepoPath(filePath) {
  return String(filePath || '').trim().replace(/\\/g, '/');
}

function defaultUniqueStrings(values) {
  const seen = new Set();
  const output = [];
  for (const value of Array.isArray(values) ? values : []) {
    const normalized = String(value || '').trim();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    output.push(normalized);
  }
  return output;
}

function createDefaultUniquePaths(toRepoPath) {
  return function uniquePaths(values) {
    const seen = new Set();
    const output = [];
    for (const value of Array.isArray(values) ? values : []) {
      const normalized = toRepoPath(value);
      if (!normalized || seen.has(normalized)) {
        continue;
      }
      seen.add(normalized);
      output.push(normalized);
    }
    return output;
  };
}

function defaultFormatInlineList(values) {
  const items = (values || []).filter(Boolean);
  if (items.length === 0) return '';
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
}

function createDefaultFormatCodeList(uniqueStrings, formatInlineList) {
  return function formatCodeList(values, maxItems = 3) {
    const items = uniqueStrings(values).slice(0, maxItems).map(value => `\`${value}\``);
    return formatInlineList(items);
  };
}

function toPercent(value, total) {
  if (!total) {
    return 0;
  }
  return Math.round((value / total) * 1000) / 10;
}

function createSummary(deps = {}) {
  const toRepoPath = typeof deps.toRepoPath === 'function' ? deps.toRepoPath : defaultToRepoPath;
  const uniqueStrings = typeof deps.uniqueStrings === 'function' ? deps.uniqueStrings : defaultUniqueStrings;
  const uniquePaths = typeof deps.uniquePaths === 'function' ? deps.uniquePaths : createDefaultUniquePaths(toRepoPath);
  const formatInlineList = typeof deps.formatInlineList === 'function'
    ? deps.formatInlineList
    : defaultFormatInlineList;
  const formatCodeList = typeof deps.formatCodeList === 'function'
    ? deps.formatCodeList
    : createDefaultFormatCodeList(uniqueStrings, formatInlineList);
  const SUMMARY_PLACEHOLDER = typeof deps.SUMMARY_PLACEHOLDER === 'string'
    ? deps.SUMMARY_PLACEHOLDER
    : 'auto-generated by study loop, no runs yet\n';
  const KNOWLEDGE_PACK_FILE = typeof deps.KNOWLEDGE_PACK_FILE === 'string'
    ? deps.KNOWLEDGE_PACK_FILE
    : 'docs/architecture/knowledge-pack.json';
  const STUDY_DELTA_FILE = typeof deps.STUDY_DELTA_FILE === 'string'
    ? deps.STUDY_DELTA_FILE
    : 'docs/architecture/study-delta.json';
  const MODULE_INDEX_FILE = typeof deps.MODULE_INDEX_FILE === 'string'
    ? deps.MODULE_INDEX_FILE
    : 'docs/architecture/module-index.json';
  const HOTSPOT_LIMIT = Number.isInteger(deps.HOTSPOT_LIMIT) && deps.HOTSPOT_LIMIT > 0 ? deps.HOTSPOT_LIMIT : 6;
  const NAVIGATION_HINT_LIMIT = Number.isInteger(deps.NAVIGATION_HINT_LIMIT) && deps.NAVIGATION_HINT_LIMIT > 0
    ? deps.NAVIGATION_HINT_LIMIT
    : 6;
  const SUMMARY_SUBSYSTEM_LIMIT = Number.isInteger(deps.SUMMARY_SUBSYSTEM_LIMIT) && deps.SUMMARY_SUBSYSTEM_LIMIT > 0
    ? deps.SUMMARY_SUBSYSTEM_LIMIT
    : 6;
  const SUMMARY_FLOW_LIMIT = Number.isInteger(deps.SUMMARY_FLOW_LIMIT) && deps.SUMMARY_FLOW_LIMIT > 0
    ? deps.SUMMARY_FLOW_LIMIT
    : 5;
  const SUMMARY_INVARIANT_LIMIT = Number.isInteger(deps.SUMMARY_INVARIANT_LIMIT) && deps.SUMMARY_INVARIANT_LIMIT > 0
    ? deps.SUMMARY_INVARIANT_LIMIT
    : 5;
  const SUMMARY_FAILURE_MODE_LIMIT = Number.isInteger(deps.SUMMARY_FAILURE_MODE_LIMIT) && deps.SUMMARY_FAILURE_MODE_LIMIT > 0
    ? deps.SUMMARY_FAILURE_MODE_LIMIT
    : 5;
  const SUMMARY_PLAYBOOK_LIMIT = Number.isInteger(deps.SUMMARY_PLAYBOOK_LIMIT) && deps.SUMMARY_PLAYBOOK_LIMIT > 0
    ? deps.SUMMARY_PLAYBOOK_LIMIT
    : 5;
  const SIGNIFICANCE_REASON_LIMIT = Number.isInteger(deps.SIGNIFICANCE_REASON_LIMIT) && deps.SIGNIFICANCE_REASON_LIMIT > 0
    ? deps.SIGNIFICANCE_REASON_LIMIT
    : 4;
  const LOCAL_ONLY_STRATEGY = typeof deps.LOCAL_ONLY_STRATEGY === 'string' && deps.LOCAL_ONLY_STRATEGY.trim()
    ? deps.LOCAL_ONLY_STRATEGY.trim()
    : 'local-deterministic';
  const DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL = typeof deps.DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL === 'string'
    && deps.DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL.trim()
    ? deps.DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL.trim()
    : 'moderate';
  const DEFAULT_PROPOSAL_MIN_SCORE = Number.isInteger(deps.DEFAULT_PROPOSAL_MIN_SCORE)
    ? deps.DEFAULT_PROPOSAL_MIN_SCORE
    : 0;

  function buildSummaryFromKnowledgePack(knowledgePack, studyDelta = null, studyEvaluation = null, studyBenchmark = null) {
    const repo = knowledgePack?.repo || {};
    const studyProfile = knowledgePack?.study_profile || {};
    const coverage = knowledgePack?.coverage || {};
    const subsystems = Array.isArray(knowledgePack?.subsystems) ? knowledgePack.subsystems : [];
    const flows = Array.isArray(knowledgePack?.flows) ? knowledgePack.flows : [];
    const hotspots = Array.isArray(knowledgePack?.hotspots) ? knowledgePack.hotspots : [];
    const entrypoints = Array.isArray(knowledgePack?.entrypoints) ? knowledgePack.entrypoints : [];
    const navigationHints = Array.isArray(knowledgePack?.navigation_hints) ? knowledgePack.navigation_hints : [];
    const expertise = knowledgePack?.expertise || {};
    const onramp = expertise?.onramp || {};
    const invariants = Array.isArray(expertise?.invariants) ? expertise.invariants : [];
    const failureModes = Array.isArray(expertise?.failure_modes) ? expertise.failure_modes : [];
    const changePlaybooks = Array.isArray(expertise?.change_playbooks) ? expertise.change_playbooks : [];
    const testMatrix = Array.isArray(expertise?.test_matrix) ? expertise.test_matrix : [];
    const impactGuidance = Array.isArray(expertise?.impact_guidance) ? expertise.impact_guidance : [];

    if (subsystems.length === 0 && entrypoints.length === 0) {
      return SUMMARY_PLACEHOLDER;
    }

    const lines = [
      `# ${repo.name || 'Repository'} Knowledge Primer`,
      '',
      repo.description || 'Local architecture study output.',
      '',
      `Coverage: ${coverage.indexed_modules ?? 0}/${coverage.tracked_files ?? 0} tracked files indexed (${coverage.indexed_percent ?? 0}%), ${(coverage.pending_files ?? 0)} pending.`,
      '',
      '## Key Artifacts',
      `- \`${KNOWLEDGE_PACK_FILE.replace(/\\/g, '/') }\` - machine-readable subsystem map, flows, hotspots, invariants, failure modes, traces, and change playbooks.`,
      `- \`${STUDY_DELTA_FILE.replace(/\\/g, '/') }\` - latest delta, significance score, changed seams, and follow-up task proposals.`,
      `- \`${MODULE_INDEX_FILE.replace(/\\/g, '/') }\` - per-file facts: purpose, exports, and dependencies.`,
    ];

    if (studyDelta && studyDelta.significance) {
      lines.push('', '## Latest Delta');
      lines.push(`- **Significance:** ${studyDelta.significance.level} (${studyDelta.significance.score}).`);
      if (Array.isArray(studyDelta.significance.reasons) && studyDelta.significance.reasons.length > 0) {
        studyDelta.significance.reasons.slice(0, SIGNIFICANCE_REASON_LIMIT).forEach((reason) => {
          lines.push(`- ${reason}`);
        });
      }
      if (Array.isArray(studyDelta.proposals?.suggested) && studyDelta.proposals.suggested.length > 0) {
        lines.push(`- **Suggested Follow-ups:** ${studyDelta.proposals.suggested.slice(0, 3).map(item => item.title).join('; ')}.`);
      }
    }

    if (studyEvaluation?.summary) {
      lines.push('', '## Pack Evaluation');
      lines.push(`- **Readiness:** ${studyEvaluation.summary.readiness} (${studyEvaluation.summary.grade || 'n/a'}, score ${studyEvaluation.summary.score ?? 0}).`);
      if (Array.isArray(studyEvaluation.strengths) && studyEvaluation.strengths.length > 0) {
        lines.push(`- **Strengths:** ${studyEvaluation.strengths.slice(0, 2).join(' ')}`);
      }
      if (Array.isArray(studyEvaluation.findings) && studyEvaluation.findings.length > 0) {
        studyEvaluation.findings.slice(0, 3).forEach((finding) => {
          lines.push(`- **Gap (${finding.severity}):** ${finding.message}`);
        });
      }
    }

    if (studyBenchmark?.summary) {
      lines.push('', '## Benchmark');
      lines.push(`- **Benchmark Readiness:** ${studyBenchmark.summary.readiness} (${studyBenchmark.summary.grade || 'n/a'}, score ${studyBenchmark.summary.score ?? 0}).`);
      lines.push(`- **Cases:** ${studyBenchmark.summary.passed_cases ?? 0} pass, ${studyBenchmark.summary.partial_cases ?? 0} partial, ${studyBenchmark.summary.failed_cases ?? 0} fail.`);
      if (Array.isArray(studyBenchmark.findings) && studyBenchmark.findings.length > 0) {
        studyBenchmark.findings.slice(0, 3).forEach((finding) => {
          lines.push(`- **Benchmark Gap (${finding.severity}):** ${finding.message}`);
        });
      }
    }

    if (studyProfile.label || onramp.summary) {
      lines.push('', '## LLM Onramp');
      if (studyProfile.label) {
        lines.push(`- **Profile:** ${studyProfile.label}. ${studyProfile.description || ''}`.trim());
      }
      if (onramp.summary) {
        lines.push(`- **Briefing:** ${onramp.summary}`);
      }
      if (Array.isArray(onramp.read_order) && onramp.read_order.length > 0) {
        lines.push(`- **Read Order:** ${formatCodeList(onramp.read_order, 6)}.`);
      }
    }

    if (entrypoints.length > 0) {
      lines.push('', '## Suggested Entry Points');
      entrypoints.slice(0, SUMMARY_SUBSYSTEM_LIMIT).forEach((entrypoint) => {
        lines.push(`- \`${entrypoint.file}\` - ${entrypoint.role}.`);
      });
    }

    if (flows.length > 0) {
      lines.push('', '## Primary Flows');
      flows.slice(0, SUMMARY_FLOW_LIMIT).forEach((flow) => {
        lines.push(`- **${flow.label}:** ${flow.summary} Start with ${formatCodeList(flow.files, 4)}.`);
      });
    }

    if (subsystems.length > 0) {
      lines.push('', '## Major Subsystems');
      subsystems.slice(0, SUMMARY_SUBSYSTEM_LIMIT).forEach((subsystem) => {
        lines.push(`- **${subsystem.label}:** ${subsystem.overview}`);
      });
    }

    if (invariants.length > 0) {
      lines.push('', '## Critical Invariants');
      invariants.slice(0, SUMMARY_INVARIANT_LIMIT).forEach((item) => {
        lines.push(`- **${item.label}:** ${item.statement} Read ${formatCodeList(item.evidence_files, 4)}.`);
      });
    }

    if (failureModes.length > 0) {
      lines.push('', '## Common Failure Modes');
      failureModes.slice(0, SUMMARY_FAILURE_MODE_LIMIT).forEach((item) => {
        lines.push(`- **${item.label}:** ${item.symptoms} Investigate ${formatCodeList(item.investigate_first, 4)} first.`);
      });
    }

    if (changePlaybooks.length > 0) {
      lines.push('', '## Change Playbooks');
      changePlaybooks.slice(0, SUMMARY_PLAYBOOK_LIMIT).forEach((item) => {
        lines.push(`- **${item.label}:** ${item.when_to_use} Start with ${formatCodeList(item.read_first, 4)}.`);
      });
    }

    if (impactGuidance.length > 0) {
      lines.push('', '## Change Impact Guidance');
      impactGuidance.slice(0, 4).forEach((item) => {
        lines.push(`- **${item.label}:** Recheck ${formatCodeList(item.related_files, 4)}. Validate with ${formatCodeList(item.validation_commands, 2)}.`);
      });
    }

    if (hotspots.length > 0) {
      lines.push('', '## Hotspots');
      hotspots.slice(0, HOTSPOT_LIMIT).forEach((hotspot) => {
        lines.push(`- \`${hotspot.file}\` - ${hotspot.reason}`);
      });
    }

    if (testMatrix.length > 0) {
      lines.push('', '## Representative Tests');
      testMatrix.slice(0, 4).forEach((item) => {
        lines.push(`- **${item.label}:** ${formatCodeList(item.tests, 4)}. ${item.rationale}`);
      });
    }

    if (navigationHints.length > 0) {
      lines.push('', '## Navigation Hints');
      navigationHints.slice(0, NAVIGATION_HINT_LIMIT).forEach((hint) => {
        lines.push(`- ${hint.question} Read ${formatCodeList(hint.read_first, 4)}. ${hint.rationale}`);
      });
    }

    return `${lines.join('\n')}\n`;
  }

  function buildStatusPayload(workingDirectory, state, currentSha) {
    return {
      working_directory: workingDirectory,
      last_sha: state.last_sha,
      current_sha: currentSha,
      last_task_id: state.last_task_id || null,
      run_count: state.run_count || 0,
      last_batch: uniquePaths(state.last_batch),
      last_run_at: state.last_run_at || null,
      last_completed_at: state.last_completed_at || null,
      last_result: state.last_result || null,
      last_error: state.last_error || null,
      tracked_count: state.file_counts?.tracked ?? state.tracked_files.length,
      pending_count: state.file_counts?.pending ?? state.pending_files.length,
      up_to_date_count: state.file_counts?.up_to_date ?? Math.max(0, state.tracked_files.length - state.pending_files.length),
      pending_files: uniquePaths(state.pending_files),
      index_strategy: state.index_strategy || LOCAL_ONLY_STRATEGY,
      summary_strategy: state.summary_strategy || LOCAL_ONLY_STRATEGY,
      last_processed_count: state.last_processed_count || 0,
      last_removed_count: state.last_removed_count || 0,
      last_summary_updated_at: state.last_summary_updated_at || null,
      knowledge_pack_updated_at: state.knowledge_pack_updated_at || null,
      module_entry_count: state.module_entry_count || 0,
      subsystem_count: state.subsystem_count || 0,
      flow_count: state.flow_count || 0,
      hotspot_count: state.hotspot_count || 0,
      invariant_count: state.invariant_count || 0,
      failure_mode_count: state.failure_mode_count || 0,
      trace_count: state.trace_count || 0,
      playbook_count: state.playbook_count || 0,
      test_area_count: state.test_area_count || 0,
      last_delta_updated_at: state.last_delta_updated_at || null,
      delta_significance_level: state.delta_significance_level || 'none',
      delta_significance_score: state.delta_significance_score || 0,
      proposal_count: state.proposal_count || 0,
      submitted_proposal_count: state.submitted_proposal_count || 0,
      proposal_significance_level: state.proposal_significance_level || DEFAULT_PROPOSAL_SIGNIFICANCE_LEVEL,
      proposal_min_score: state.proposal_min_score ?? DEFAULT_PROPOSAL_MIN_SCORE,
      evaluation_score: state.evaluation_score || 0,
      evaluation_grade: state.evaluation_grade || null,
      evaluation_readiness: state.evaluation_readiness || null,
      evaluation_findings_count: state.evaluation_findings_count || 0,
      evaluation_generated_at: state.evaluation_generated_at || null,
      benchmark_score: state.benchmark_score || 0,
      benchmark_grade: state.benchmark_grade || null,
      benchmark_readiness: state.benchmark_readiness || null,
      benchmark_findings_count: state.benchmark_findings_count || 0,
      benchmark_case_count: state.benchmark_case_count || 0,
      benchmark_generated_at: state.benchmark_generated_at || null,
    };
  }

  return {
    buildSummaryFromKnowledgePack,
    buildStatusPayload,
    toPercent,
  };
}

module.exports = { createSummary };
