'use strict';

const childProcess = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { benchmarkStudyArtifacts } = require('../integrations/codebase-study-engine');

const patchedExecFileSync = childProcess.execFileSync;
const patchedSpawnSync = childProcess.spawnSync;
const realExecFileSync = childProcess._realExecFileSync || childProcess.execFileSync;
const realSpawnSync = childProcess._realSpawnSync || childProcess.spawnSync;
const SUMMARY_PLACEHOLDER = 'auto-generated by study loop, no runs yet\n';
const GIT_TEST_ENV = {
  ...process.env,
  GIT_TERMINAL_PROMPT: '0',
  GIT_OPTIONAL_LOCKS: '0',
  GIT_CONFIG_NOSYSTEM: '1',
  GIT_AUTHOR_NAME: 'Study Test',
  GIT_AUTHOR_EMAIL: 'study@example.com',
  GIT_COMMITTER_NAME: 'Study Test',
  GIT_COMMITTER_EMAIL: 'study@example.com',
};

function installCjsModuleMock(modulePath, exportsValue) {
  const resolved = require.resolve(modulePath);
  require.cache[resolved] = {
    id: resolved,
    filename: resolved,
    loaded: true,
    exports: exportsValue,
  };
}

function resetCjsModule(modulePath) {
  try {
    delete require.cache[require.resolve(modulePath)];
  } catch {
    // Ignore modules that are not currently loaded.
  }
}

function runGit(cwd, args) {
  return realExecFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    windowsHide: true,
    stdio: ['ignore', 'pipe', 'pipe'],
    timeout: 10000,
    env: GIT_TEST_ENV,
  }).trim();
}

function writeRepoFile(repoDir, relativePath, content) {
  const fullPath = path.join(repoDir, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf8');
}

function createRepo(files) {
  const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'torque-study-'));
  runGit(repoDir, ['init']);
  runGit(repoDir, ['config', 'user.email', 'study@example.com']);
  runGit(repoDir, ['config', 'user.name', 'Study Test']);
  Object.entries(files).forEach(([relativePath, content]) => {
    writeRepoFile(repoDir, relativePath, content);
  });
  runGit(repoDir, ['add', '.']);
  runGit(repoDir, ['commit', '-m', 'initial', '--no-gpg-sign']);
  return repoDir;
}

function loadStudyModule(mocks) {
  [
    '../integrations/codebase-study',
    '../db/scheduling-automation',
  ].forEach(resetCjsModule);

  installCjsModuleMock('../db/scheduling-automation', {
    listApprovalRules: mocks.listApprovalRules,
    createApprovalRule: mocks.createApprovalRule,
    createApprovalRequest: mocks.createApprovalRequest,
  });

  childProcess.execFileSync = realExecFileSync;
  childProcess.spawnSync = realSpawnSync;
  try {
    return require('../integrations/codebase-study');
  } finally {
    childProcess.execFileSync = patchedExecFileSync;
    childProcess.spawnSync = patchedSpawnSync;
  }
}

function readModuleIndex(repoDir) {
  const moduleIndexPath = path.join(repoDir, 'docs', 'architecture', 'module-index.json');
  return JSON.parse(fs.readFileSync(moduleIndexPath, 'utf8'));
}

function readKnowledgePack(repoDir) {
  const knowledgePackPath = path.join(repoDir, 'docs', 'architecture', 'knowledge-pack.json');
  return JSON.parse(fs.readFileSync(knowledgePackPath, 'utf8'));
}

function readStudyDelta(repoDir) {
  const deltaPath = path.join(repoDir, 'docs', 'architecture', 'study-delta.json');
  return JSON.parse(fs.readFileSync(deltaPath, 'utf8'));
}

function readStudyEvaluation(repoDir) {
  const evaluationPath = path.join(repoDir, 'docs', 'architecture', 'study-evaluation.json');
  return JSON.parse(fs.readFileSync(evaluationPath, 'utf8'));
}

function readStudyBenchmark(repoDir) {
  const benchmarkPath = path.join(repoDir, 'docs', 'architecture', 'study-benchmark.json');
  return JSON.parse(fs.readFileSync(benchmarkPath, 'utf8'));
}

function readSummary(repoDir) {
  const summaryPath = path.join(repoDir, 'docs', 'architecture', 'SUMMARY.md');
  return fs.readFileSync(summaryPath, 'utf8');
}

describe('codebase study integration', () => {
  let repoDir;
  let schedulingAutomation;

  afterEach(() => {
    if (repoDir) {
      fs.rmSync(repoDir, { recursive: true, force: true });
      repoDir = null;
    }
    childProcess.execFileSync = patchedExecFileSync;
    childProcess.spawnSync = patchedSpawnSync;
    [
      '../integrations/codebase-study',
      '../db/scheduling-automation',
    ].forEach(resetCjsModule);
  });

  function createService(taskCoreOverrides = {}, options = {}) {
    schedulingAutomation = {
      listApprovalRules: vi.fn(() => []),
      createApprovalRule: vi.fn(() => 'study-rule-1'),
      createApprovalRequest: vi.fn((taskId) => `approval-for-${taskId}`),
    };

    const { createCodebaseStudy } = loadStudyModule(schedulingAutomation);

    const taskCore = {
      listTasks: vi.fn(() => []),
      getTask: vi.fn(() => ({ id: 'study-task-1', status: 'completed' })),
      createTask: vi.fn(),
      ...taskCoreOverrides,
    };

    return {
      service: createCodebaseStudy({
        db: {},
        taskCore,
        logger: {
          debug() {},
          info() {},
          warn() {},
          error() {},
        },
        batchSize: options.batchSize,
      }),
      taskCore,
      schedulingAutomation,
    };
  }

  it('skips when the queue already has running tasks', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
    });

    const { service } = createService({
      listTasks: vi.fn(() => [{ id: 'running-task', status: 'running' }]),
    });

    const result = await service.runStudyCycle(repoDir);

    expect(result).toEqual(expect.objectContaining({
      skipped: true,
      reason: 'queue_active',
      running_task_count: 1,
    }));
  });

  it('ignores the current scheduled wrapper task when checking the queue', async () => {
    repoDir = createRepo({
      'src/alpha.js': [
        'function alpha() { return 1; }',
        'module.exports = { alpha };',
        '',
      ].join('\n'),
    });

    const { service } = createService({
      listTasks: vi.fn(() => [{ id: 'scheduled-tool-task-1', status: 'running' }]),
    });

    const result = await service.runStudyCycle(repoDir, {
      currentTaskId: 'scheduled-tool-task-1',
    });

    expect(result.skipped).toBe(false);
    expect(result.task_status).toBe('completed');
    expect(result.last_result).toBe('completed_local');
  });

  it('updates module-index and summary locally without spawning child tasks', async () => {
    repoDir = createRepo({
      'src/alpha.js': [
        'function alpha() { return 1; }',
        'module.exports = { alpha };',
        '',
      ].join('\n'),
      'data/config.json': JSON.stringify({ ok: true, port: 3456 }, null, 2) + '\n',
    });

    const { service, taskCore } = createService();
    const result = await service.runStudyCycle(repoDir);

    expect(result.skipped).toBe(false);
    expect(result.task_status).toBe('completed');
    expect(result.last_result).toBe('completed_local');
    expect(result.pending_count).toBe(0);
    expect(result.module_entry_count).toBe(2);
    expect(result.docs_updated).toEqual(expect.objectContaining({
      module_entry_count: 2,
      module_entries_updated: 2,
      module_entries_removed: 0,
      subsystem_count: 2,
    }));
    expect(result.files_modified).toEqual([
      'docs/architecture/module-index.json',
      'docs/architecture/knowledge-pack.json',
      'docs/architecture/study-delta.json',
      'docs/architecture/study-evaluation.json',
      'docs/architecture/study-benchmark.json',
      'docs/architecture/SUMMARY.md',
      'docs/architecture/study-state.json',
    ]);
    expect(taskCore.createTask).not.toHaveBeenCalled();

    const moduleIndex = readModuleIndex(repoDir);
    expect(moduleIndex.modules.map(entry => entry.file).sort()).toEqual(['data/config.json', 'src/alpha.js']);
    const alphaEntry = moduleIndex.modules.find(entry => entry.file === 'src/alpha.js');
    expect(alphaEntry.exports).toContain('alpha');
    const configEntry = moduleIndex.modules.find(entry => entry.file === 'data/config.json');
    expect(configEntry.exports).toEqual(expect.arrayContaining(['ok', 'port']));

    const knowledgePack = readKnowledgePack(repoDir);
    expect(knowledgePack.version).toBe(3);
    expect(knowledgePack.study_profile.id).toBe('generic-javascript-repo');
    expect(knowledgePack.study_profile.reusable_strategy).toContain('artifact schema is generic');
    expect(knowledgePack.coverage).toEqual(expect.objectContaining({
      indexed_modules: 2,
      tracked_files: 2,
      pending_files: 0,
    }));
    expect(knowledgePack.subsystems.map(subsystem => subsystem.id).sort()).toEqual(['data-area', 'src-area']);
    expect(knowledgePack.hotspots).toHaveLength(2);
    expect(knowledgePack.navigation_hints.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.invariants.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.change_playbooks.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.impact_guidance.length).toBeGreaterThan(0);
    const studyDelta = readStudyDelta(repoDir);
    expect(studyDelta.version).toBe(1);
    expect(studyDelta.significance.level).toBe('baseline');
    expect(studyDelta.proposals.suggested).toEqual([]);
    const studyEvaluation = readStudyEvaluation(repoDir);
    expect(studyEvaluation.summary).toEqual(expect.objectContaining({
      score: expect.any(Number),
      grade: expect.any(String),
      readiness: expect.any(String),
    }));
    expect(studyEvaluation.probes.length).toBeGreaterThan(0);
    const studyBenchmark = readStudyBenchmark(repoDir);
    expect(studyBenchmark.summary).toEqual(expect.objectContaining({
      score: expect.any(Number),
      grade: expect.any(String),
      readiness: expect.any(String),
      total_cases: expect.any(Number),
    }));
    expect(studyBenchmark.cases.length).toBeGreaterThan(0);

    const summary = readSummary(repoDir);
    expect(summary).not.toBe('auto-generated by study loop, no runs yet\n');
    expect(summary).toContain('Knowledge Primer');
    expect(summary).toContain('## Major Subsystems');
    expect(summary).toContain('## Critical Invariants');
    expect(summary).toContain('study-delta.json');
    expect(summary).toContain('## Pack Evaluation');
    expect(summary).toContain('## Benchmark');
    expect(summary).toContain('## Latest Delta');
    expect(summary).toContain('knowledge-pack.json');
  });

  it('builds an LLM-ready knowledge pack with subsystem and flow hints for torque-like repos', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'mini-torque',
        description: 'Miniature TORQUE fixture for knowledge-pack testing.',
        main: 'server/index.js',
      }, null, 2) + '\n',
      'server/index.js': [
        'const dispatch = require("./api/v2-dispatch");',
        'const taskManager = require("./task-manager");',
        'module.exports = { start() { dispatch.handleV2CpSubmitTask?.(); return taskManager.startTask?.(); } };',
        '',
      ].join('\n'),
      'server/task-manager.js': [
        'const startup = require("./execution/task-startup");',
        'const router = require("./execution/provider-router");',
        'const finalizer = require("./execution/task-finalizer");',
        'exports.startTask = function startTask() {',
        '  startup.prepareTask?.();',
        '  router.routeTask?.();',
        '  return finalizer.finalize?.();',
        '};',
        '',
      ].join('\n'),
      'server/api/v2-dispatch.js': 'const taskHandler = require("../handlers/task/index");\nexports.handleV2CpSubmitTask = () => taskHandler.submit?.();\n',
      'server/handlers/task/index.js': 'exports.submit = () => null;\n',
      'server/execution/task-startup.js': 'exports.prepareTask = () => null;\n',
      'server/execution/provider-router.js': 'const retry = require("./fallback-retry");\nexports.routeTask = () => retry.retryTask?.();\n',
      'server/execution/fallback-retry.js': 'exports.retryTask = () => null;\n',
      'server/execution/process-lifecycle.js': 'exports.cleanup = () => null;\n',
      'server/execution/task-finalizer.js': 'const pipeline = require("./completion-pipeline");\nexports.finalize = () => pipeline.handlePostCompletion?.();\n',
      'server/execution/completion-pipeline.js': 'exports.handlePostCompletion = () => null;\n',
      'server/execution/workflow-runtime.js': 'exports.advanceWorkflow = () => null;\n',
      'server/execution/schedule-runner.js': 'exports.executeScheduledTask = () => null;\n',
      'server/handlers/workflow/index.js': 'exports.createWorkflow = () => null;\n',
      'server/handlers/workflow/dag.js': 'exports.buildDag = () => null;\n',
      'server/handlers/workflow/await.js': 'exports.awaitWorkflow = () => null;\n',
      'server/db/cron-scheduling.js': 'exports.createCronScheduledTask = () => null;\n',
      'server/maintenance/scheduler.js': 'exports.startMaintenanceScheduler = () => null;\n',
      'server/tools.js': 'exports.handleToolCall = () => null;\n',
      'server/plugins/snapscope/plugin.js': 'exports.activate = () => null;\n',
      'server/contracts/peek.js': 'exports.contract = () => null;\n',
      'server/tests/task-manager.test.js': 'const taskManager = require("../task-manager");\nexports.taskLifecycle = () => taskManager.startTask();\n',
      'server/tests/v2-dispatch.test.js': 'const dispatch = require("../api/v2-dispatch");\nexports.dispatchFlow = () => dispatch.handleV2CpSubmitTask();\n',
      'dashboard/src/main.jsx': 'export function mountDashboard() { return null; }\n',
      'dashboard/src/App.jsx': 'export default function App() { return null; }\n',
    });

    const { service, taskCore, schedulingAutomation } = createService();
    await service.runStudyCycle(repoDir);

    const knowledgePack = readKnowledgePack(repoDir);
    expect(knowledgePack.study_profile.id).toBe('torque-control-plane');
    expect(knowledgePack.entrypoints.map(entrypoint => entrypoint.file)).toEqual(expect.arrayContaining([
      'server/index.js',
      'server/task-manager.js',
      'dashboard/src/main.jsx',
    ]));
    expect(knowledgePack.subsystems.map(subsystem => subsystem.id)).toEqual(expect.arrayContaining([
      'control-plane-api',
      'task-execution',
      'workflow-orchestration',
      'dashboard-ui',
      'server-plugins-area',
      'server-contracts-area',
    ]));
    expect(knowledgePack.subsystems[0].id).toBe('control-plane-api');
    const validationSubsystem = knowledgePack.subsystems.find(subsystem => subsystem.id === 'validation-tests');
    expect(validationSubsystem.overview).not.toContain('Key exports:');
    expect(knowledgePack.flows.map(flow => flow.id)).toEqual(expect.arrayContaining([
      'task-lifecycle',
      'workflow-lifecycle',
      'scheduled-automation',
      'tool-dispatch',
    ]));
    expect(knowledgePack.navigation_hints.map(hint => hint.question)).toContain('How does a task move from submission to completion?');
    expect(knowledgePack.expertise.onramp.read_order).toContain('server/index.js');
    expect(knowledgePack.expertise.invariants.some(item => item.statement.includes('delegate into handlers and the task manager'))).toBe(true);
    expect(knowledgePack.expertise.failure_modes.map(item => item.label)).toContain('Bypassed finalization');
    expect(knowledgePack.expertise.canonical_traces.map(item => item.id)).toContain('task-lifecycle');
    expect(knowledgePack.expertise.change_playbooks.map(item => item.label)).toContain('Editing Control-plane API');
    expect(knowledgePack.expertise.change_playbooks.some(item => item.validation_commands.length > 0)).toBe(true);
    expect(knowledgePack.expertise.test_matrix.some(item => item.scope_id === 'task-lifecycle')).toBe(true);
    expect(knowledgePack.expertise.impact_guidance.some(item => item.validation_commands.length > 0)).toBe(true);

    const summary = readSummary(repoDir);
    expect(summary).toContain('## LLM Onramp');
    expect(summary).toContain('## Primary Flows');
    expect(summary).toContain('Task lifecycle');
    expect(summary).toContain('## Critical Invariants');
    expect(summary).toContain('## Common Failure Modes');
    expect(summary).toContain('## Change Playbooks');
    expect(summary).toContain('## Change Impact Guidance');
    expect(summary).toContain('## Representative Tests');
    expect(summary).toContain('## Navigation Hints');
    expect(summary).not.toContain('**Validation and tests:**');
  });

  it('writes a significant study delta and suggested proposals for core repo changes', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'mini-torque',
        description: 'Miniature TORQUE fixture for delta testing.',
        main: 'server/index.js',
      }, null, 2) + '\n',
      'server/index.js': 'const dispatch = require("./api/v2-dispatch");\nmodule.exports = { start() { return dispatch.handleV2CpSubmitTask?.(); } };\n',
      'server/task-manager.js': 'const finalizer = require("./execution/task-finalizer");\nexports.startTask = () => finalizer.finalize?.();\n',
      'server/api/v2-dispatch.js': 'const taskHandler = require("../handlers/task/index");\nexports.handleV2CpSubmitTask = () => taskHandler.submit?.();\n',
      'server/handlers/task/index.js': 'exports.submit = () => null;\n',
      'server/execution/task-startup.js': 'exports.prepareTask = () => null;\n',
      'server/execution/provider-router.js': 'exports.routeTask = () => null;\n',
      'server/execution/task-finalizer.js': 'exports.finalize = () => null;\n',
      'server/execution/completion-pipeline.js': 'exports.handlePostCompletion = () => null;\n',
      'server/execution/workflow-runtime.js': 'exports.advanceWorkflow = () => null;\n',
      'server/execution/schedule-runner.js': 'exports.executeScheduledTask = () => null;\n',
      'server/handlers/workflow/index.js': 'exports.createWorkflow = () => null;\n',
      'server/handlers/workflow/dag.js': 'exports.buildDag = () => null;\n',
      'server/handlers/workflow/await.js': 'exports.awaitWorkflow = () => null;\n',
      'server/db/cron-scheduling.js': 'exports.createCronScheduledTask = () => null;\n',
      'server/maintenance/scheduler.js': 'exports.startMaintenanceScheduler = () => null;\n',
      'server/tools.js': 'exports.handleToolCall = () => null;\n',
      'server/tests/task-manager.test.js': 'const taskManager = require("../task-manager");\nexports.taskLifecycle = () => taskManager.startTask();\n',
    });

    const { service, taskCore, schedulingAutomation } = createService();
    await service.runStudyCycle(repoDir);

    writeRepoFile(repoDir, 'server/task-manager.js', [
      'const startup = require("./execution/task-startup");',
      'const finalizer = require("./execution/task-finalizer");',
      'exports.startTask = () => {',
      '  startup.prepareTask?.();',
      '  return finalizer.finalize?.();',
      '};',
      '',
    ].join('\n'));
    writeRepoFile(repoDir, 'server/api/v2-dispatch.js', 'const taskHandler = require("../handlers/task/index");\nexports.handleV2CpSubmitTask = () => taskHandler.submit?.("delta");\n');
    runGit(repoDir, ['add', '.']);
    runGit(repoDir, ['commit', '-m', 'delta']);

    const result = await service.runStudyCycle(repoDir);
    const studyDelta = readStudyDelta(repoDir);

    expect(result.delta_significance_level).not.toBe('none');
    expect(studyDelta.changed_files.repo_delta).toEqual(expect.arrayContaining([
      'server/api/v2-dispatch.js',
      'server/task-manager.js',
    ]));
    expect(studyDelta.affected_flows.map(item => item.id)).toContain('task-lifecycle');
    expect(studyDelta.invariant_hits.length).toBeGreaterThan(0);
    expect(studyDelta.failure_mode_hits.length).toBeGreaterThan(0);
    expect(studyDelta.proposals.suggested.length).toBeGreaterThan(0);
    expect(studyDelta.proposals.suggested[0].title).toContain('Review');
  });

  it('submits bounded follow-up tasks when requested', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'mini-torque',
        description: 'Miniature TORQUE fixture for proposal submission testing.',
        main: 'server/index.js',
      }, null, 2) + '\n',
      'server/index.js': 'const dispatch = require("./api/v2-dispatch");\nmodule.exports = { start() { return dispatch.handleV2CpSubmitTask?.(); } };\n',
      'server/task-manager.js': 'const finalizer = require("./execution/task-finalizer");\nexports.startTask = () => finalizer.finalize?.();\n',
      'server/api/v2-dispatch.js': 'const taskHandler = require("../handlers/task/index");\nexports.handleV2CpSubmitTask = () => taskHandler.submit?.();\n',
      'server/handlers/task/index.js': 'exports.submit = () => null;\n',
      'server/execution/task-startup.js': 'exports.prepareTask = () => null;\n',
      'server/execution/provider-router.js': 'exports.routeTask = () => null;\n',
      'server/execution/task-finalizer.js': 'exports.finalize = () => null;\n',
      'server/execution/completion-pipeline.js': 'exports.handlePostCompletion = () => null;\n',
      'server/execution/workflow-runtime.js': 'exports.advanceWorkflow = () => null;\n',
      'server/execution/schedule-runner.js': 'exports.executeScheduledTask = () => null;\n',
      'server/handlers/workflow/index.js': 'exports.createWorkflow = () => null;\n',
      'server/handlers/workflow/dag.js': 'exports.buildDag = () => null;\n',
      'server/handlers/workflow/await.js': 'exports.awaitWorkflow = () => null;\n',
      'server/db/cron-scheduling.js': 'exports.createCronScheduledTask = () => null;\n',
      'server/maintenance/scheduler.js': 'exports.startMaintenanceScheduler = () => null;\n',
      'server/tools.js': 'exports.handleToolCall = () => null;\n',
      'server/tests/task-manager.test.js': 'const taskManager = require("../task-manager");\nexports.taskLifecycle = () => taskManager.startTask();\n',
    });

    const { service, taskCore, schedulingAutomation } = createService();
    await service.runStudyCycle(repoDir);

    writeRepoFile(repoDir, 'server/task-manager.js', [
      'const startup = require("./execution/task-startup");',
      'const finalizer = require("./execution/task-finalizer");',
      'exports.startTask = () => {',
      '  startup.prepareTask?.();',
      '  return finalizer.finalize?.();',
      '};',
      '',
    ].join('\n'));
    runGit(repoDir, ['add', '.']);
    runGit(repoDir, ['commit', '-m', 'delta']);

    const result = await service.runStudyCycle(repoDir, {
      submitProposals: true,
      proposalLimit: 1,
      proposalSignificanceLevel: 'low',
      proposalMinScore: 1,
      project: 'mini-torque',
    });
    const studyDelta = readStudyDelta(repoDir);

    expect(taskCore.createTask).toHaveBeenCalledTimes(1);
    expect(taskCore.createTask.mock.calls[0][0]).toEqual(expect.objectContaining({
      status: 'pending',
      project: 'mini-torque',
      approval_status: 'pending',
      task_description: expect.stringContaining('[Study Proposal]'),
      metadata: expect.objectContaining({
        version_intent: 'internal',
            study_proposal: expect.objectContaining({
              title: expect.any(String),
              validation_commands: expect.any(Array),
              trace: expect.objectContaining({
                delta_significance_level: expect.any(String),
            delta_significance_score: expect.any(Number),
            study_delta_generated_at: expect.any(String),
            study_delta_path: 'docs/architecture/study-delta.json',
          }),
        }),
      }),
    }));
    expect(schedulingAutomation.createApprovalRule).toHaveBeenCalledTimes(1);
    expect(schedulingAutomation.createApprovalRequest).toHaveBeenCalledTimes(1);
    expect(result.submitted_proposal_count).toBe(1);
    expect(result.proposal_significance_level).toBe('low');
    expect(result.proposal_min_score).toBe(1);
    expect(studyDelta.proposals.submitted).toEqual([
      expect.objectContaining({
        title: expect.any(String),
        task_id: expect.any(String),
        approval_id: expect.stringContaining('approval-for-'),
      }),
    ]);
  });

  it('holds study proposals when the delta score is below the configured threshold', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'mini-torque',
        description: 'Miniature TORQUE fixture for proposal threshold testing.',
        main: 'server/index.js',
      }, null, 2) + '\n',
      'server/index.js': 'const dispatch = require("./api/v2-dispatch");\nmodule.exports = { start() { return dispatch.handleV2CpSubmitTask?.(); } };\n',
      'server/task-manager.js': 'exports.startTask = () => null;\n',
      'server/api/v2-dispatch.js': 'exports.handleV2CpSubmitTask = () => null;\n',
      'server/execution/provider-router.js': 'exports.routeTask = () => null;\n',
      'server/execution/task-finalizer.js': 'exports.finalize = () => null;\n',
      'server/execution/completion-pipeline.js': 'exports.handlePostCompletion = () => null;\n',
      'server/tests/task-manager.test.js': 'exports.taskLifecycle = () => null;\n',
    });

    const { service, taskCore, schedulingAutomation } = createService();
    await service.runStudyCycle(repoDir);

    writeRepoFile(repoDir, 'server/task-manager.js', 'exports.startTask = () => "delta";\n');
    runGit(repoDir, ['add', '.']);
    runGit(repoDir, ['commit', '-m', 'delta']);

    const result = await service.runStudyCycle(repoDir, {
      submitProposals: true,
      proposalSignificanceLevel: 'critical',
      proposalMinScore: 999,
      project: 'mini-torque',
    });
    const studyDelta = readStudyDelta(repoDir);

    expect(taskCore.createTask).not.toHaveBeenCalled();
    expect(schedulingAutomation.createApprovalRequest).not.toHaveBeenCalled();
    expect(result.submitted_proposal_count).toBe(0);
    expect(result.proposal_significance_level).toBe('critical');
    expect(result.proposal_min_score).toBe(999);
    expect(studyDelta.proposals.suggested.length).toBeGreaterThan(0);
    expect(studyDelta.proposals.submitted).toEqual([]);
  });

  it('suppresses duplicate study proposals that already exist in the queue', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'mini-torque',
        description: 'Miniature TORQUE fixture for proposal dedupe testing.',
        main: 'server/index.js',
      }, null, 2) + '\n',
      'server/index.js': 'const dispatch = require("./api/v2-dispatch");\nmodule.exports = { start() { return dispatch.handleV2CpSubmitTask?.(); } };\n',
      'server/task-manager.js': 'const finalizer = require("./execution/task-finalizer");\nexports.startTask = () => finalizer.finalize?.();\n',
      'server/api/v2-dispatch.js': 'exports.handleV2CpSubmitTask = () => null;\n',
      'server/execution/task-finalizer.js': 'exports.finalize = () => null;\n',
      'server/execution/completion-pipeline.js': 'exports.handlePostCompletion = () => null;\n',
      'server/tests/task-manager.test.js': 'exports.taskLifecycle = () => null;\n',
    });

    let existingProposalKey = null;
    const initialSha = runGit(repoDir, ['rev-parse', 'HEAD']);
    const { service, taskCore } = createService({
      listTasks: vi.fn((options = {}) => {
        if (options.status === 'running') {
          return [];
        }
        if (options.tag === 'study-delta-proposal' && existingProposalKey) {
          return [
            {
              id: 'existing-study-task',
              status: 'pending',
              approval_status: 'pending',
              metadata: JSON.stringify({
                study_proposal: {
                  key: existingProposalKey,
                },
              }),
            },
          ];
        }
        return [];
      }),
    });
    await service.runStudyCycle(repoDir);

    writeRepoFile(repoDir, 'server/task-manager.js', [
      'const startup = require("./execution/task-startup");',
      'const finalizer = require("./execution/task-finalizer");',
      'exports.startTask = () => {',
      '  startup.prepareTask?.();',
      '  return finalizer.finalize?.();',
      '};',
      '',
    ].join('\n'));
    writeRepoFile(repoDir, 'server/execution/task-startup.js', 'exports.prepareTask = () => null;\n');
    runGit(repoDir, ['add', '.']);
    runGit(repoDir, ['commit', '-m', 'delta']);

    await service.runStudyCycle(repoDir, {
      submitProposals: false,
      project: 'mini-torque',
    });
    existingProposalKey = readStudyDelta(repoDir).proposals?.suggested?.[0]?.key || null;
    expect(existingProposalKey).toBeTruthy();

    const statePath = path.join(repoDir, 'docs', 'architecture', 'study-state.json');
    const persistedState = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    persistedState.last_sha = initialSha;
    fs.writeFileSync(statePath, `${JSON.stringify(persistedState, null, 2)}\n`, 'utf8');

    await service.runStudyCycle(repoDir, {
      submitProposals: true,
      proposalSignificanceLevel: 'low',
      project: 'mini-torque',
    });
    const studyDelta = readStudyDelta(repoDir);

    const submittedKeys = taskCore.createTask.mock.calls.map(([task]) => task?.metadata?.study_proposal?.key).filter(Boolean);
    expect(submittedKeys).not.toContain(existingProposalKey);
    expect(studyDelta.proposals.errors).toEqual(expect.arrayContaining([
      expect.objectContaining({
        existing_task_id: 'existing-study-task',
      }),
    ]));
  });

  it('detects delta files from the previous study sha and preserves earlier module entries', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
      'src/beta.ts': 'export const beta = 2;\n',
      'data/config.json': '{"ok":true}\n',
    });

    const { service } = createService();
    const firstRun = await service.runStudyCycle(repoDir);
    expect(firstRun.batch_files.sort()).toEqual(['data/config.json', 'src/alpha.js', 'src/beta.ts']);

    writeRepoFile(repoDir, 'src/alpha.js', 'module.exports = 42;\n');
    writeRepoFile(repoDir, 'src/gamma.js', 'exports.gamma = 3;\n');
    writeRepoFile(repoDir, 'README.md', '# ignored\n');
    runGit(repoDir, ['add', '.']);
    runGit(repoDir, ['commit', '-m', 'delta']);

    const secondRun = await service.runStudyCycle(repoDir);

    expect(secondRun.batch_files.sort()).toEqual(['src/alpha.js', 'src/gamma.js']);
    expect(secondRun.last_result).toBe('completed_local');

    const moduleIndex = readModuleIndex(repoDir);
    expect(moduleIndex.modules.map(entry => entry.file).sort()).toEqual([
      'data/config.json',
      'src/alpha.js',
      'src/beta.ts',
      'src/gamma.js',
    ]);
  });

  it('uses the configured local batch size and persists backlog until later runs', async () => {
    repoDir = createRepo({
      'src/a.js': 'module.exports = "a";\n',
      'src/b.js': 'module.exports = "b";\n',
      'src/c.js': 'module.exports = "c";\n',
      'src/d.js': 'module.exports = "d";\n',
      'src/e.js': 'module.exports = "e";\n',
      'src/f.js': 'module.exports = "f";\n',
      'src/g.js': 'module.exports = "g";\n',
    });

    const { service } = createService({}, { batchSize: 5 });
    const firstRun = await service.runStudyCycle(repoDir);
    expect(firstRun.batch_files).toHaveLength(5);
    expect(firstRun.pending_count).toBe(2);
    expect(firstRun.last_result).toBe('partial_local');
    expect(firstRun.last_processed_count).toBe(5);

    const statePath = path.join(repoDir, 'docs', 'architecture', 'study-state.json');
    const persistedAfterFirstRun = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    expect(persistedAfterFirstRun.run_count).toBe(1);
    expect(persistedAfterFirstRun.pending_files).toHaveLength(2);
    expect(persistedAfterFirstRun.last_sha).toBe(runGit(repoDir, ['rev-parse', 'HEAD']));

    const secondRun = await service.runStudyCycle(repoDir);
    expect(secondRun.pending_count).toBe(0);
    expect(secondRun.last_result).toBe('completed_local');

    const status = await service.getStudyStatus(repoDir);
    expect(status.run_count).toBe(2);
    expect(status.pending_count).toBe(0);
    expect(status.tracked_count).toBe(7);
    expect(status.module_entry_count).toBe(7);
  });

  it('uses multiple local batches for manual runs', async () => {
    repoDir = createRepo({
      'src/a.js': 'module.exports = "a";\n',
      'src/b.js': 'module.exports = "b";\n',
      'src/c.js': 'module.exports = "c";\n',
      'src/d.js': 'module.exports = "d";\n',
      'src/e.js': 'module.exports = "e";\n',
      'src/f.js': 'module.exports = "f";\n',
      'src/g.js': 'module.exports = "g";\n',
    });

    const { service } = createService({}, { batchSize: 5 });
    const result = await service.runStudyCycle(repoDir, {
      manualRunNow: true,
    });

    expect(result.last_result).toBe('completed_local');
    expect(result.pending_count).toBe(0);
    expect(result.last_processed_count).toBe(7);
    expect(result.batch_count).toBe(2);
  });

  it('removes deleted files from the module index on later runs', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
      'src/beta.js': 'module.exports = 2;\n',
    });

    const { service } = createService();
    await service.runStudyCycle(repoDir);

    fs.rmSync(path.join(repoDir, 'src', 'beta.js'));
    runGit(repoDir, ['add', '-A']);
    runGit(repoDir, ['commit', '-m', 'remove beta']);

    const secondRun = await service.runStudyCycle(repoDir);

    expect(secondRun.batch_files).toHaveLength(0);
    expect(secondRun.removed_files).toEqual(['src/beta.js']);
    expect(secondRun.last_removed_count).toBe(1);

    const moduleIndex = readModuleIndex(repoDir);
    expect(moduleIndex.modules.map(entry => entry.file)).toEqual(['src/alpha.js']);
  });

  it('refreshes summary and knowledge-pack artifacts even when the repo is already up to date', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
    });

    const { service } = createService();
    await service.runStudyCycle(repoDir);

    fs.writeFileSync(path.join(repoDir, 'docs', 'architecture', 'SUMMARY.md'), SUMMARY_PLACEHOLDER, 'utf8');
    fs.rmSync(path.join(repoDir, 'docs', 'architecture', 'knowledge-pack.json'), { force: true });
    fs.rmSync(path.join(repoDir, 'docs', 'architecture', 'study-delta.json'), { force: true });
    fs.rmSync(path.join(repoDir, 'docs', 'architecture', 'study-evaluation.json'), { force: true });
    fs.rmSync(path.join(repoDir, 'docs', 'architecture', 'study-benchmark.json'), { force: true });

    const result = await service.runStudyCycle(repoDir);

    expect(result.skipped).toBe(true);
    expect(result.reason).toBe('up_to_date');
    expect(result.module_entry_count).toBe(1);
    expect(result.subsystem_count).toBeGreaterThan(0);
    expect(result.knowledge_pack_updated_at).toBeTruthy();
    expect(result.invariant_count).toBeGreaterThan(0);
    expect(result.playbook_count).toBeGreaterThan(0);

    const knowledgePack = readKnowledgePack(repoDir);
    expect(knowledgePack.coverage.indexed_modules).toBe(1);
    expect(knowledgePack.expertise.invariants.length).toBeGreaterThan(0);
    const studyDelta = readStudyDelta(repoDir);
    expect(studyDelta.significance.level).toBe('none');
    const studyEvaluation = readStudyEvaluation(repoDir);
    expect(studyEvaluation.summary.score).toBeGreaterThan(0);
    const studyBenchmark = readStudyBenchmark(repoDir);
    expect(studyBenchmark.summary.score).toBeGreaterThan(0);

    const summary = readSummary(repoDir);
    expect(summary).not.toBe(SUMMARY_PLACEHOLDER);
    expect(summary).toContain('Knowledge Primer');
    expect(summary).toContain('## Critical Invariants');
    expect(summary).toContain('## Benchmark');
  });

  it('evaluates the existing study artifacts without rerunning the study loop', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
      'src/beta.js': 'module.exports = 2;\n',
    });

    const { service } = createService();
    await service.runStudyCycle(repoDir);

    const result = await service.evaluateStudy(repoDir);
    const studyEvaluation = readStudyEvaluation(repoDir);

    expect(result.study_evaluation.summary).toEqual(expect.objectContaining({
      score: expect.any(Number),
      readiness: expect.any(String),
    }));
    expect(result.study_benchmark.summary).toEqual(expect.objectContaining({
      score: expect.any(Number),
      readiness: expect.any(String),
    }));
    expect(result.files_modified).toEqual([
      'docs/architecture/study-evaluation.json',
      'docs/architecture/study-benchmark.json',
    ]);
    expect(studyEvaluation.summary.score).toBe(result.study_evaluation.summary.score);
    const studyBenchmark = readStudyBenchmark(repoDir);
    expect(studyBenchmark.summary.score).toBe(result.study_benchmark.summary.score);
  });

  it('benchmarks the existing study artifacts without rerunning the study loop', async () => {
    repoDir = createRepo({
      'src/alpha.js': 'module.exports = 1;\n',
      'src/beta.js': 'module.exports = 2;\n',
    });

    const { service } = createService();
    await service.runStudyCycle(repoDir);

    const result = await service.benchmarkStudy(repoDir);
    const studyBenchmark = readStudyBenchmark(repoDir);

    expect(result.study_benchmark.summary).toEqual(expect.objectContaining({
      score: expect.any(Number),
      grade: expect.any(String),
      readiness: expect.any(String),
    }));
    expect(result.files_modified).toEqual(['docs/architecture/study-benchmark.json']);
    expect(studyBenchmark.summary.score).toBe(result.study_benchmark.summary.score);
  });

  it('benchmarks invariants and playbooks using shared evidence fields', () => {
    const knowledgePack = {
      repo: {
        name: 'generic-study-target',
      },
      study_profile: {
        id: 'generic-javascript-repo',
      },
      flows: [
        {
          id: 'main-flow',
          label: 'Main flow',
          files: ['src/entry.js'],
          steps: [
            { label: 'Prepare', files: ['src/prepare.js'] },
            { label: 'Finalize', files: ['src/finalize.js'] },
          ],
          questions_it_answers: ['How does the main flow work?'],
        },
      ],
      expertise: {
        invariants: [
          {
            id: 'main-flow:1',
            label: 'Main flow',
            statement: 'Core flow edits should stay inside the shared pipeline.',
            why_it_matters: 'Downstream callers rely on one lifecycle seam.',
            evidence_files: ['src/entry.js', 'src/prepare.js', 'src/finalize.js'],
            related_tests: ['tests/main-flow.test.js'],
          },
        ],
        change_playbooks: [
          {
            id: 'main-flow-playbook',
            label: 'Editing Main flow',
            read_first: ['src/entry.js'],
            inspect_also: ['src/prepare.js', 'src/finalize.js'],
            edit_surface: ['src/entry.js', 'src/prepare.js', 'src/finalize.js'],
            related_tests: ['tests/main-flow.test.js', 'tests/finalize.test.js'],
            validation_commands: ['npx vitest run tests/main-flow.test.js tests/finalize.test.js'],
            invariants_to_recheck: [
              {
                statement: 'Core flow edits should stay inside the shared pipeline.',
              },
            ],
          },
        ],
        impact_guidance: [
          {
            scope_id: 'main-flow',
            related_files: ['src/entry.js', 'src/prepare.js', 'src/finalize.js'],
            related_tests: ['tests/main-flow.test.js', 'tests/finalize.test.js'],
          },
        ],
      },
    };
    const moduleIndex = {
      modules: [
        { file: 'src/entry.js', purpose: 'Entry', exports: ['run'], deps: ['src/prepare.js'] },
        { file: 'src/prepare.js', purpose: 'Prepare', exports: ['prepare'], deps: [] },
        { file: 'src/finalize.js', purpose: 'Finalize', exports: ['finalize'], deps: [] },
        { file: 'tests/main-flow.test.js', purpose: 'Main flow test', exports: [], deps: ['src/entry.js'] },
        { file: 'tests/finalize.test.js', purpose: 'Finalize test', exports: [], deps: ['src/finalize.js'] },
      ],
    };

    const benchmark = benchmarkStudyArtifacts({
      knowledgePack,
      studyDelta: { significance: { level: 'none' } },
      studyEvaluation: { summary: { grade: 'A' } },
      moduleIndex,
      workingDirectory: 'C:/tmp/generic-study-target',
    });

    const invariantCase = benchmark.cases.find((item) => item.scope_type === 'invariant');
    const playbookCase = benchmark.cases.find((item) => item.scope_type === 'change_playbook');

    expect(invariantCase).toEqual(expect.objectContaining({
      verdict: 'pass',
      answerability: 'strong',
    }));
    expect(invariantCase.source_grounded_answer.map((item) => item.file)).toEqual(expect.arrayContaining([
      'src/entry.js',
      'src/prepare.js',
    ]));
    expect(playbookCase.pack_coverage).toEqual(expect.objectContaining({
      coverage_ratio: 1,
    }));
    expect(benchmark.findings).toEqual([]);
    expect(benchmark.summary.readiness).toBe('expert_ready');
  });

  it('bootstraps the study with a reusable profile plan and initial artifacts', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'bootstrap-repo',
        description: 'Bootstrap target for study planning.',
      }, null, 2) + '\n',
      'src/index.js': 'module.exports = { run() { return true; } };\n',
      'server/index.js': 'module.exports = { start() { return true; } };\n',
    });

    const { service } = createService();
    const result = await service.bootstrapStudy(repoDir, {
      project: 'bootstrap-repo',
      scheduleName: 'codebase-study:bootstrap-repo',
      submitProposals: true,
      proposalLimit: 3,
      initialMaxBatches: 4,
    });

    expect(result.bootstrap_plan).toEqual(expect.objectContaining({
      repo: expect.objectContaining({
        name: 'bootstrap-repo',
        project: 'bootstrap-repo',
      }),
      study_profile: expect.objectContaining({
        id: expect.any(String),
        label: expect.any(String),
      }),
      recommendations: expect.objectContaining({
        run_initial_study: true,
        run_benchmark: true,
        create_schedule: true,
        initial_run: expect.objectContaining({
          max_batches: 4,
        }),
        schedule: expect.objectContaining({
          name: 'codebase-study:bootstrap-repo',
          submit_proposals: true,
          proposal_limit: 3,
        }),
      }),
      steps: expect.any(Array),
    }));
    expect(result.study_profile).toEqual(expect.objectContaining({
      id: expect.any(String),
      label: expect.any(String),
    }));
    expect(result.initial_run).toEqual(expect.objectContaining({
      skipped: false,
      task_status: 'completed',
    }));
    expect(result.study_evaluation.summary.score).toEqual(expect.any(Number));
    expect(result.study_benchmark.summary.score).toEqual(expect.any(Number));
    expect(readStudyBenchmark(repoDir).summary.score).toBe(result.study_benchmark.summary.score);
  });

  it('bootstraps a generic repo into populated study artifacts instead of placeholders', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'generic-bootstrap-repo',
        description: 'Generic bootstrap target for study rollout verification.',
      }, null, 2) + '\n',
      'README.md': [
        '# Generic Bootstrap Repo',
        '',
        'Exercises the shared study bootstrap path on a non-TORQUE style repo.',
        '',
      ].join('\n'),
      'src/index.js': [
        'const runtime = require("./runtime");',
        'module.exports = { run() { return runtime.boot(); } };',
        '',
      ].join('\n'),
      'src/runtime.js': [
        'const manifest = require("../config/app.json");',
        'exports.boot = function boot() { return manifest.enabled === true; };',
        '',
      ].join('\n'),
      'config/app.json': JSON.stringify({ enabled: true, mode: 'demo' }, null, 2) + '\n',
      'tests/runtime.test.js': [
        'const runtime = require("../src/runtime");',
        'test("boot returns the manifest flag", () => {',
        '  expect(runtime.boot()).toBe(true);',
        '});',
        '',
      ].join('\n'),
    });

    const { service } = createService();
    const result = await service.bootstrapStudy(repoDir, {
      project: 'generic-bootstrap-repo',
      runInitialStudy: true,
      runBenchmark: true,
      writeProfileScaffold: true,
    });

    const studyState = JSON.parse(fs.readFileSync(path.join(repoDir, 'docs', 'architecture', 'study-state.json'), 'utf8'));
    const knowledgePack = readKnowledgePack(repoDir);
    const moduleIndex = readModuleIndex(repoDir);
    const summary = readSummary(repoDir);

    expect(result.initial_run).toEqual(expect.objectContaining({
      skipped: false,
      task_status: 'completed',
      pending_count: 0,
    }));
    expect(studyState).toEqual(expect.objectContaining({
      run_count: 1,
      last_result: 'completed_local',
      module_entry_count: 5,
      flow_count: expect.any(Number),
      trace_count: expect.any(Number),
      evaluation_grade: expect.any(String),
      evaluation_readiness: expect.any(String),
      benchmark_grade: expect.any(String),
    }));
    expect(Array.isArray(studyState.tracked_files)).toBe(true);
    expect(studyState.tracked_files.length).toBe(5);
    expect(moduleIndex.modules).toHaveLength(5);
    expect(knowledgePack.study_profile).toEqual(expect.objectContaining({
      id: 'generic-javascript-repo',
      override_applied: false,
      framework_detection: expect.objectContaining({
        archetype: expect.any(String),
        confidence: expect.any(String),
      }),
    }));
    expect(knowledgePack.coverage).toEqual(expect.objectContaining({
      tracked_files: 5,
      indexed_modules: 5,
      pending_files: 0,
      indexed_percent: 100,
    }));
    expect(knowledgePack.flows.length).toBeGreaterThanOrEqual(3);
    expect(knowledgePack.subsystems.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.invariants.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.canonical_traces.length).toBeGreaterThan(0);
    expect(knowledgePack.expertise.change_playbooks.length).toBeGreaterThan(0);
    expect(summary).not.toBe(SUMMARY_PLACEHOLDER);
    expect(summary).toContain('Knowledge Primer');
    expect(summary).toContain('docs/architecture/knowledge-pack.json');
    expect(result.study_evaluation.summary.readiness).not.toBe('map_only');
    expect(fs.existsSync(path.join(repoDir, 'docs', 'architecture', 'study-profile.override.json'))).toBe(true);
  });

  it('previews bootstrap plans and can scaffold a repo-local profile override', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'generic-preview-repo',
        description: 'Preview target for generic study bootstrap.',
      }, null, 2) + '\n',
      'src/index.js': 'module.exports = { run() { return true; } };\n',
      'src/runtime.js': 'module.exports = { boot() { return true; } };\n',
    });

    const { service } = createService();
    const preview = await service.previewBootstrapStudy(repoDir, {
      project: 'generic-preview-repo',
      submitProposals: true,
      proposalLimit: 2,
    });

    expect(preview.bootstrap_plan).toEqual(expect.objectContaining({
      repo: expect.objectContaining({
        name: 'generic-preview-repo',
        project: 'generic-preview-repo',
      }),
      study_profile: expect.objectContaining({
        id: expect.any(String),
      }),
    }));
    expect(preview.study_profile).toEqual(expect.objectContaining({
      id: expect.any(String),
      label: expect.any(String),
      override_applied: false,
    }));
    expect(preview.profile_override).toEqual(expect.objectContaining({
      exists: false,
      repo_path: 'docs/architecture/study-profile.override.json',
      template: expect.objectContaining({
        base_profile_id: preview.study_profile.id,
      }),
    }));

    const bootstrap = await service.bootstrapStudy(repoDir, {
      runInitialStudy: false,
      runBenchmark: false,
      writeProfileScaffold: true,
    });
    const overridePath = path.join(repoDir, 'docs', 'architecture', 'study-profile.override.json');
    expect(fs.existsSync(overridePath)).toBe(true);
    expect(bootstrap.profile_override).toEqual(expect.objectContaining({
      exists: true,
      scaffold_written: true,
      repo_path: 'docs/architecture/study-profile.override.json',
    }));
    const overrideFile = JSON.parse(fs.readFileSync(overridePath, 'utf8'));
    expect(overrideFile).toEqual(expect.objectContaining({
      version: 1,
      base_profile_id: bootstrap.study_profile.id,
    }));
  });

  it('reports, saves, and clears repo-local study profile overrides', async () => {
    repoDir = createRepo({
      'package.json': JSON.stringify({
        name: 'generic-override-repo',
        scripts: {
          build: 'vite build',
          test: 'vitest run',
        },
      }, null, 2) + '\n',
      'src/main.jsx': 'export function boot() { return true; }\n',
      'src/App.jsx': 'export default function App() { return null; }\n',
    });

    const { service } = createService();
    const initial = await service.getStudyProfileOverrideStatus(repoDir);
    expect(initial).toEqual(expect.objectContaining({
      exists: false,
      active: false,
      repo_path: 'docs/architecture/study-profile.override.json',
      study_profile: expect.objectContaining({
        framework_detection: expect.objectContaining({
          archetype: expect.any(String),
          confidence: expect.any(String),
        }),
      }),
    }));

    const saved = await service.saveStudyProfileOverride(repoDir, {
      version: 1,
      base_profile_id: 'generic-javascript-repo',
      subsystem_priority: {
        runtime: 50,
      },
    });
    expect(saved).toEqual(expect.objectContaining({
      exists: true,
      active: true,
      override: expect.objectContaining({
        subsystem_priority: {
          runtime: 50,
        },
      }),
    }));

    const cleared = await service.saveStudyProfileOverride(repoDir, null, { clear: true });
    expect(cleared).toEqual(expect.objectContaining({
      exists: false,
      active: false,
      template: expect.objectContaining({
        base_profile_id: expect.any(String),
      }),
    }));
  });
});
