import { describe, it, expect } from 'vitest';
import { createPlanExecuteStage } from '../factory/plan-execute.js';

// Phase 3 slice 5 (final): the PLAN/EXECUTE stage executors (executePlanStage,
// executeNonPlanFileStage, executePlanFileStage, handlePlanExecuteTransition)
// plus cluster-internal fold-ins moved from loop-controller.js to
// plan-execute.js. Behavioral coverage stays in the loop-controller factory
// tests. This file pins the createPlanExecuteStage dependency-injection
// contract.
//
// Seam-tightening follow-up: the 48 cross-cluster deps are no longer passed
// flat. They arrive as 3 cluster objects — planGenerationCluster /
// worktreeOwner / executeDeferral, each a createXxx() factory output —
// which plan-execute.js destructures internally. The contract is now
// 32 fn deps + 6 value deps + 3 cluster objects (41 total, was 86).

const FN_DEPS = [
  'awaitTaskToStructuredResult', 'elapsedMsSince', 'extractTextContent',
  'finalizeTerminalVerifyOutcome', 'getDatabaseHandle', 'getDecisionBatchId',
  'getDefaultFactoryBatchId', 'getInstanceOrThrow', 'getSelectedWorkItem', 'getTaskAgeMs',
  'getWorkItemDecisionContext', 'getWorkItemScopedBatchId', 'getWorktreeRunner',
  'isTerminalVerifyOutcome', 'listTasksForFactoryBatch', 'maybeShipNoop',
  'maybeShortCircuitZeroDiffExecute', 'normalizeOptionalString', 'nowIso', 'parseJsonObject',
  'recordFactoryIdleIfExhausted', 'rememberSelectedWorkItem', 'restoreTerminalEscalationWorkItem',
  'routePlanQualityGateFailureToNeedsReplan', 'routeWorkItemToNeedsReplan', 'runExecuteVerifyStage',
  'safeLogDecision', 'shouldDeletePlanPathForNeedsReplan', 'terminateInstanceAndSync',
  'tryGetSelectedWorkItem', 'tryMoveInstanceToStage', 'updateInstanceAndSync',
];
const VALUE_DEPS = [
  'AUTO_ADVANCE_DEFERRED_FALLBACK_DELAY_MS', 'IN_FLIGHT_SAME_WI_SKIP_LOG_INTERVAL_MS',
  'IN_FLIGHT_SAME_WI_SKIP_TRACKING_MAX_ENTRIES', 'PLAN_GENERATION_UNUSABLE_OUTPUT_RETRIES',
  'TERMINAL_FACTORY_BATCH_TASK_STATUSES', 'inFlightSameWiSkipEmitTimestamps',
];
const CLUSTER_DEPS = {
  planGenerationCluster: [
    'returnAutoGeneratedPlanToPrioritizeForDescriptionQuality', 'getPlanGeneratorLabel',
    'getStoredPlanGeneratorProvider', 'reviewAutoGeneratedPlan', 'getPlanGenerationTask',
    'getPlanGenerationWait', 'isPlanGenerationTaskPending', 'buildPlanGenerationDeferredResult',
    'getPlanGenerationRetryCount', 'buildPlanGenerationRetryResult',
    'buildPlanGenerationProviderFallbackResult', 'getStoredPlanGenerationTaskId',
    'migrateGeneratedPlanPathForExecutionWorktree', 'findExistingPlanTaskSubmission',
    'recoverTerminalPlanGenerationMarkdown', 'extractPlanGenerationRawMarkdown',
    'normalizeAutoGeneratedPlanMarkdown', 'cleanupRecoveredSideWrittenPlan', 'lintAutoGeneratedPlan',
    'findActivePlanGenerationTask', 'findActiveProjectPlanGenerationTask',
    'buildProjectPlanGenerationBusyResult', 'persistPlanGenerationTaskReplacement',
    'prepareAutoGeneratedPlanArtifactWorktree', 'retireStalePendingPlanGenerationTask',
  ],
  worktreeOwner: [
    'resolveTaskReplacementChain', 'getActiveBatchWorktreeForPlanGate',
    'getLiveActiveBatchWorktreeOwner', 'getFactoryWorktreePath', 'factoryWorktreeBelongsToWorkItem',
    'isReusableWorktreeOwner', 'ensureReusedFactoryWorktreeFresh',
    'prepareReusedFactoryWorktreeDependencies', 'maybeReuseCompletedWorktreeOwner',
    'getFactoryWorktreeWorkItemId', 'isLiveWorktreeOwner', 'findLiveReplacementWorktreeOwner',
    'adoptReplacementWorktreeOwner', 'getWorktreeDirtyStatus', 'findReusableReplacementWorktreeOwner',
  ],
  executeDeferral: [
    'getLatestExecutePausedDeferral', 'deferExecutePlanTaskIfProjectPaused',
    'ExecuteDeferredPausedError', 'inspectExecuteDeferredResume', 'logExecuteDeferredResume',
    'maybeWarnStaleExecuteDeferral', 'maybeRejectResumedDeferredPlan',
    'logExecuteDeferredPausedStaleWarning',
  ],
};

function makeFullDeps() {
  const deps = {};
  for (const name of FN_DEPS) deps[name] = () => {};
  for (const name of VALUE_DEPS) deps[name] = name.endsWith('_MS') ? 1000 : new Set();
  for (const [clusterName, members] of Object.entries(CLUSTER_DEPS)) {
    const cluster = {};
    for (const member of members) cluster[member] = () => {};
    deps[clusterName] = cluster;
  }
  return deps;
}

describe('createPlanExecuteStage — dependency-injection contract', () => {
  it('returns the 3 dispatcher-facing PLAN/EXECUTE functions with full deps', () => {
    const api = createPlanExecuteStage(makeFullDeps());
    expect(Object.keys(api).sort()).toEqual(
      ['executeNonPlanFileStage', 'executePlanStage', 'handlePlanExecuteTransition'],
    );
    for (const fn of Object.values(api)) expect(typeof fn).toBe('function');
  });

  it('throws naming each missing function dep', () => {
    for (const missing of FN_DEPS) {
      const deps = makeFullDeps();
      delete deps[missing];
      expect(() => createPlanExecuteStage(deps)).toThrow(new RegExp(`dep '${missing}' is required`));
    }
  });

  it('throws naming each missing value dep', () => {
    for (const missing of VALUE_DEPS) {
      const deps = makeFullDeps();
      delete deps[missing];
      expect(() => createPlanExecuteStage(deps)).toThrow(new RegExp(`dep '${missing}' is required`));
    }
  });

  it('throws naming each missing cluster object', () => {
    for (const clusterName of Object.keys(CLUSTER_DEPS)) {
      const deps = makeFullDeps();
      delete deps[clusterName];
      expect(() => createPlanExecuteStage(deps)).toThrow(
        new RegExp(`cluster dep '${clusterName}' is required`),
      );
    }
  });

  it('throws naming each missing cluster member', () => {
    for (const [clusterName, members] of Object.entries(CLUSTER_DEPS)) {
      for (const member of members) {
        const deps = makeFullDeps();
        deps[clusterName] = { ...deps[clusterName] };
        delete deps[clusterName][member];
        expect(() => createPlanExecuteStage(deps)).toThrow(
          new RegExp(`'${clusterName}\\.${member}' is required`),
        );
      }
    }
  });

  it('throws when called with no deps at all', () => {
    expect(() => createPlanExecuteStage()).toThrow(/is required/);
  });
});
