'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { setupTestDbOnly, teardownTestDb, rawDb } = require('./vitest-setup');

function seedProjectAndItem(db, { trust = 'autonomous', originOverrides = {}, projectPath } = {}) {
  const projectId = 'proj-e2e-1';
  const resolvedPath = projectPath || fs.mkdtempSync(path.join(os.tmpdir(), 'pqg-e2e-'));
  db.prepare(`INSERT INTO factory_projects (id, name, path, trust_level, status, config_json, created_at, updated_at) VALUES (?, ?, ?, ?, 'running', '{}', datetime('now'), datetime('now'))`)
    .run(projectId, 'Test', resolvedPath, trust);
  const item = {
    project_id: projectId,
    source: 'architect',
    title: 'Edit src/foo.ts to do a thing',
    description: 'In src/foo.ts adjust handleFoo and run npx vitest tests/foo.test.ts.',
    priority: 50,
    status: 'planned',
    origin_json: JSON.stringify({ plan_path: path.join(resolvedPath, 'plan.md'), ...originOverrides }),
  };
  const { lastInsertRowid } = db.prepare(`INSERT INTO factory_work_items (project_id, source, title, description, priority, status, origin_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))`)
    .run(item.project_id, item.source, item.title, item.description, item.priority, item.status, item.origin_json);
  return { projectId, workItemId: lastInsertRowid, projectPath: resolvedPath };
}

const HIGH_QUALITY_PLAN = [
  '# Concrete Plan',
  '',
  '**Source:** auto-generated from work_item #1',
  '**Tech Stack:** Node.js',
  '',
  '## Task 1: Add deterministic plan specificity scoring',
  '',
  '- [ ] **Step 1: Update scorer**',
  '',
  '    Edit server/factory/loop-controller.js only; scope is 1 file and under 120 lines. Add the score helper beside lintAutoGeneratedPlan and include threshold details in the result payload.',
  '',
  '- [ ] **Step 2: Validate rejection payload**',
  '',
  '    Run npx vitest run server/tests/factory-plan-quality-gate-e2e.test.js. Success criteria: expect vague plans to return to PRIORITIZE with JSON reject_reason.score and threshold fields.',
].join('\n');

const VAGUE_PLAN_WITH_NO_FILE_PATHS = [
  '# Vague Plan',
  '',
  '**Source:** auto-generated from work_item #1',
  '**Tech Stack:** Node.js',
  '',
  '## Task 1: Improve the implementation',
  '',
  '- [ ] **Step 1: Improve things**',
  '',
  '    Improve the implementation, handle edge cases, update tests, and make better behavior.',
  '',
  '- [ ] **Step 2: Check it**',
  '',
  '    Run npm test. Success criteria: things should pass.',
].join('\n');

describe('auto-generated plan description quality scoring', () => {
  it('passes a high-quality plan with file path, scope, success criteria, and validation command', () => {
    const loopController = require('../factory/loop-controller');

    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(HIGH_QUALITY_PLAN);

    expect(score.blocked).toBe(false);
    expect(score.tasks[0].score).toBeGreaterThanOrEqual(score.threshold);
    expect(score.tasks[0].missing_signals).toEqual([]);
  });

  it('fails a structurally valid vague plan with no file paths', () => {
    const loopController = require('../factory/loop-controller');

    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(VAGUE_PLAN_WITH_NO_FILE_PATHS);

    expect(score.blocked).toBe(true);
    expect(score.failures[0]).toMatchObject({
      task_index: 1,
      threshold: 80,
    });
    expect(score.failures[0].missing_signals).toContain('explicit_file_paths');
    expect(score.failures[0].missing_signals).toContain('estimated_scope');
    expect(score.failures[0].missing_signals).toContain('concrete_language');
  });

  it('passes a documentation-only plan without synthetic line counts or pytest invocations', () => {
    // Guards the bitsy 2026-04-20 item 490 / 491 regression: the deterministic
    // gate kept rejecting doc-only tasks at 60/100 because `estimated_scope`
    // and `validation_steps` regex target test-run commands ("pytest", "npx
    // vitest", etc.). Doc-removal / doc-supersession tasks naturally lack
    // these signals. When every extracted file path is a documentation
    // extension, auto-satisfy both signals so well-specified doc work gets
    // through without the planner fabricating fake pytest commands.
    const loopController = require('../factory/loop-controller');

    const DOC_ONLY_PLAN = [
      '# Doc Plan',
      '',
      '**Source:** auto-generated from work_item #1',
      '**Tech Stack:** Python',
      '',
      '## Task 1: Mark PixelLab-era design documents as superseded',
      '',
      '- [ ] **Step 1: Add supersession banners**',
      '',
      '    Edit docs/plans/2026-02-24-pixellab-integration-design.md and docs/plans/2026-03-07-style-consistency-design.md. Add top-of-file notices stating the docs are historical and superseded. Acceptance criteria: both docs must show the supersession notice before original content, and must not imply the active package wraps the PixelLab API.',
      '',
    ].join('\n');

    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(DOC_ONLY_PLAN);

    expect(score.blocked).toBe(false);
    expect(score.tasks[0].score).toBeGreaterThanOrEqual(score.threshold);
    // The carve-out flips these two regex signals on for doc-only paths.
    expect(score.tasks[0].signals.estimated_scope).toBe(true);
    expect(score.tasks[0].signals.validation_steps).toBe(true);
  });

  it('still rejects a doc-only plan that lacks success criteria or concrete language', () => {
    // The carve-out only relaxes scope+validation for doc-only paths; the
    // other three signals (explicit_file_paths, success_criteria,
    // concrete_language) still have to pass on their own so vague
    // "update docs" one-liners are still rejected. The vague phrase is
    // placed far enough from the file path that the 200-char
    // hasObjectLevelDetail window doesn't rescue it.
    const loopController = require('../factory/loop-controller');

    const VAGUE_DOC_PLAN = [
      '# Vague Doc Plan',
      '',
      '**Source:** auto-generated from work_item #1',
      '**Tech Stack:** Python',
      '',
      '## Task 1: Update the PixelLab-era plan docs to tidy them up',
      '',
      '    Improve and clean up the PixelLab-era plan documents so readers have a gentler onboarding experience across the supersession notice, the historical framing, and the residual narrative framing that is no longer relevant to active work in the current package layout that ships today.',
      '',
      '    Touches docs/plans/historical/legacy.md only.',
      '',
    ].join('\n');

    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(VAGUE_DOC_PLAN);

    expect(score.blocked).toBe(true);
    expect(score.failures[0].missing_signals).toContain('success_criteria');
    expect(score.failures[0].missing_signals).toContain('concrete_language');
  });

  it('augments rejected task specificity from work-item origin scope and verification', () => {
    const loopController = require('../factory/loop-controller');

    const underSpecifiedPlan = [
      '# Origin-Backed Plan',
      '',
      '**Source:** auto-generated from work_item #2048',
      '**Tech Stack:** Python',
      '',
      '## Task 1: Reconcile first-run smoke validation',
      '',
      '    Reconcile the first-run host join smoke validation for the factory work item.',
      '',
    ].join('\n');
    const workItem = {
      id: 2048,
      origin_json: JSON.stringify({
        allowed_files: [
          'tools/validate_first_run_smoke.py',
          'docs/qa/UnityFirstRunHostJoinSmokeChecklist.md',
        ],
        verification: 'python tools/validate_first_run_smoke.py docs/qa/UnityFirstRunHostJoinSmokeChecklist.md',
      }),
    };

    const augmented = loopController._internalForTests.augmentAutoGeneratedTaskSpecificity(underSpecifiedPlan, workItem);
    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(augmented);

    expect(augmented).toContain('Estimated scope: single focused change across 2 files');
    expect(augmented).toContain('Validation: Run `python tools/validate_first_run_smoke.py docs/qa/UnityFirstRunHostJoinSmokeChecklist.md`');
    expect(score.blocked).toBe(false);
    expect(score.tasks[0].missing_signals).toEqual([]);
  });

  it('normalizes provider plans with task-local scope and validation when origin scope is absent', () => {
    const loopController = require('../factory/loop-controller');
    const projectPath = fs.mkdtempSync(path.join(os.tmpdir(), 'pqg-node-project-'));
    fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify({ scripts: { test: 'vitest run' } }));
    fs.mkdirSync(path.join(projectPath, 'server', 'db'), { recursive: true });
    fs.mkdirSync(path.join(projectPath, 'server', 'execution'), { recursive: true });
    fs.mkdirSync(path.join(projectPath, 'server', 'tests'), { recursive: true });
    fs.writeFileSync(path.join(projectPath, 'server', 'db', 'workflow-engine.js'), 'module.exports = {};\n');
    fs.writeFileSync(path.join(projectPath, 'server', 'execution', 'workflow-runtime.js'), 'module.exports = { runWorkflow() {} };\n');
    fs.writeFileSync(path.join(projectPath, 'server', 'tests', 'workflow-runtime.test.js'), 'test("runtime", () => {});\n');
    const rawPlan = [
      '# Fabro #60 Plan',
      '',
      '**Tech Stack:** Node.js',
      '',
      '## Task 1: Identify and analyze the workflow execution entrypoint in the workflow engine',
      '',
      '- [ ] **Step 1: Locate workflow execution functions**',
      '',
      '    Identify the functions in `server/db/workflow-engine.js` that handle workflow execution and find `runWorkflow` or `executeWorkflow`.',
      '',
      '- [ ] **Step 2: Commit**',
      '',
      '    git commit -m "Analyzed workflow engine execution flow for API extraction"',
      '',
      '## Task 2: Implement input validation for the new API',
      '',
      '- [ ] **Step 1: Add validation for workflowPath**',
      '',
      '    Add validation to ensure `workflowPath` is provided and points to a readable YAML file.',
      '',
      '- [ ] **Step 2: Validate args**',
      '',
      '    Add validation for the `args` parameter and reject invalid values before execution. Verify with `npx vitest run server/__tests__/workflow-runtime-library.test.js`.',
      '',
      '- [ ] **Step 3: Commit**',
      '',
      '    git commit -m "Added input validation for workflow API"',
      '',
    ].join('\n');
    const workItem = {
      id: 190,
      title: 'Extract workflow runtime entrypoint',
      description: 'Expose runWorkflow near `server/workflow-engine.js` or `server/workflow-engine/index.js`, add `packages/runtime/src/index.ts`, and cover `server/__tests__/workflow-runtime-library.test.js`.',
      origin_json: '{}',
    };
    const prompt = loopController.buildAutoGeneratedPlanPrompt(
      { id: 'p1', name: 'Test', path: projectPath },
      workItem
    );
    expect(prompt).toContain('Candidate paths mentioned by the work item but not currently present');
    expect(prompt).toContain('`server/workflow-engine.js`');
    expect(prompt).toContain('Existing repository files related to this work item');
    expect(prompt).toContain('`server/execution/workflow-runtime.js`');

    const normalized = loopController._internalForTests.normalizeAutoGeneratedPlanMarkdown(
      rawPlan,
      workItem,
      { id: 'p1', name: 'Test', path: projectPath }
    );

    expect(normalized).toContain('server/execution/workflow-runtime.js');
    expect(normalized).toContain('server/tests/workflow-runtime.test.js');
    expect(normalized).not.toContain('server/db/workflow-engine.js');
    expect(normalized).not.toContain('server/__tests__/workflow-runtime-library.test.js');
    expect(normalized).toContain('Estimated scope: single focused change across');
    expect(normalized).toContain('Validation: Run `');

    const score = loopController._internalForTests.scoreAutoGeneratedPlanDescriptions(normalized);
    expect(score.blocked).toBe(false);
    expect(score.tasks.map((task) => task.missing_signals)).toEqual([[], []]);
  });
});

describe('executeNonPlanFileStage plan-quality-gate integration', () => {
  let db;
  beforeEach(() => {
    setupTestDbOnly('plan-quality-gate-e2e');
    db = rawDb();
  });
  afterEach(() => {
    vi.restoreAllMocks();
    teardownTestDb();
  });

  it('Scenario 1 (autonomous, good plan first try): EXECUTE proceeds and plan_gen_attempts becomes 1', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });

    vi.spyOn(planGate, 'evaluatePlan').mockResolvedValue({ passed: true, hardFails: [], warnings: [], llmCritique: null, feedbackPrompt: null });
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-1' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-1', project_id: projectId, batch_id: 'batch-1' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).not.toBe(true);
    const after = db.prepare('SELECT origin_json FROM factory_work_items WHERE id = ?').get(workItemId);
    const origin = JSON.parse(after.origin_json);
    expect(origin.plan_gen_attempts).toBe(1);
  });

  it('Scenario 5 (skip_plan_quality_gate metadata): evaluatePlan is NOT called', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous', originOverrides: { skip_plan_quality_gate: true } });
    const gateSpy = vi.spyOn(planGate, 'evaluatePlan').mockResolvedValue({ passed: false, hardFails: [{ rule: 'x', detail: 'x' }], warnings: [], llmCritique: null, feedbackPrompt: 'x' });
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-2' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-5', project_id: projectId, batch_id: 'batch-5' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(gateSpy).not.toHaveBeenCalled();
    expect(result?.stop_execution).not.toBe(true);
  });

  it('Scenario 6 (gate exception): fail-open, EXECUTE proceeds', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });
    vi.spyOn(planGate, 'evaluatePlan').mockRejectedValue(new Error('scorer exploded'));
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-6' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-6', project_id: projectId, batch_id: 'batch-6' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).not.toBe(true);
  });
});

describe('executeNonPlanFileStage plan-quality-gate — reject paths', () => {
  let db;
  beforeEach(() => {
    setupTestDbOnly('plan-quality-gate-e2e-rejects');
    db = rawDb();
  });
  afterEach(() => {
    vi.restoreAllMocks();
    teardownTestDb();
  });

  it('Scenario 2 (autonomous, bad plan first, good plan on replan): attempts=2, EXECUTE proceeds', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });
    const gateSpy = vi.spyOn(planGate, 'evaluatePlan')
      .mockResolvedValueOnce({ passed: false, hardFails: [{ rule: 'task_has_file_reference', taskNumber: 1, detail: 'no file' }], warnings: [], llmCritique: null, feedbackPrompt: '## Prior plan rejected\n\n- [task_has_file_reference] Task 1: no file' })
      .mockResolvedValueOnce({ passed: true, hardFails: [], warnings: [], llmCritique: null, feedbackPrompt: null });

    const submitStub = vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-2' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-2', project_id: projectId, batch_id: 'batch-2' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).not.toBe(true);
    expect(gateSpy).toHaveBeenCalledTimes(2);
    expect(submitStub).toHaveBeenCalledTimes(2); // initial plan gen + re-plan
    const after = db.prepare('SELECT origin_json FROM factory_work_items WHERE id = ?').get(workItemId);
    const origin = JSON.parse(after.origin_json);
    expect(origin.plan_gen_attempts).toBe(2);
  });

  it('defers an active intra-batch re-plan task and records it on the work item', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });
    vi.spyOn(planGate, 'evaluatePlan')
      .mockResolvedValueOnce({
        passed: false,
        hardFails: [{ rule: 'task_has_file_reference', taskNumber: 1, detail: 'no file' }],
        warnings: [],
        llmCritique: null,
        feedbackPrompt: '## Prior plan rejected\n\n- [task_has_file_reference] Task 1: no file',
      });

    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask')
      .mockResolvedValueOnce({ task_id: 'initial-plan-task' })
      .mockResolvedValueOnce({ task_id: 'active-replan-task' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'running' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockImplementation((taskId) => {
      if (taskId === 'initial-plan-task') {
        return { id: taskId, status: 'completed', output: HIGH_QUALITY_PLAN, error_output: null };
      }
      if (taskId === 'active-replan-task') {
        return { id: taskId, status: 'running', output: '', error_output: null };
      }
      return null;
    });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-replan-active', project_id: projectId, batch_id: 'batch-replan-active' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result).toMatchObject({
      stop_execution: true,
      next_state: 'EXECUTE',
      stage_result: {
        status: 'deferred',
        reason: 'task_still_running',
        generation_task_id: 'active-replan-task',
        task_status: 'running',
      },
    });

    const after = db.prepare('SELECT status, origin_json FROM factory_work_items WHERE id = ?').get(workItemId);
    const origin = JSON.parse(after.origin_json);
    expect(after.status).toBe('executing');
    expect(origin.plan_generation_task_id).toBe('active-replan-task');
    expect(origin.plan_generation_wait_reason).toBe('task_still_running');
  });

  it('returns a structurally valid but vague generated plan to PRIORITIZE with threshold details', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });
    db.prepare('UPDATE factory_work_items SET title = ?, description = ?, origin_json = ? WHERE id = ?')
      .run(
        'Improve behavior',
        'Improve the implementation and handle edge cases.',
        '{}',
        workItemId
      );
    const gateSpy = vi.spyOn(planGate, 'evaluatePlan').mockResolvedValue({ passed: true, hardFails: [], warnings: [], llmCritique: null, feedbackPrompt: null });
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-specificity' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: VAGUE_PLAN_WITH_NO_FILE_PATHS });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-specificity', project_id: projectId, batch_id: 'batch-specificity' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).toBe(true);
    expect(result?.next_state).toBe('PRIORITIZE');
    expect(gateSpy).not.toHaveBeenCalled();

    const after = db.prepare('SELECT status, reject_reason FROM factory_work_items WHERE id = ?').get(workItemId);
    // Phase X3 (66b153fa): plan-quality failures route work items to
    // 'needs_replan' instead of 'prioritized' so PRIORITIZE re-picks them
    // with the Phase X2 prior-rejection feedback prepended next cycle.
    expect(after.status).toBe('needs_replan');
    const rejectReason = JSON.parse(after.reject_reason);
    expect(rejectReason).toMatchObject({
      code: 'plan_description_quality_below_threshold',
      failing_task_index: 1,
      failing_task_title: 'Improve the implementation',
      score: 60,
      threshold: 80,
    });
    expect(rejectReason.missing_specificity_signals).toEqual(expect.arrayContaining([
      'explicit_file_paths',
      'concrete_language',
    ]));
    expect(rejectReason.missing_specificity_signals).not.toContain('estimated_scope');
    expect(rejectReason.missing_specificity_signals).not.toContain('validation_steps');
    expect(result.stage_result.description_quality.threshold).toBe(80);
  });

  it('Scenario 3 (autonomous, bad plan twice): item routed to needs_replan, next_state PRIORITIZE', async () => {
    // Phase X3/X4 (66b153fa, 79917100): plan-quality failures route to
    // 'needs_replan' instead of terminal 'rejected', and the loop returns
    // to PRIORITIZE (not IDLE) so the next architect attempt can produce
    // a different plan with the prior-rejection feedback prepended.
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'autonomous' });
    vi.spyOn(planGate, 'evaluatePlan').mockResolvedValue({ passed: false, hardFails: [{ rule: 'task_has_file_reference', taskNumber: 1, detail: 'no file' }], warnings: [], llmCritique: null, feedbackPrompt: '## Prior plan rejected\n...' });
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-3' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-3', project_id: projectId, batch_id: 'batch-3' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).toBe(true);
    expect(result?.next_state).toBe('PRIORITIZE');
    const after = db.prepare('SELECT status, reject_reason FROM factory_work_items WHERE id = ?').get(workItemId);
    expect(after.status).toBe('needs_replan');
  });

  it('Scenario 4 (supervised, bad plan): paused at PLAN_REVIEW with gate_feedback populated', async () => {
    const loopController = require('../factory/loop-controller');
    const planGate = require('../factory/plan-quality-gate');

    const { projectId, workItemId } = seedProjectAndItem(db, { trust: 'supervised' });
    vi.spyOn(planGate, 'evaluatePlan').mockResolvedValue({ passed: false, hardFails: [{ rule: 'task_has_file_reference', taskNumber: 1, detail: 'no file' }], warnings: [], llmCritique: null, feedbackPrompt: '## Prior plan rejected\n\n- [task_has_file_reference] Task 1: no file' });
    vi.spyOn(require('../factory/internal-task-submit'), 'submitFactoryInternalTask').mockResolvedValue({ task_id: 't-4' });
    vi.spyOn(require('../handlers/workflow/await'), 'handleAwaitTask').mockResolvedValue({ status: 'completed' });
    vi.spyOn(require('../db/task-core'), 'getTask').mockReturnValue({ status: 'completed', output: HIGH_QUALITY_PLAN });

    const project = db.prepare('SELECT * FROM factory_projects WHERE id = ?').get(projectId);
    const instance = { id: 'inst-4', project_id: projectId, batch_id: 'batch-4' };
    const workItem = db.prepare('SELECT * FROM factory_work_items WHERE id = ?').get(workItemId);

    const result = await loopController.executeNonPlanFileStage(project, instance, workItem);

    expect(result?.stop_execution).toBe(true);
    expect(result?.paused_at_stage).toBe('PLAN_REVIEW');
    expect(result?.stage_result?.gate_feedback).toContain('## Prior plan rejected');
    expect(result?.stage_result?.hardFails).toHaveLength(1);
  });
});
