import { describe, it, expect } from 'vitest';
import { createPlanExecuteStage } from '../factory/plan-execute.js';

// Phase 3 slice 5 (final): the PLAN/EXECUTE stage executors (executePlanStage,
// executeNonPlanFileStage, executePlanFileStage, handlePlanExecuteTransition)
// plus cluster-internal fold-ins moved from loop-controller.js to
// plan-execute.js. Behavioral coverage stays in the loop-controller factory
// tests. This file pins the createPlanExecuteStage dependency-injection
// contract.

const FN_DEPS = [
  'awaitTaskToStructuredResult', 'elapsedMsSince', 'extractTextContent',
  'finalizeTerminalVerifyOutcome', 'getDatabaseHandle', 'getDecisionBatchId',
  'getDefaultFactoryBatchId', 'getInstanceOrThrow', 'getSelectedWorkItem', 'getTaskAgeMs',
  'getWorkItemDecisionContext', 'getWorkItemScopedBatchId', 'getWorktreeRunner',
  'isTerminalVerifyOutcome', 'listTasksForFactoryBatch', 'maybeShipNoop',
  'maybeShortCircuitZeroDiffExecute', 'normalizeOptionalString', 'nowIso', 'parseJsonObject',
  'recordFactoryIdleIfExhausted', 'rememberSelectedWorkItem', 'restoreTerminalEscalationWorkItem',
  'routePlanQualityGateFailureToNeedsReplan', 'routeWorkItemToNeedsReplan', 'runExecuteVerifyStage',
  'safeLogDecision', 'shouldDeletePlanPathForNeedsReplan', 'terminateInstanceAndSync',
  'tryGetSelectedWorkItem', 'tryMoveInstanceToStage', 'updateInstanceAndSync',
  'returnAutoGeneratedPlanToPrioritizeForDescriptionQuality', 'getPlanGeneratorLabel',
  'getStoredPlanGeneratorProvider', 'reviewAutoGeneratedPlan', 'getPlanGenerationTask',
  'getPlanGenerationWait', 'isPlanGenerationTaskPending', 'buildPlanGenerationDeferredResult',
  'getPlanGenerationRetryCount', 'buildPlanGenerationRetryResult',
  'buildPlanGenerationProviderFallbackResult', 'getStoredPlanGenerationTaskId',
  'migrateGeneratedPlanPathForExecutionWorktree', 'findExistingPlanTaskSubmission',
  'recoverTerminalPlanGenerationMarkdown', 'extractPlanGenerationRawMarkdown',
  'normalizeAutoGeneratedPlanMarkdown', 'cleanupRecoveredSideWrittenPlan', 'lintAutoGeneratedPlan',
  'findActivePlanGenerationTask', 'findActiveProjectPlanGenerationTask',
  'buildProjectPlanGenerationBusyResult', 'persistPlanGenerationTaskReplacement',
  'prepareAutoGeneratedPlanArtifactWorktree', 'retireStalePendingPlanGenerationTask',
  'resolveTaskReplacementChain', 'getActiveBatchWorktreeForPlanGate',
  'getLiveActiveBatchWorktreeOwner', 'getFactoryWorktreePath', 'factoryWorktreeBelongsToWorkItem',
  'isReusableWorktreeOwner', 'ensureReusedFactoryWorktreeFresh',
  'prepareReusedFactoryWorktreeDependencies', 'maybeReuseCompletedWorktreeOwner',
  'getFactoryWorktreeWorkItemId', 'isLiveWorktreeOwner', 'findLiveReplacementWorktreeOwner',
  'adoptReplacementWorktreeOwner', 'getWorktreeDirtyStatus', 'findReusableReplacementWorktreeOwner',
  'getLatestExecutePausedDeferral', 'deferExecutePlanTaskIfProjectPaused',
  'ExecuteDeferredPausedError', 'inspectExecuteDeferredResume', 'logExecuteDeferredResume',
  'maybeWarnStaleExecuteDeferral', 'maybeRejectResumedDeferredPlan',
  'logExecuteDeferredPausedStaleWarning',
];
const VALUE_DEPS = [
  'AUTO_ADVANCE_DEFERRED_FALLBACK_DELAY_MS', 'IN_FLIGHT_SAME_WI_SKIP_LOG_INTERVAL_MS',
  'IN_FLIGHT_SAME_WI_SKIP_TRACKING_MAX_ENTRIES', 'PLAN_GENERATION_UNUSABLE_OUTPUT_RETRIES',
  'TERMINAL_FACTORY_BATCH_TASK_STATUSES', 'inFlightSameWiSkipEmitTimestamps',
];

function makeFullDeps() {
  const deps = {};
  for (const name of FN_DEPS) deps[name] = () => {};
  for (const name of VALUE_DEPS) deps[name] = name.endsWith('_MS') ? 1000 : new Set();
  return deps;
}

describe('createPlanExecuteStage — dependency-injection contract', () => {
  it('returns the 3 dispatcher-facing PLAN/EXECUTE functions with full deps', () => {
    const api = createPlanExecuteStage(makeFullDeps());
    expect(Object.keys(api).sort()).toEqual(
      ['executeNonPlanFileStage', 'executePlanStage', 'handlePlanExecuteTransition'],
    );
    for (const fn of Object.values(api)) expect(typeof fn).toBe('function');
  });

  it('throws naming each missing function dep', () => {
    for (const missing of FN_DEPS) {
      const deps = makeFullDeps();
      delete deps[missing];
      expect(() => createPlanExecuteStage(deps)).toThrow(new RegExp(`dep '${missing}' is required`));
    }
  });

  it('throws naming each missing value dep', () => {
    for (const missing of VALUE_DEPS) {
      const deps = makeFullDeps();
      delete deps[missing];
      expect(() => createPlanExecuteStage(deps)).toThrow(new RegExp(`dep '${missing}' is required`));
    }
  });

  it('throws when called with no deps at all', () => {
    expect(() => createPlanExecuteStage()).toThrow(/is required/);
  });
});
