'use strict';

const path = require('path');
const fs = require('fs');
const {
  buildPriorRejectionFeedbackPrompt,
  buildAutoGeneratedPlanPrompt,
} = require('../factory/loop-controller');

describe('Phase X2: prior-rejection feedback prompt', () => {
  describe('buildPriorRejectionFeedbackPrompt', () => {
    it('returns null for missing/empty rejection payload', () => {
      expect(buildPriorRejectionFeedbackPrompt(null)).toBeNull();
      expect(buildPriorRejectionFeedbackPrompt(undefined)).toBeNull();
      expect(buildPriorRejectionFeedbackPrompt({})).toBeNull();
    });

    it('threads semantic gate feedback when no deterministic rejection payload exists', () => {
      const feedback = buildPriorRejectionFeedbackPrompt(
        null,
        '## Prior plan rejected — address these issues in the next plan.\n\n### Semantic concern:\nUse the requested focused test file instead of the broad workflow handler test.'
      );

      expect(feedback).toContain('PRIOR PLAN REJECTED');
      expect(feedback).toContain('Prior gate feedback');
      expect(feedback).toContain('Semantic concern');
      expect(feedback).toContain('requested focused test file');
      expect(feedback).toContain('Required for this attempt');
    });

    it('produces a structured feedback block from a real plan-quality rejection payload', () => {
      // Shape captured live from example-project work item #2177 rejection at
      // 2026-05-01 21:29:54 UTC.
      const rejection = {
        code: 'plan_description_quality_below_threshold',
        failing_task_index: 1,
        failing_task_title: 'Make redaction compliance failures catchable',
        score: 60,
        threshold: 80,
        missing_specificity_signals: ['estimated_scope', 'validation_steps'],
        reasons: [
          'missing estimated scope or line/file count',
          'missing concrete validation command or step',
        ],
        failing_tasks: [
          {
            task_index: 1,
            task_title: 'Make redaction compliance failures catchable',
            score: 60,
            threshold: 80,
            missing_specificity_signals: ['estimated_scope', 'validation_steps'],
            reasons: ['missing estimated scope or line/file count'],
          },
        ],
      };
      const feedback = buildPriorRejectionFeedbackPrompt(rejection);
      expect(feedback).toContain('PRIOR PLAN REJECTED');
      expect(feedback).toContain('60');
      expect(feedback).toContain('80');
      expect(feedback).toContain('estimated_scope');
      expect(feedback).toContain('validation_steps');
      expect(feedback).toContain('Make redaction compliance failures catchable');
      expect(feedback).toContain('Required for this attempt');
    });

    it('includes top-level signals when failing_tasks is missing', () => {
      const rejection = {
        score: 50,
        threshold: 80,
        missing_specificity_signals: ['explicit_file_paths'],
        reasons: ['no concrete file paths cited'],
      };
      const feedback = buildPriorRejectionFeedbackPrompt(rejection);
      expect(feedback).toContain('explicit_file_paths');
      expect(feedback).toContain('no concrete file paths cited');
    });

    it('always reminds the architect of the five specificity signals', () => {
      const rejection = {
        failing_tasks: [{ task_index: 0, task_title: 'X', score: 60, threshold: 80 }],
      };
      const feedback = buildPriorRejectionFeedbackPrompt(rejection);
      expect(feedback).toMatch(/explicit file paths/i);
      expect(feedback).toMatch(/estimated scope/i);
      expect(feedback).toMatch(/validation steps/i);
      expect(feedback).toMatch(/success criteria/i);
      expect(feedback).toMatch(/distinct output paths/i);
      expect(feedback).toMatch(/repeat the same test\/source path/i);
    });
  });

  describe('buildAutoGeneratedPlanPrompt threading', () => {
    it('prepends prior feedback to the plan prompt when supplied', () => {
      const project = { id: 'p1', name: 'Test', path: '/tmp/test', brief: 'A project' };
      const workItem = {
        id: 1,
        title: 'Do the thing',
        description: 'Make X work',
        source: 'scout',
      };
      const feedback = '## PRIOR PLAN REJECTED — your last attempt failed.\n\nFix scope.';
      const prompt = buildAutoGeneratedPlanPrompt(project, workItem, feedback);
      // Feedback must come BEFORE the main prompt body.
      const feedbackIdx = prompt.indexOf('PRIOR PLAN REJECTED');
      const planRulesIdx = prompt.indexOf('You are generating an execution plan');
      expect(feedbackIdx).toBeGreaterThan(-1);
      expect(planRulesIdx).toBeGreaterThan(-1);
      expect(feedbackIdx).toBeLessThan(planRulesIdx);
    });

    it('omits the feedback section entirely when none is supplied (regression)', () => {
      const project = { id: 'p1', name: 'Test', path: '/tmp/test', brief: 'A project' };
      const workItem = { id: 1, title: 'X', description: 'Y', source: 'scout' };
      const prompt = buildAutoGeneratedPlanPrompt(project, workItem);
      expect(prompt).not.toContain('PRIOR PLAN REJECTED');
    });

    it('warns architects not to put server-side tests in dashboard view specs', () => {
      const project = { id: 'p1', name: 'Test', path: '/tmp/test', brief: 'A project' };
      const workItem = {
        id: 29,
        title: 'Event-History-Backed Workflow Replay',
        description: 'Add server-side workflow replay behavior and focused tests for the workflow runtime.',
        source: 'scout',
      };

      const prompt = buildAutoGeneratedPlanPrompt(project, workItem);

      expect(prompt).toContain('server-side modules and database/workflow/runtime behavior');
      expect(prompt).toContain('server/tests/...');
      expect(prompt).toContain('server/plugins/<plugin>/tests/...');
      expect(prompt).toContain('dashboard/src/views/*.test.jsx');
      expect(prompt).toContain('React dashboard view/component tests');
    });

    it('warns architects not to invent edit target paths', () => {
      const project = { id: 'p1', name: 'Test', path: '/tmp/test', brief: 'A project' };
      const workItem = {
        id: 6,
        title: 'Cost Ceilings',
        description: 'Add workflow cost ceiling enforcement to the existing workflow runtime.',
        source: 'plan_file',
      };

      const prompt = buildAutoGeneratedPlanPrompt(project, workItem);

      expect(prompt).toContain('For edit/update/extend/fix tasks');
      expect(prompt).toContain('files that already exist in the repository');
      expect(prompt).toContain('make the task an explicit create-file task');
    });

    it('warns architects not to reuse create-file outputs or duplicate validation targets', () => {
      const project = { id: 'p1', name: 'Test', path: '/tmp/test', brief: 'A project' };
      const workItem = {
        id: 548,
        title: 'workflow-runtime.js complexity hotspot',
        description: 'Split workflow runtime behavior into focused modules and tests.',
        source: 'scout',
      };

      const prompt = buildAutoGeneratedPlanPrompt(project, workItem);

      expect(prompt).toContain('Each create-file task must name a distinct output path');
      expect(prompt).toContain('do not say "Create" for a file that already exists');
      expect(prompt).toContain('Targeted validation commands must list each file path only once');
      expect(prompt).toContain('Do not repeat the same test file multiple times');
    });
  });
});

describe('Phase X2: first-attempt plan generation reads origin.last_plan_description_quality_rejection', () => {
  it('source-grep: the first plan-generation prompt build pulls priorFeedback from origin', () => {
    // Verifies the wiring without booting the full container. A future
    // refactor that drops this code path will surface here.
    const src = fs.readFileSync(
      path.join(__dirname, '..', 'factory', 'loop-controller.js'),
      'utf8',
    );
    // The wire-in must reference both the origin field name and the
    // builder, in close proximity.
    expect(src).toMatch(/last_plan_description_quality_rejection[\s\S]{0,400}buildPriorRejectionFeedbackPrompt/);
    expect(src).toMatch(/last_gate_feedback[\s\S]{0,400}buildPriorRejectionFeedbackPrompt/);
    // And the result must be passed to buildAutoGeneratedPlanPrompt.
    expect(src).toMatch(/buildAutoGeneratedPlanPrompt\(planGenerationProject,\s*targetItem,\s*priorFeedback\)/);
  });
});
