'use strict';

const { buildAutoGeneratedPlanPrompt } = require('../factory/loop-controller');

describe('buildAutoGeneratedPlanPrompt — scope files (Phase F)', () => {
  // Phase F regression: without scout exemplar_files in the architect
  // prompt, scout-source items get vague tasks and burn the deterministic
  // plan-quality gate's 5-attempt cap. DLPhone #2098 (2026-04-30)
  // demonstrated this — scout produced a real domain pattern citing
  // docs/planning/BackendMultiplayerPlan.md but the architect never saw
  // that path so its tasks named no concrete files.

  const project = { id: 'p1', name: 'DLPhone', path: '/proj', brief: 'Mobile RTS.' };

  it('injects scout exemplar_files under "Files in scope"', () => {
    const workItem = {
      id: 2098,
      source: 'scout',
      title: 'Scout pattern: Unity client connection logic to relay server',
      description: 'Refactor client-side connection handling.',
      origin: {
        type: 'starvation_recovery_scout_pattern',
        exemplar_files: ['docs/planning/BackendMultiplayerPlan.md'],
        shared_dependencies: [{ file: 'simtests/SimCore.DotNet.Tests.csproj', change: 'Update test refs' }],
      },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('Files in scope');
    expect(out).toContain('`docs/planning/BackendMultiplayerPlan.md`');
    expect(out).toContain('`simtests/SimCore.DotNet.Tests.csproj`');
    expect(out).toMatch(/cite these in task bodies/i);
    expect(out).toMatch(/do NOT invent unrelated paths/i);
  });

  it('handles shared_dependencies as plain strings', () => {
    const workItem = {
      id: 1,
      origin: { shared_dependencies: ['plain/path.txt'] },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('`plain/path.txt`');
  });

  it('reads allowed_files from origin (concrete scout work items)', () => {
    const workItem = {
      id: 2,
      origin: { allowed_files: ['simtests/FixedPointTests.cs', 'simtests/CombatTests.cs'] },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('`simtests/FixedPointTests.cs`');
    expect(out).toContain('`simtests/CombatTests.cs`');
  });

  it('reads allowed_files from constraints object (operator-seeded items)', () => {
    const workItem = {
      id: 3,
      constraints: { allowed_files: ['server/foo.js'], max_files: 1 },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('`server/foo.js`');
  });

  it('parses constraints_json string when constraints object missing', () => {
    const workItem = {
      id: 4,
      constraints_json: JSON.stringify({ allowed_files: ['lib/parsed.ts'] }),
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('`lib/parsed.ts`');
  });

  it('survives malformed constraints_json without throwing', () => {
    const workItem = {
      id: 5,
      constraints_json: '{not valid json',
    };
    expect(() => buildAutoGeneratedPlanPrompt(project, workItem)).not.toThrow();
  });

  it('omits the "Files in scope" section when no scope files are present', () => {
    const workItem = { id: 6, title: 'Plain item', description: 'No scope hints.' };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).not.toContain('Files in scope');
  });

  it('deduplicates files appearing in multiple sources', () => {
    const workItem = {
      id: 7,
      origin: {
        exemplar_files: ['shared/file.md'],
        allowed_files: ['shared/file.md', 'unique.md'],
        shared_dependencies: [{ file: 'shared/file.md' }],
      },
      constraints: { allowed_files: ['shared/file.md'] },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    const matches = out.match(/`shared\/file\.md`/g) || [];
    expect(matches.length).toBe(1);
    expect(out).toContain('`unique.md`');
  });

  it('skips empty/whitespace/non-string entries cleanly', () => {
    const workItem = {
      id: 8,
      origin: {
        exemplar_files: ['real.md', '', '   ', null, 42, 'another.md'],
      },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('`real.md`');
    expect(out).toContain('`another.md`');
    // No empty backticks should appear.
    expect(out).not.toMatch(/`\s*`/);
  });

  it('places "Files in scope" between Title and Description', () => {
    const workItem = {
      id: 9,
      title: 'Scope ordering test',
      description: 'A description.',
      origin: { exemplar_files: ['a.md'] },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    const titleIdx = out.indexOf('Scope ordering test');
    const scopeIdx = out.indexOf('Files in scope');
    const descIdx = out.indexOf('A description.');
    expect(titleIdx).toBeGreaterThan(0);
    expect(scopeIdx).toBeGreaterThan(titleIdx);
    expect(descIdx).toBeGreaterThan(scopeIdx);
  });

  it('preserves priorFeedback when scope files are also present', () => {
    const workItem = {
      id: 10,
      origin: { exemplar_files: ['fix-me.js'] },
    };
    const out = buildAutoGeneratedPlanPrompt(project, workItem, 'Prior reviewer feedback here.');
    expect(out.startsWith('Prior reviewer feedback here.')).toBe(true);
    expect(out).toContain('`fix-me.js`');
  });
});
