'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { _internalForTests } = require('../factory/loop-controller');

const { normalizeAutoGeneratedPlanMarkdown } = _internalForTests;

function withTempProject(callback) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'plan-generation-normalization-'));
  try {
    return callback(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeFixtureFile(repoPath, filePath, content = '// fixture\n') {
  const absolute = path.join(repoPath, filePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, content);
}

describe('normalizeAutoGeneratedPlanMarkdown', () => {
  it('preserves every path in a create-file list during path normalization', () => withTempProject((repoPath) => {
    writeFixtureFile(repoPath, 'package.json', '{"scripts":{"test":"vitest"}}\n');
    writeFixtureFile(repoPath, 'server/api-server.js');
    writeFixtureFile(repoPath, 'server/tests/api-server.test.js');
    writeFixtureFile(repoPath, 'dashboard/src/views/Workflows.test.jsx');

    const workItem = {
      id: 172,
      title: 'Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat)',
      description: 'Add per-file and per-hunk approval controls for multi-file diffs. Node.js, better-sqlite3.',
    };
    const rawPlan = [
      '# Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat) Plan',
      '',
      '## Task 1: Unified-Diff Parser, Selected-Hunk Applier, And Feedback Prompt',
      '',
      '- [ ] **Step 1: Create approval helper modules with focused server tests**',
      '',
      '    Create `server/approval/diff-parser.js`, `server/approval/diff-applier.js`, `server/approval/feedback-prompt.js`, `server/tests/diff-parser.test.js`, `server/tests/diff-applier.test.js`, and `server/tests/feedback-prompt.test.js`. Estimated scope: one parser helper, one selected-hunk applier, one feedback formatter, and focused tests.',
      '',
      '    The helpers must parse unified diffs, apply accepted hunks only, and format rejected hunk feedback.',
      '',
      '- [ ] **Step 2: Validate targeted change**',
      '',
      '    Run `npx vitest run server/tests/diff-parser.test.js server/tests/diff-applier.test.js server/tests/feedback-prompt.test.js` and expect all helper-level approval tests to pass.',
    ].join('\n');

    const normalized = normalizeAutoGeneratedPlanMarkdown(rawPlan, workItem, { id: 'p1', path: repoPath });

    expect(normalized).toContain('`server/approval/diff-applier.js`');
    expect(normalized).toContain('`server/approval/feedback-prompt.js`');
    expect(normalized).toContain('`server/tests/diff-applier.test.js`');
    expect(normalized).toContain('`server/tests/feedback-prompt.test.js`');
    expect(normalized).not.toContain('`server/api-server.js`, `server/api-server.js`');
    expect(normalized).not.toContain('`dashboard/src/views/Workflows.test.jsx`');
  }));

  it('preserves ordinary missing edit paths instead of replacing them with unrelated related files', () => withTempProject((repoPath) => {
    writeFixtureFile(repoPath, 'package.json', '{"scripts":{"test":"vitest"}}\n');
    writeFixtureFile(repoPath, 'dashboard/src/components/TaskSubmitForm.test.jsx');
    writeFixtureFile(repoPath, 'server/tests/vitest-setup.js');
    writeFixtureFile(repoPath, 'server/logger.js');

    const workItem = {
      id: 172,
      title: 'Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat)',
      description: 'Present multi-file diffs in the dashboard with per-file and per-hunk controls. Node.js, better-sqlite3.',
    };
    const rawPlan = [
      '# Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat) Plan',
      '',
      '## Task 1: Implement diff parser with proper DI container usage',
      '',
      '- [ ] **Step 1: Update diff parser tests**',
      '',
      '    Edit `server/tests/diff-parser.test.js` to use proper DI container imports instead of raw require(). Estimated scope: one missing test file and one helper-level suite.',
      '',
      '- [ ] **Step 2: Update diff parser implementation**',
      '',
      '    Edit `server/approval/diff-parser.js` to expose `parseUnifiedDiff(raw)` through the registered diff parser service. Success criteria: tests cover multiple files and hunks.',
      '',
      '- [ ] **Step 3: Validate targeted change**',
      '',
      '    Run `npx vitest run server/tests/diff-parser.test.js` and expect the parser tests to pass.',
    ].join('\n');

    const normalized = normalizeAutoGeneratedPlanMarkdown(rawPlan, workItem, { id: 'p1', path: repoPath });

    expect(normalized).toContain('server/tests/diff-parser.test.js');
    expect(normalized).toContain('server/approval/diff-parser.js');
    expect(normalized).not.toContain('dashboard/src/components/TaskSubmitForm.test.jsx');
  }));

  it('preserves explicit work-item validation when remote tests are disabled', () => withTempProject((repoPath) => {
    writeFixtureFile(repoPath, 'simtests/FixedPointTests.cs');
    writeFixtureFile(repoPath, 'client/UnityProject/Assets/Scripts/SimCore/FixedPoint.cs');
    writeFixtureFile(repoPath, 'simtests/SimCore.DotNet.Tests.csproj', '<Project />\n');

    const validation = 'dotnet test simtests/SimCore.DotNet.Tests.csproj -c Release --filter "FullyQualifiedName~FixedPointTests"';
    const workItem = {
      id: 2428,
      title: 'Add FixedPoint multiply divide and floor determinism coverage',
      description: 'Extend simtests/FixedPointTests.cs with deterministic cases for FixedPoint arithmetic.',
      origin: {
        allowed_files: [
          'simtests/FixedPointTests.cs',
          'client/UnityProject/Assets/Scripts/SimCore/FixedPoint.cs',
        ],
        verification: validation,
      },
    };
    const rawPlan = [
      '# Add FixedPoint multiply divide and floor determinism coverage Plan',
      '',
      '## Task 1: Add FixedPoint scaling and floor cases',
      '',
      '- [ ] **Step 1: Edit FixedPointTests scaling and floor coverage**',
      '',
      '    Edit `simtests/FixedPointTests.cs` only, adding focused NUnit cases for fixed-point scaling and floor behavior.',
      '',
      '- [ ] **Step 2: Validate targeted change**',
      '',
      `    Run \`${validation}\` and expect all FixedPointTests cases to pass.`,
    ].join('\n');

    const normalized = normalizeAutoGeneratedPlanMarkdown(rawPlan, workItem, {
      id: 'p1',
      path: repoPath,
      config: { prefer_remote_tests: false },
    });

    expect(normalized).toContain(`Run \`${validation}\``);
    expect(normalized).not.toContain('Run `git diff --check` and expect all FixedPointTests cases to pass');
  }));
});
