'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { _internalForTests } = require('../factory/loop-controller');

const { normalizeAutoGeneratedPlanMarkdown } = _internalForTests;

function withTempProject(callback) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'plan-generation-normalization-'));
  try {
    return callback(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeFixtureFile(repoPath, filePath, content = '// fixture\n') {
  const absolute = path.join(repoPath, filePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, content);
}

describe('normalizeAutoGeneratedPlanMarkdown', () => {
  it('preserves every path in a create-file list during path normalization', () => withTempProject((repoPath) => {
    writeFixtureFile(repoPath, 'package.json', '{"scripts":{"test":"vitest"}}\n');
    writeFixtureFile(repoPath, 'server/api-server.js');
    writeFixtureFile(repoPath, 'server/tests/api-server.test.js');
    writeFixtureFile(repoPath, 'dashboard/src/views/Workflows.test.jsx');

    const workItem = {
      id: 172,
      title: 'Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat)',
      description: 'Add per-file and per-hunk approval controls for multi-file diffs. Node.js, better-sqlite3.',
    };
    const rawPlan = [
      '# Fabro #44: Per-Hunk Approval Gates for Multi-File Edits (Mentat) Plan',
      '',
      '## Task 1: Unified-Diff Parser, Selected-Hunk Applier, And Feedback Prompt',
      '',
      '- [ ] **Step 1: Create approval helper modules with focused server tests**',
      '',
      '    Create `server/approval/diff-parser.js`, `server/approval/diff-applier.js`, `server/approval/feedback-prompt.js`, `server/tests/diff-parser.test.js`, `server/tests/diff-applier.test.js`, and `server/tests/feedback-prompt.test.js`. Estimated scope: one parser helper, one selected-hunk applier, one feedback formatter, and focused tests.',
      '',
      '    The helpers must parse unified diffs, apply accepted hunks only, and format rejected hunk feedback.',
      '',
      '- [ ] **Step 2: Validate targeted change**',
      '',
      '    Run `npx vitest run server/tests/diff-parser.test.js server/tests/diff-applier.test.js server/tests/feedback-prompt.test.js` and expect all helper-level approval tests to pass.',
    ].join('\n');

    const normalized = normalizeAutoGeneratedPlanMarkdown(rawPlan, workItem, { id: 'p1', path: repoPath });

    expect(normalized).toContain('`server/approval/diff-applier.js`');
    expect(normalized).toContain('`server/approval/feedback-prompt.js`');
    expect(normalized).toContain('`server/tests/diff-applier.test.js`');
    expect(normalized).toContain('`server/tests/feedback-prompt.test.js`');
    expect(normalized).not.toContain('`server/api-server.js`, `server/api-server.js`');
    expect(normalized).not.toContain('`dashboard/src/views/Workflows.test.jsx`');
  }));
});
