'use strict';

describe('event-bus plan-quality-gate emitters', () => {
  it('emitFactoryPlanRejectedQuality fires with event name factory:plan_rejected_quality', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryPlanRejectedQuality(spy);
    bus.emitFactoryPlanRejectedQuality({ project_id: 'p', work_item_id: 1, rule_violations: [], attempt: 1 });
    expect(spy).toHaveBeenCalledTimes(1);
    expect(spy.mock.calls[0][0]).toEqual({ project_id: 'p', work_item_id: 1, rule_violations: [], attempt: 1 });
  });

  it('emitFactoryPlanRejectedFinal fires with event name factory:plan_rejected_final', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryPlanRejectedFinal(spy);
    bus.emitFactoryPlanRejectedFinal({ project_id: 'p', work_item_id: 2, rule_violations: [] });
    expect(spy).toHaveBeenCalledTimes(1);
  });

  it('emitFactoryPlanGateSkipped fires with event name factory:plan_gate_skipped', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryPlanGateSkipped(spy);
    bus.emitFactoryPlanGateSkipped({ project_id: 'p', work_item_id: 3, reason: 'metadata_override' });
    expect(spy).toHaveBeenCalledTimes(1);
  });
});

describe('buildAutoGeneratedPlanPrompt priorFeedback parameter', () => {
  it('omits the prior-feedback section when priorFeedback is null', () => {
    const loopController = require('../factory/loop-controller');
    const prompt = loopController.buildAutoGeneratedPlanPrompt(
      { id: 'p', name: 'proj', path: '/tmp/p' },
      { id: 1, title: 'Item', description: 'Do a thing in src/foo.ts' },
      null,
    );
    expect(prompt).not.toContain('## Prior plan rejected');
  });

  it('prepends the prior-feedback block when priorFeedback is provided', () => {
    const loopController = require('../factory/loop-controller');
    const feedback = '## Prior plan rejected — address these issues.\n\nTask 2 has no file path.';
    const prompt = loopController.buildAutoGeneratedPlanPrompt(
      { id: 'p', name: 'proj', path: '/tmp/p' },
      { id: 1, title: 'Item', description: 'Do a thing in src/foo.ts' },
      feedback,
    );
    expect(prompt.startsWith('## Prior plan rejected')).toBe(true);
    expect(prompt).toContain('Task 2 has no file path.');
  });
});

describe('event-bus verify-review emitters', () => {
  it('emitFactoryProjectBaselineBroken fires factory:project_baseline_broken', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryProjectBaselineBroken(spy);
    bus.emitFactoryProjectBaselineBroken({ project_id: 'p', reason: 'r', failing_tests: ['t'], evidence: {} });
    expect(spy).toHaveBeenCalledTimes(1);
    expect(spy.mock.calls[0][0]).toEqual({ project_id: 'p', reason: 'r', failing_tests: ['t'], evidence: {} });
  });

  it('emitFactoryProjectBaselineCleared fires factory:project_baseline_cleared', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryProjectBaselineCleared(spy);
    bus.emitFactoryProjectBaselineCleared({ project_id: 'p', cleared_after_ms: 12345 });
    expect(spy).toHaveBeenCalledTimes(1);
  });

  it('emitFactoryProjectEnvironmentFailure fires factory:project_environment_failure', () => {
    const { createEventBus } = require('../event-bus');
    const bus = createEventBus();
    const spy = vi.fn();
    bus.onFactoryProjectEnvironmentFailure(spy);
    bus.emitFactoryProjectEnvironmentFailure({ project_id: 'p', signals: ['exit_127'], exit_code: 127 });
    expect(spy).toHaveBeenCalledTimes(1);
  });
});
