'use strict';
/* global describe, it, expect, beforeEach, afterEach */

const { buildAutoGeneratedPlanPrompt } = require('../factory/loop-controller');

describe('buildAutoGeneratedPlanPrompt — codegraph integration', () => {
  let prevPlannerEnv;
  let prevPluginEnv;

  beforeEach(() => {
    prevPlannerEnv = process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT;
    prevPluginEnv = process.env.TORQUE_CODEGRAPH_ENABLED;
  });
  afterEach(() => {
    if (prevPlannerEnv === undefined) delete process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT;
    else process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT = prevPlannerEnv;
    if (prevPluginEnv === undefined) delete process.env.TORQUE_CODEGRAPH_ENABLED;
    else process.env.TORQUE_CODEGRAPH_ENABLED = prevPluginEnv;
  });

  const project = { id: 1, name: 'demo', path: '/tmp/x', brief: 'A demo project.' };
  const workItem = { id: 7, title: 'Refactor BaseProvider', description: 'Change the BaseProvider abstract class to add a new lifecycle hook.' };

  it('includes the codegraph research section when TORQUE_CODEGRAPH_PLANNER_PROMPT=1', () => {
    process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT = '1';
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('Code-graph research');
    expect(out).toContain('cg_class_hierarchy');
    expect(out).toContain('cg_impact_set');
    expect(out).toContain('cg_find_references');
    expect(out).toContain('cg_reindex({repo_path, force:true, async:true})');
    expect(out).toContain('Do not use');
    expect(out).toContain('async:false');
  });

  it('omits the codegraph section by default (planner env var unset)', () => {
    delete process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT;
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).not.toContain('Code-graph research');
    expect(out).not.toContain('cg_class_hierarchy');
  });

  it('omits the codegraph section when the planner env var is "0"', () => {
    process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT = '0';
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).not.toContain('Code-graph research');
  });

  // Regression: enabling the codegraph PLUGIN (TORQUE_CODEGRAPH_ENABLED, the
  // var that defaults ON and is `0` to disable) must NOT advertise cg_* tools
  // in the plan prompt. Plan-gen worker CLIs do not receive the cg_* MCP
  // tools, so advertising them made the generator fabricate tool-call
  // transcripts with invented file paths and the quality gate rejected every
  // plan. The planner section is gated independently.
  it('does NOT advertise cg_* tools just because the codegraph plugin is enabled', () => {
    process.env.TORQUE_CODEGRAPH_ENABLED = '1';
    delete process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT;
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).not.toContain('Code-graph research');
    expect(out).not.toContain('cg_impact_set');
    expect(out).not.toContain('cg_find_references');
  });

  it('codegraph section sits between specificity signals and project context', () => {
    process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT = '1';
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    const cgIdx = out.indexOf('Code-graph research');
    const boundaryIdx = out.indexOf('Repository boundary (CRITICAL)');
    const specIdx = out.indexOf('Concrete language');
    const projIdx = out.indexOf('Project context:');
    // specificity signals -> repository boundary -> codegraph section -> project context
    expect(specIdx).toBeGreaterThan(0);
    expect(boundaryIdx).toBeGreaterThan(specIdx);
    expect(cgIdx).toBeGreaterThan(boundaryIdx);
    expect(projIdx).toBeGreaterThan(cgIdx);
  });

  it('preserves the priorFeedback prefix when codegraph is enabled', () => {
    process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT = '1';
    const out = buildAutoGeneratedPlanPrompt(project, workItem, 'Prior reviewer said: be more specific.');
    expect(out.startsWith('Prior reviewer said')).toBe(true);
    expect(out).toContain('Code-graph research');
  });

  it('always includes repository boundary rules that forbid Codex memories and outside paths', () => {
    delete process.env.TORQUE_CODEGRAPH_PLANNER_PROMPT;
    const out = buildAutoGeneratedPlanPrompt(project, workItem);
    expect(out).toContain('Repository boundary (CRITICAL)');
    expect(out).toContain('only files under the project path');
    expect(out).toContain('Codex memories');
    expect(out).toContain('`.codex/`');
    expect(out).toContain('`.torque/`');
    expect(out).toContain('outside the project tree');
  });
});
